/**
 * Packed Tier-2 density aggregate framing (`XYAG` → Worker → `XYAO`).
 *
 * TypeScript only packs point columns and reads the Rust output header. Binning
 * and mean-color policy stay in `xyg-engine` via `xyg_wasm_aggregate_bin2d`.
 */

import {
  XygWasmWorker,
  XygWasmError,
  type XygWasmAggregateTaskOptions,
  type XygWasmDiagnostics,
  type XygWasmTask,
} from "./47_wasm";
import { XYG_WASM_AGGREGATE_ACCUMULATOR_STRIDE_COLOR, XYG_WASM_AGGREGATE_ACCUMULATOR_STRIDE_COUNT, XYG_WASM_AGGREGATE_CHECKPOINT_POINTS, XYG_WASM_AGGREGATE_CHECKPOINT_STRIDE_COLOR, XYG_WASM_AGGREGATE_CHECKPOINT_STRIDE_COUNT, XYG_WASM_AGGREGATE_FLAG_MEAN_COLOR, XYG_WASM_AGGREGATE_HEADER_BYTES, XYG_WASM_AGGREGATE_MAGIC, XYG_WASM_AGGREGATE_MAX_GRID_CELLS, XYG_WASM_AGGREGATE_MAX_POINTS, XYG_WASM_AGGREGATE_MAX_REQUEST_BYTES, XYG_WASM_AGGREGATE_OFFSETS, XYG_WASM_AGGREGATE_OUTPUT_COPY_FACTOR, XYG_WASM_AGGREGATE_OUTPUT_HEADER_BYTES, XYG_WASM_AGGREGATE_OUTPUT_MAGIC, XYG_WASM_AGGREGATE_OUTPUT_OFFSETS, XYG_WASM_AGGREGATE_OUTPUT_STRIDE_COLOR, XYG_WASM_AGGREGATE_OUTPUT_STRIDE_COUNT, XYG_WASM_AGGREGATE_OUTPUT_VERSION, XYG_WASM_AGGREGATE_REQUEST_COPY_FACTOR, XYG_WASM_AGGREGATE_REQUEST_STRIDE_COLOR, XYG_WASM_AGGREGATE_REQUEST_STRIDE_COUNT, XYG_WASM_AGGREGATE_TOTAL_MEMORY_BYTES, XYG_WASM_AGGREGATE_VERSION } from "./wasm_abi_generated";
export { XYG_WASM_AGGREGATE_FLAG_MEAN_COLOR, XYG_WASM_AGGREGATE_HEADER_BYTES, XYG_WASM_AGGREGATE_OUTPUT_HEADER_BYTES, XYG_WASM_AGGREGATE_VERSION } from "./wasm_abi_generated";

export interface XygWasmAggregateInput {
  x: ArrayLike<number>;
  y: ArrayLike<number>;
  x0: number;
  x1: number;
  y0: number;
  y1: number;
  width: number;
  height: number;
  /** Straight-alpha RGBA8, length `4 * pointCount`. Enables mean-color plane. */
  rgba?: Uint8Array | number[];
}

export interface XygWasmAggregateGrid extends XygWasmDiagnostics {
  sequence: number;
  /** Packed `XYAO` buffer: header + f32 grid (+ optional RGBA8 mean colors). */
  aggregate: ArrayBuffer;
  width: number;
  height: number;
  maxCount: number;
  grid: Float32Array;
  rgba: Uint8Array | null;
}

function writeF64(view: DataView, offset: number, value: number) {
  if (!Number.isFinite(value)) {
    throw new TypeError("non-finite f64 is not allowed in XYAG requests");
  }
  view.setFloat64(offset, value, true);
}
function u32(value: number, name: string, positive = false) {
  if (!Number.isSafeInteger(value) || value < (positive ? 1 : 0) || value > 0xffff_ffff) throw new TypeError(`${name} must be a ${positive ? "positive " : ""}u32 integer`);
  return value;
}

/**
 * Pack points into the little-endian `XYAG` request consumed by
 * `xyg_wasm_aggregate_bin2d`. Framing only — no binning in TypeScript.
 */
export function encodeWasmAggregate(input: XygWasmAggregateInput): ArrayBuffer {
  if (!input || input.x.length !== input.y.length) {
    throw new TypeError("x and y must share the same length");
  }
  const pointCount = input.x.length;
  u32(pointCount, "point count"); u32(input.width, "width", true); u32(input.height, "height", true);
  if (pointCount > XYG_WASM_AGGREGATE_MAX_POINTS || input.width * input.height > XYG_WASM_AGGREGATE_MAX_GRID_CELLS) throw new RangeError("aggregate request exceeds the generated Rust bounds");
  if (!(input.x1 > input.x0) || !(input.y1 > input.y0)) {
    throw new TypeError("aggregate domains must satisfy hi > lo");
  }
  const wantColor = input.rgba != null;
  if (wantColor && input.rgba!.length !== pointCount * 4) {
    throw new TypeError("rgba must contain 4 bytes per point");
  }
  if (wantColor && Array.isArray(input.rgba) && input.rgba.some((value) => !Number.isInteger(value) || value < 0 || value > 255)) throw new TypeError("rgba values must be u8 integers");

  const payloadBytes = pointCount * (wantColor ? XYG_WASM_AGGREGATE_REQUEST_STRIDE_COLOR : XYG_WASM_AGGREGATE_REQUEST_STRIDE_COUNT);
  const requestBytes = XYG_WASM_AGGREGATE_HEADER_BYTES + payloadBytes;
  if (requestBytes > XYG_WASM_AGGREGATE_MAX_REQUEST_BYTES) {
    throw new RangeError("aggregate request exceeds the generated byte bound");
  }
  const cells = input.width * input.height;
  const accumulatorBytes = cells * (wantColor ? XYG_WASM_AGGREGATE_ACCUMULATOR_STRIDE_COLOR : XYG_WASM_AGGREGATE_ACCUMULATOR_STRIDE_COUNT);
  const outputBytes = XYG_WASM_AGGREGATE_OUTPUT_HEADER_BYTES + cells * (wantColor ? XYG_WASM_AGGREGATE_OUTPUT_STRIDE_COLOR : XYG_WASM_AGGREGATE_OUTPUT_STRIDE_COUNT);
  const checkpointBytes = Math.min(pointCount, XYG_WASM_AGGREGATE_CHECKPOINT_POINTS)
    * (wantColor ? XYG_WASM_AGGREGATE_CHECKPOINT_STRIDE_COLOR : XYG_WASM_AGGREGATE_CHECKPOINT_STRIDE_COUNT);
  // The transferred JS request coexists with its WASM copy, and the copied
  // XYAO transfer buffer briefly coexists with Rust-owned output.
  const totalBytes = XYG_WASM_AGGREGATE_REQUEST_COPY_FACTOR * requestBytes
    + accumulatorBytes
    + XYG_WASM_AGGREGATE_OUTPUT_COPY_FACTOR * outputBytes
    + checkpointBytes;
  if (!Number.isSafeInteger(totalBytes) || totalBytes > XYG_WASM_AGGREGATE_TOTAL_MEMORY_BYTES) {
    throw new RangeError("aggregate request exceeds the generated total memory bound");
  }
  const bytes = new Uint8Array(requestBytes);
  const view = new DataView(bytes.buffer);
  bytes.set(new TextEncoder().encode(XYG_WASM_AGGREGATE_MAGIC), 0);
  view.setUint32(XYG_WASM_AGGREGATE_OFFSETS.version, XYG_WASM_AGGREGATE_VERSION, true);
  view.setUint32(XYG_WASM_AGGREGATE_OFFSETS.header_bytes, XYG_WASM_AGGREGATE_HEADER_BYTES, true);
  view.setUint32(XYG_WASM_AGGREGATE_OFFSETS.flags, wantColor ? XYG_WASM_AGGREGATE_FLAG_MEAN_COLOR : 0, true);
  view.setUint32(XYG_WASM_AGGREGATE_OFFSETS.point_count, pointCount, true);
  view.setUint32(XYG_WASM_AGGREGATE_OFFSETS.width, input.width, true);
  view.setUint32(XYG_WASM_AGGREGATE_OFFSETS.height, input.height, true);
  writeF64(view, XYG_WASM_AGGREGATE_OFFSETS.x0, input.x0);
  writeF64(view, XYG_WASM_AGGREGATE_OFFSETS.x1, input.x1);
  writeF64(view, XYG_WASM_AGGREGATE_OFFSETS.y0, input.y0);
  writeF64(view, XYG_WASM_AGGREGATE_OFFSETS.y1, input.y1);

  let offset = XYG_WASM_AGGREGATE_HEADER_BYTES;
  for (let index = 0; index < pointCount; index++) {
    writeF64(view, offset + index * 8, input.x[index]!);
  }
  offset += pointCount * 8;
  for (let index = 0; index < pointCount; index++) {
    writeF64(view, offset + index * 8, input.y[index]!);
  }
  offset += pointCount * 8;
  if (wantColor) {
    bytes.set(input.rgba as ArrayLike<number>, offset);
  }
  return bytes.buffer;
}

export function decodeWasmAggregateOutput(buffer: ArrayBuffer): {
  width: number;
  height: number;
  maxCount: number;
  grid: Float32Array;
  rgba: Uint8Array | null;
} {
  const bytes = new Uint8Array(buffer);
  if (bytes.length < XYG_WASM_AGGREGATE_OUTPUT_HEADER_BYTES) {
    throw new TypeError("aggregate output is truncated");
  }
  if (new TextDecoder().decode(bytes.subarray(0, 4)) !== XYG_WASM_AGGREGATE_OUTPUT_MAGIC) {
    throw new TypeError("aggregate output missing XYAO magic");
  }
  const view = new DataView(buffer);
  const version = view.getUint32(XYG_WASM_AGGREGATE_OUTPUT_OFFSETS.version, true);
  const headerBytes = view.getUint32(XYG_WASM_AGGREGATE_OUTPUT_OFFSETS.header_bytes, true);
  const flags = view.getUint32(XYG_WASM_AGGREGATE_OUTPUT_OFFSETS.flags, true);
  const width = view.getUint32(XYG_WASM_AGGREGATE_OUTPUT_OFFSETS.width, true);
  const height = view.getUint32(XYG_WASM_AGGREGATE_OUTPUT_OFFSETS.height, true);
  const maxCount = view.getFloat32(XYG_WASM_AGGREGATE_OUTPUT_OFFSETS.max_count, true);
  if (version !== XYG_WASM_AGGREGATE_OUTPUT_VERSION || headerBytes !== XYG_WASM_AGGREGATE_OUTPUT_HEADER_BYTES) {
    throw new TypeError("unsupported aggregate output version");
  }
  const cells = width * height;
  if (!width || !height || cells > XYG_WASM_AGGREGATE_MAX_GRID_CELLS || view.getUint32(XYG_WASM_AGGREGATE_OUTPUT_OFFSETS.reserved, true) !== 0 || flags & ~XYG_WASM_AGGREGATE_FLAG_MEAN_COLOR) throw new TypeError("aggregate output header is malformed");
  const gridBytes = cells * 4;
  const wantColor = (flags & XYG_WASM_AGGREGATE_FLAG_MEAN_COLOR) !== 0;
  const expected = headerBytes + gridBytes + (wantColor ? cells * 4 : 0);
  if (bytes.length !== expected) {
    throw new TypeError("aggregate output length does not match width/height");
  }
  const grid = new Float32Array(buffer, headerBytes, cells);
  const rgba = wantColor
    ? new Uint8Array(buffer, headerBytes + gridBytes, cells * 4)
    : null;
  return { width, height, maxCount, grid, rgba };
}

export function aggregateWasmBin2d(
  worker: XygWasmWorker,
  request: ArrayBuffer | Uint8Array | XygWasmAggregateInput,
  options: XygWasmAggregateTaskOptions = {},
): XygWasmTask<XygWasmAggregateGrid> {
  const buffer = request instanceof ArrayBuffer || request instanceof Uint8Array
    ? request
    : new Uint8Array(encodeWasmAggregate(request));
  const task = worker.aggregateBin2d(buffer, options);
  return {
    requestId: task.requestId,
    sequence: task.sequence,
    cancel: () => task.cancel(),
    result: task.result.then((value) => {
      try {
        const decoded = decodeWasmAggregateOutput(value.aggregate);
        return {
          ...value,
          ...decoded,
        };
      } catch (cause) {
        // The Worker returned a successful transport envelope, so this is a
        // contract breach at the XYAO boundary rather than a caller error.
        // Preserve the Rust-owned accounting snapshot while making the
        // failure actionable to direct ChartView consumers.
        throw new XygWasmError(
          "XYG_WASM_MALFORMED_OUTPUT",
          cause instanceof Error ? cause.message : "aggregate output is malformed",
          null,
          value,
        );
      }
    }),
  };
}
