/** Exact original-row membership for nonfinal temporal-domain cells (§27/§29/§34). */
import {encodeGeoScaleRequest} from './63_geo_source';
import type {XygGeoScaleBridge,XygGeoQueryBudget} from './63_geo_source';
import {GeoAllocationAttempt,forgetGeoAllocationIssuer} from './72_geo_allocation_attempt';
import {withGeoWorkerMemberDataOutcome as withGeoMemberDataOutcome} from './47_wasm';
const HEADER=256, COOKIE=128, MAX=HEADER+4096*32, CAP=Symbol('issued members');
interface Context {issuer:XygGeoScaleBridge;issuerExecute:XygGeoScaleBridge['execute'];handle:bigint;sequence:bigint;transport:XygGeoScaleBridge;reader:(ticket:Record<string,unknown>,signal?:AbortSignal)=>Promise<ArrayBuffer|Uint8Array>;budget:XygGeoQueryBudget;header:Uint8Array}
const contexts=new WeakMap<object,Context>();
export function registerOverviewMembers(frame:object,transport:XygGeoScaleBridge,reader:Context['reader'],budget:XygGeoQueryBudget,header:Uint8Array,handle:bigint,sequence:bigint,issuer:XygGeoScaleBridge,issuerExecute:XygGeoScaleBridge['execute']){contexts.set(frame,Object.freeze({issuer,issuerExecute,handle,sequence,transport,reader,budget:Object.freeze({...budget}),header:header.slice()}));}
const capturedContexts=new WeakMap<object,Context>();
/** Opaque private callback/snapshot capture before asynchronous retained allocation. */
export function captureOverviewMembers(from:object):object{const context=contexts.get(from);if(!context)throw new TypeError('Issued overview membership context required');const token=Object.freeze({});capturedContexts.set(token,context);return token;}
export function installOverviewMembers(token:object,to:object,handle:bigint,sequence:bigint){const context=capturedContexts.get(token);if(!context||handle===0n||sequence===0n)throw new TypeError('Issued retained membership capture required');contexts.set(to,Object.freeze({...context,handle,sequence}));}
export function copyOverviewMembers(from:object,to:object,handle:bigint,sequence:bigint){const c=contexts.get(from);if(!c)throw new TypeError('Issued overview membership context required');contexts.set(to,Object.freeze({...c,handle,sequence}));}
export function dropOverviewMembers(frame:object){contexts.delete(frame);}
function zeros(b:Uint8Array,a:number,z:number){if(b.subarray(a,z).some(n=>n!==0))throw new TypeError('Nonzero domain-member reserved bytes');}
function u64(n:bigint){if(typeof n!=='bigint'||n<=0n||n>0xffffffffffffffffn)throw new TypeError('Nonzero u64 required');}
export function encodeOverviewMembersRequest(command:number,handle:bigint,sequence:bigint,budget?:XygGeoQueryBudget,payload?:Uint8Array){if(![6,7,8,9,10,23,45,46].includes(command))throw new TypeError('Unknown domain-member command');const b=encodeGeoScaleRequest({command:6,handle,sequence,budget,payload});new DataView(b).setUint32(8,command,true);return b;}
export function decodeOverviewMembersReply(packet:ArrayBuffer){if(!(packet instanceof ArrayBuffer)||packet.byteLength!==HEADER)throw new TypeError('Fixed domain-member reply required');const b=new Uint8Array(packet),v=new DataView(packet),code=v.getUint32(8,true);if(v.getUint32(0,true)!==0x5a475958||v.getUint32(4,true)!==1||![0,1,2,9,21].includes(code))throw new TypeError('Invalid domain-member reply');zeros(b,12,16);let ticket:Uint8Array|null=null;
 if(code===1||code===2&&b.subarray(64,192).some(n=>n!==0)){zeros(b,32,64);zeros(b,192,256);ticket=b.slice(64,192);const t=new DataView(ticket.buffer),length=t.getBigUint64(56,true);if(t.getUint32(24,true)!==1||length<64n||length>16n*1024n*1024n||t.getUint32(44,true)===0)throw new TypeError('Invalid domain-member cookie');zeros(ticket,28,32);zeros(ticket,72,128);}
 else if(code===21){if(v.getBigUint64(32,true)>4096n||v.getUint32(56,true)>1)throw new TypeError('Invalid domain-member completion');zeros(b,60,64);zeros(b,88,256);}
 else{zeros(b,48,256);if(code!==0)zeros(b,32,48);}
 return {code,handle:v.getBigUint64(16,true),sequence:v.getBigUint64(24,true),dataLength:v.getBigUint64(32,true),sourceHandle:v.getBigUint64(40,true),ticket,raw:b};}
function receipt(packet:ArrayBuffer,handle:bigint,sequence:bigint,code=0){const r=decodeOverviewMembersReply(packet);if(r.handle!==handle||r.sequence!==sequence||r.code!==code)throw new TypeError('Domain-member mutation did not confirm settlement');zeros(r.raw,32,256);return r;}
/** Called only for private known46 Data after unresolved attempted10, never45 birth. */
async function knownMemberDataAbsent(c:Context,handle:bigint,sequence:bigint){
 const canonical=encodeOverviewMembersRequest(6,handle,sequence);
 return withGeoMemberDataOutcome(c.issuer,canonical,async outcome=>{
  try{const packet=await c.transport.execute(canonical.slice(0));if(!outcome(packet)?.reply)throw new TypeError('MemberData probe lacks genuine current producer outcome');const r=decodeOverviewMembersReply(packet);if(r.code!==0||r.handle!==handle||r.sequence!==sequence||r.sourceHandle!==handle||r.dataLength<256n||r.dataLength>BigInt(MAX))throw new TypeError('Known MemberData probe kind/receipt mismatch');return false;}
  catch(error){const proof=outcome(error);if(proof&&(proof.status===-10&&proof.code===undefined||proof.status===7&&proof.code==='XYG_GEO_SOURCE_STALE'))return true;throw error;}
 },c.issuerExecute);
}
function abort(){return new DOMException('Domain membership aborted','AbortError');}
export class GeoOverviewMembershipUncertain extends Error {readonly owner:GeoOverviewMembershipOperation;readonly cause:unknown;constructor(owner:GeoOverviewMembershipOperation,cause:unknown){super('Domain-member allocation confirmation uncertain; recover the exact issued allocation');this.name='GeoOverviewMembershipUncertain';this.owner=owner;this.cause=cause;}}
export class GeoOverviewMembershipCleanupPending extends Error {readonly owner:GeoOverviewMembershipOperation|GeoOverviewMembershipPage;readonly cause:unknown;constructor(owner:GeoOverviewMembershipOperation|GeoOverviewMembershipPage,cause:unknown){super('Domain-member cleanup pending; retry owner.dispose()');this.name='GeoOverviewMembershipCleanupPending';this.owner=owner;this.cause=cause;}}
export class GeoOverviewMembershipPublicationPending extends Error {readonly owner:GeoOverviewMembershipOperation;readonly cause:unknown;constructor(owner:GeoOverviewMembershipOperation,cause:unknown){super('Membership publication deferred; known Query confirmed, retry owner.prepare() or dispose()');this.owner=owner;this.cause=cause;}}
export interface GeoOverviewMembersInput {sequence:bigint;maxVertices:bigint;signal?:AbortSignal}
const pending=new WeakMap<object,GeoOverviewMembershipOperation>();
export async function overviewMembers(frame:object,cell:number,input:GeoOverviewMembersInput){const c=contexts.get(frame);if(!c)throw new TypeError('Privately issued live overview frame required');return start(frame,c,c.handle,c.sequence,cell,input,0n);}
async function start(owner:object,c:Context,handle:bigint,sequence:bigint,cell:number,input:GeoOverviewMembersInput,prior:bigint,after=-1n){if(!Number.isInteger(cell)||cell<0||cell>=256)throw new TypeError('Domain cell must be0..255');u64(input.sequence);u64(input.maxVertices);const prev=pending.get(owner);if(prev&&!prev.closed)throw new GeoOverviewMembershipUncertain(prev,new Error('Previous membership operation remains pending'));if(input.signal?.aborted)throw abort();const payload=new Uint8Array(24),v=new DataView(payload.buffer);v.setBigUint64(0,input.sequence,true);v.setUint32(8,cell,true);v.setBigUint64(16,input.maxVertices,true);const allocationRequest=encodeOverviewMembersRequest(45,handle,sequence,c.budget,payload);const op=new GeoOverviewMembershipOperation(CAP,c,cell,input.sequence,prior,after,owner,allocationRequest);pending.set(owner,op);
 try{await canonicalAdmit.call(op);await canonicalDrive.call(op,input.signal);const page=await canonicalPrepare.call(op,input.signal);pending.delete(owner);return page;}catch(cause){if(op.retryablePublication&&!(cause instanceof DOMException&&cause.name==='AbortError'))throw new GeoOverviewMembershipPublicationPending(op,cause);if(!op.uncertain){try{await canonicalDispose.call(op);pending.delete(owner);}catch(cleanup){throw new GeoOverviewMembershipCleanupPending(op,cleanup);}}throw cause;}}
export class GeoOverviewMembershipOperation {
 #attempt:GeoAllocationAttempt;#recovery:Promise<GeoOverviewMembershipPage>|undefined;#disposeAttempted=false;#disposed=false;#dataReceipt:ReturnType<typeof decodeOverviewMembersReply>|undefined;#c:Context;#cell:number;#sequence:bigint;#prior:bigint;#after:bigint;#handle=0n;#phase:'admitting'|'query'|'complete'|'publication'|'data'|'uncertain'|'closed'='admitting';#loan:Uint8Array|undefined;#active:Promise<unknown>|undefined;#admission:Promise<void>|undefined;#dispose:Promise<void>|undefined;#page:GeoOverviewMembershipPage|undefined;#completion:Uint8Array|undefined;#publishAttempted=false;#publication:Promise<GeoOverviewMembershipPage>|undefined;#closing=false;
 constructor(cap:symbol,c:Context,cell:number,sequence:bigint,prior:bigint,after:bigint,owner:object,request:ArrayBuffer){if(cap!==CAP)throw new TypeError('Private domain-member operation required');this.#c=c;this.#cell=cell;this.#sequence=sequence;this.#prior=prior;this.#after=after;this.#attempt=new GeoAllocationAttempt(owner,c.transport,request,sequence);}
 get retryablePublication(){return this.#publishAttempted&&this.#phase==='complete';}
 get handle(){return this.#handle;}get sequence(){return this.#sequence;}get uncertain(){return this.#phase==='uncertain';}get closed(){return this.#phase==='closed';}
 #request(command:number,payload?:Uint8Array){return encodeOverviewMembersRequest(command,this.#handle,this.#sequence,this.#c.budget,payload);}
 #validateAllocation(packet:ArrayBuffer){const r=decodeOverviewMembersReply(packet);if(r.code!==0||r.handle===0n||r.sequence!==this.#sequence||r.dataLength!==0n||r.sourceHandle!==0n)throw new TypeError('Invalid membership allocation receipt');return r.handle;}
 async admit(){if(this.#admission)return this.#admission;this.#admission=(async()=>{try{const packet=await this.#attempt.recover(packet=>this.#validateAllocation(packet));if(!packet){this.#phase='closed';return;}this.#handle=decodeOverviewMembersReply(packet).handle;this.#phase='query';}catch(cause){this.#admission=undefined;if(this.#attempt.rejected){this.#phase='closed';throw cause;}this.#phase='uncertain';throw new GeoOverviewMembershipUncertain(this,cause);}})();return this.#admission;}
 recover(signal?:AbortSignal){if(this.#recovery)return this.#recovery;const task=Promise.resolve().then(async()=>{if(this.#closing||this.closed)throw new Error('Membership operation closed');if(this.#phase==='admitting'||this.uncertain)await canonicalAdmit.call(this);if(this.closed)throw new Error('Membership allocation retired');if(this.#phase==='query')await canonicalDrive.call(this,signal);return canonicalPrepare.call(this,signal);});this.#recovery=task;void task.finally(()=>{if(this.#recovery===task)this.#recovery=undefined;}).catch(()=>{});return task;}
 async #cancel(){const r=decodeOverviewMembersReply(await this.#c.transport.execute(this.#request(9)));if(r.handle!==this.#handle||r.sequence!==this.#sequence||![2,9].includes(r.code))throw new TypeError('Domain-member cancel unconfirmed');if(r.code===2&&(!this.#loan||!r.ticket||r.ticket.some((n,i)=>n!==this.#loan![i])))throw new TypeError('Domain-member cancel loan mismatch');return r;}
 async #settle(){if(!this.#loan)return;try{receipt(await this.#c.transport.execute(this.#request(8,this.#loan.slice())),this.#handle,this.#sequence);}catch(cause){const r=await this.#cancel();if(r.code!==9)throw cause;zeros(r.raw,32,256);}this.#loan=undefined;}
 async drive(signal?:AbortSignal){if(this.#phase!=='query'||this.#active)throw new Error('Membership query not idle');const task=(async()=>{await this.#settle();for(;;){if(signal?.aborted){await this.#cancel();throw abort();}const r=decodeOverviewMembersReply(await this.#c.transport.execute(this.#request(6)));if(r.handle!==this.#handle||r.sequence!==this.#sequence)throw new TypeError('Membership operation mismatch');if(r.code===21){this.#completion=r.raw.slice();this.#phase='complete';return;}if(r.code!==1||!r.ticket)throw new Error('Membership query not complete');const authority=r.ticket.slice(),t=new DataView(authority.buffer),length=Number(t.getBigUint64(56,true));if(t.getBigUint64(16,true)!==this.#sequence||t.getBigUint64(0,true)===0n||t.getBigUint64(32,true)!==new DataView(this.#c.header.buffer).getBigUint64(56,true)||t.getBigUint64(48,true)+BigInt(t.getUint32(44,true))>new DataView(this.#c.header.buffer).getBigUint64(88,true))throw new TypeError('Membership cookie identity mismatch');this.#loan=authority;
 let borrowed:ArrayBuffer|Uint8Array|undefined,view:Uint8Array|undefined,payload:Uint8Array|undefined,request:ArrayBuffer|undefined;
 try{if(4*(256+128+length)>this.#c.budget.processorBytes)throw new RangeError('Membership transfer exceeds budget');const ticket={raw:authority.slice(),kind:1,owner:t.getBigUint64(0,true),serial:t.getBigUint64(8,true),sequence:this.#sequence,generation:t.getBigUint64(32,true),chunkIndex:t.getUint32(40,true),rows:t.getUint32(44,true),firstRow:t.getBigUint64(48,true),encodedBytes:length,digest:authority.slice(64,72)};borrowed=await this.#c.reader(ticket,signal);view=borrowed instanceof ArrayBuffer?new Uint8Array(borrowed):borrowed;if(!(view instanceof Uint8Array)||view.byteLength!==length||view.buffer.byteLength!==length)throw new TypeError('Exact owning membership chunk required');if(signal?.aborted){await this.#cancel();throw abort();}payload=new Uint8Array(128+length);payload.set(authority);payload.set(view,128);request=this.#request(7,payload);payload=undefined;receipt(await this.#c.transport.execute(request),this.#handle,this.#sequence);if(signal?.aborted){await this.#cancel();throw abort();}}
 catch(cause){borrowed=view=payload=request=undefined;await this.#cancel();throw cause;}finally{borrowed=view=payload=request=undefined;await this.#settle();}
 }})();this.#active=task;try{await task;}finally{this.#active=undefined;}}
 async #probe(){const r=decodeOverviewMembersReply(await this.#c.transport.execute(this.#request(6)));if(r.handle!==this.#handle||r.sequence!==this.#sequence)throw new TypeError('Membership publication probe mismatch');if(r.code===21){this.#phase='complete';return null;}if(r.code===0&&r.sourceHandle===this.#handle&&r.dataLength>=256n&&r.dataLength<=BigInt(MAX)){this.#phase='data';this.#dataReceipt=r;return r;}throw new Error('Membership publication remains unresolved');}
 prepare(signal?:AbortSignal){if(this.#closing)throw new Error('Membership operation closing');if(this.#publication)return this.#publication;const task=this.#prepare(signal);this.#publication=task;task.catch(()=>{if(this.#publication===task)this.#publication=undefined;});return task;}
 async #prepare(signal?:AbortSignal){if(this.#phase==='data'&&this.#dataReceipt)return this.#read(this.#dataReceipt,signal);if(this.#phase==='publication'){const r=await this.#probe();if(r)return this.#read(r,signal);}if(this.#phase!=='complete')throw new Error('Membership query not complete');if(signal?.aborted)throw abort();this.#publishAttempted=true;this.#phase='publication';let r;try{r=decodeOverviewMembersReply(await this.#c.transport.execute(this.#request(46)));if(r.code!==0||r.handle!==this.#handle||r.sequence!==this.#sequence||r.sourceHandle!==this.#handle||r.dataLength<256n||r.dataLength>BigInt(MAX))throw new TypeError('Invalid member Data receipt');this.#phase='data';this.#dataReceipt=r;}catch(cause){r=await this.#probe();if(!r)throw cause;}return this.#read(r,signal);}
 async #read(r:ReturnType<typeof decodeOverviewMembersReply>,signal?:AbortSignal){await this.#attempt.release();if(4n*r.dataLength>BigInt(this.#c.budget.processorBytes))throw new RangeError('Membership output exceeds budget');let packet:ArrayBuffer|undefined;try{packet=await this.#c.transport.read(this.#request(23));if(BigInt(packet.byteLength)!==r.dataLength)throw new TypeError('Membership output length mismatch');const page=new GeoOverviewMembershipPage(CAP,this.#c,this.#handle,this.#sequence,this.#cell,this.#prior,packet,this.#completion,this.#after);this.#page=page;packet=undefined;if(signal?.aborted||this.#closing){await page.dispose();this.#phase='closed';throw abort();}this.#phase='closed';return page;}catch(cause){packet=undefined;throw cause;}}
 async dispose(){if(this.closed)return;this.#closing=true;if(this.#active)await this.#cancel();if(this.#recovery)await this.#recovery.catch(()=>{});if(this.closed)return;if(this.#publication){try{await this.#publication;}catch{}}if(this.closed)return;if(this.#admission){try{await this.#admission;}catch{}}if(this.uncertain){await canonicalAdmit.call(this);if(this.closed)return;}if(this.#active){await this.#cancel();try{await this.#active;}catch{}}await this.#settle();if(this.#phase==='publication')await this.#probe();if(this.#page){await this.#page.dispose();this.#phase='closed';return;}const sequence=this.#phase==='data'?0n:this.#sequence;if(!this.#dispose)this.#dispose=Promise.resolve().then(async()=>{if(sequence===0n&&this.#disposeAttempted&&!this.#disposed){this.#disposed=await knownMemberDataAbsent(this.#c,this.#handle,this.#sequence);}if(sequence!==0n&&this.#disposeAttempted&&!this.#disposed){if(!await this.#attempt.probeRetirement(packet=>this.#validateAllocation(packet)))this.#disposed=true;}if(!this.#disposed){this.#disposeAttempted=true;receipt(await this.#c.transport.execute(encodeOverviewMembersRequest(10,this.#handle,sequence)),this.#handle,sequence);this.#disposed=true;}await this.#attempt.release();this.#phase='closed';}).catch(cause=>{this.#dispose=undefined;throw cause;});return this.#dispose;}

}
export interface GeoOverviewMemberRecord {featureId:bigint;sourceRow:bigint;chunkIndex:number;row:number;matchedVertices:bigint}
export class GeoOverviewMembershipPage {
 #c:Context|undefined;#handle:bigint;#sequence:bigint;#cell:number;#cumulative:bigint;#next:boolean;#packet:ArrayBuffer|undefined;#count:number;#after:bigint;#disposal:Promise<void>|undefined;#inspection=false;#disposed=false;#disposeAttempted=false;
 constructor(cap:symbol,c:Context,handle:bigint,sequence:bigint,cell:number,prior:bigint,packet:ArrayBuffer,completion?:Uint8Array,after=-1n){if(cap!==CAP)throw new TypeError('Private membership Page required');this.#c=c;this.#handle=handle;this.#sequence=sequence;this.#cell=cell;const parsed=parseOverviewMembers(packet,c.header,handle,sequence,cell,prior,completion,after);this.#after=parsed.lastRow;this.#count=parsed.count;this.#next=parsed.hasNext;this.#cumulative=parsed.cumulative;this.#packet=packet;}
 get handle(){return this.#handle;}get sequence(){return this.#sequence;}get count(){this.#live();return this.#count;}get hasNext(){this.#live();return this.#next;}get cumulativeVertices(){this.#live();return this.#cumulative;}get cell(){return this.#cell;}get temporalExact(){return true;}get dataSpace(){return true;}get final(){return false;}
 #live(){if(!this.#packet)throw new Error('Membership Page views disposed');return this.#packet;}
 copyBytes(){if(this.#inspection)throw new RangeError('One bounded membership inspection copy per Page');const bytes=new Uint8Array(this.#live()).slice();this.#inspection=true;return bytes;}
 record(i:number):GeoOverviewMemberRecord{if(!Number.isInteger(i)||i<0||i>=this.#count)throw new RangeError('Membership record index');const v=new DataView(this.#live(),256+i*32,32);return {featureId:v.getBigUint64(0,true),sourceRow:v.getBigUint64(8,true),chunkIndex:v.getUint32(16,true),row:v.getUint32(20,true),matchedVertices:v.getBigUint64(24,true)};}
 nextPage(input:GeoOverviewMembersInput){this.#live();if(!this.#next)throw new Error('Terminal membership Page has no continuation');if(input.sequence<=this.#sequence)throw new TypeError('Continuation sequence must advance');return start(this,this.#c!,this.#handle,this.#sequence,this.#cell,input,this.#cumulative,this.#after);}
 async dispose(){this.#packet=undefined;if(!this.#disposal)this.#disposal=Promise.resolve().then(async()=>{if(this.#disposeAttempted&&!this.#disposed)this.#disposed=await knownMemberDataAbsent(this.#c!,this.#handle,this.#sequence);if(!this.#disposed){this.#disposeAttempted=true;receipt(await this.#c!.transport.execute(encodeOverviewMembersRequest(10,this.#handle,0n)),this.#handle,0n);this.#disposed=true;}await forgetGeoAllocationIssuer(this);this.#c=undefined;}).catch(cause=>{this.#disposal=undefined;throw cause;});return this.#disposal;}
}
export function parseOverviewMembers(packet:ArrayBuffer,header:Uint8Array,handle:bigint,sequence:bigint,cell:number,prior:bigint,completion?:Uint8Array,after=-1n){if(!(packet instanceof ArrayBuffer)||packet.byteLength<256||packet.byteLength>MAX)throw new TypeError('Bounded XYOM required');const b=new Uint8Array(packet),v=new DataView(packet),h=new DataView(header.buffer,header.byteOffset,header.byteLength),count=v.getBigUint64(32,true),hasNext=v.getUint32(44,true);if(v.getUint32(0,true)!==0x4d4f5958||v.getUint32(4,true)!==1||v.getUint32(8,true)!==3||v.getUint32(12,true)!==16||v.getBigUint64(16,true)!==handle||v.getBigUint64(24,true)!==sequence||v.getUint32(40,true)!==cell||count>4096n||BigInt(packet.byteLength)!==256n+32n*count||hasNext>1)throw new TypeError('Invalid exact domain-member header');zeros(b,220,224);zeros(b,248,256);
 for(const [to,from,n] of [[64,88,8],[72,56,8],[80,64,8],[88,48,8],[96,80,8],[104,72,8],[112,96,8],[120,112,56],[176,176,40],[216,224,4],[224,232,16]])if(b.subarray(to,to+n).some((x,i)=>x!==header[from+i]))throw new TypeError('Membership differs from private overview snapshot');
 const expected=h.getBigUint64(256+8*cell,true),cumulative=v.getBigUint64(56,true);if(v.getBigUint64(48,true)!==expected||cumulative>expected||cumulative<prior||!hasNext&&cumulative!==expected)throw new TypeError('Membership counts mismatch');let sum=0n,last=after;for(let i=0;i<Number(count);i++){const p=256+32*i,row=v.getBigUint64(p+8,true),n=v.getBigUint64(p+24,true);if(row<=last||row>=h.getBigUint64(88,true)||n===0n||h.getUint32(76,true)===1&&n!==1n)throw new TypeError('Invalid physical membership row');last=row;sum+=n;}if(sum!==v.getBigUint64(240,true)||sum+prior!==cumulative)throw new TypeError('Matched vertex count mismatch');if(completion){const c=new DataView(completion.buffer,completion.byteOffset);if(c.getBigUint64(32,true)!==count||c.getBigUint64(40,true)!==expected||c.getBigUint64(48,true)!==cumulative||c.getUint32(56,true)!==hasNext)throw new TypeError('Membership completion mismatch');}return {count:Number(count),hasNext:hasNext===1,cumulative,lastRow:last};}

const canonicalAdmit=GeoOverviewMembershipOperation.prototype.admit,canonicalDrive=GeoOverviewMembershipOperation.prototype.drive,canonicalPrepare=GeoOverviewMembershipOperation.prototype.prepare,canonicalDispose=GeoOverviewMembershipOperation.prototype.dispose;
