// Generated by scripts/gen_wasm_abi.py from spec/wasm/abi.json.
// Do not hand-edit raw WASM signatures or status numbers here.

export const XYG_WASM_ABI_VERSION = 6 as const;
export const XYG_WASM_SCENE_VERSION = 10 as const;
export const XYG_WASM_PAINTER_VERSION = 7 as const;
export const XYG_WASM_PAINTER_HEADER_BYTES = 288 as const;
export const XYG_WASM_PAINTER_TRACE_BYTES = 64 as const;
export const XYG_WASM_PAINTER_TICK_BYTES = 16 as const;
export const XYG_WASM_PAINTER_MAX_TRACES = 1024 as const;
export const XYG_WASM_TYPED_SERIES_VERSION = 1 as const;
export const XYG_WASM_TYPED_SERIES_HEADER_BYTES = 192 as const;
export const XYG_WASM_TYPED_SERIES_DESCRIPTOR_BYTES = 96 as const;
export const XYG_WASM_TYPED_SERIES_MAX_SERIES = 4096 as const;
export const XYG_WASM_TYPED_SERIES_MAX_RECORDS = 10000000 as const;
export const XYG_WASM_TYPED_SERIES_MAX_TEXT_BYTES = 4096 as const;
export const XYG_WASM_TYPED_SERIES_MAX_SYMBOL_CODE = 18 as const;
export const XYG_WASM_TYPED_SERIES_PEAK_FIXED_BYTES = 4096 as const;
export const XYG_WASM_TYPED_SERIES_PEAK_BYTES_PER_RECORD = 256 as const;
export const XYG_WASM_TYPED_SERIES_PEAK_BYTES_PER_SERIES = 1024 as const;
export const XYG_WASM_TYPED_SERIES_PEAK_INPUT_MULTIPLIER = 2 as const;
export const XYG_WASM_MAX_ARENA_BYTES = 402653184 as const;
export const XYG_WASM_PAINTER_MAX_LEGEND_BYTES = 57424 as const;
export const XYG_WASM_AGGREGATE_VERSION = 1 as const;
export const XYG_WASM_AGGREGATE_MAGIC = "XYAG" as const;
export const XYG_WASM_AGGREGATE_HEADER_BYTES = 64 as const;
export const XYG_WASM_AGGREGATE_OUTPUT_VERSION = 1 as const;
export const XYG_WASM_AGGREGATE_OUTPUT_MAGIC = "XYAO" as const;
export const XYG_WASM_AGGREGATE_OUTPUT_HEADER_BYTES = 32 as const;
export const XYG_WASM_AGGREGATE_FLAG_MEAN_COLOR = 1 as const;
export const XYG_WASM_AGGREGATE_CHECKPOINT_POINTS = 32768 as const;
export const XYG_WASM_AGGREGATE_MAX_REQUEST_BYTES = 67108864 as const;
export const XYG_WASM_AGGREGATE_TOTAL_MEMORY_BYTES = 67108864 as const;
export const XYG_WASM_AGGREGATE_REQUEST_STRIDE_COUNT = 16 as const;
export const XYG_WASM_AGGREGATE_REQUEST_STRIDE_COLOR = 20 as const;
export const XYG_WASM_AGGREGATE_ACCUMULATOR_STRIDE_COUNT = 4 as const;
export const XYG_WASM_AGGREGATE_ACCUMULATOR_STRIDE_COLOR = 40 as const;
export const XYG_WASM_AGGREGATE_OUTPUT_STRIDE_COUNT = 4 as const;
export const XYG_WASM_AGGREGATE_OUTPUT_STRIDE_COLOR = 8 as const;
export const XYG_WASM_AGGREGATE_CHECKPOINT_STRIDE_COUNT = 16 as const;
export const XYG_WASM_AGGREGATE_CHECKPOINT_STRIDE_COLOR = 20 as const;
export const XYG_WASM_AGGREGATE_REQUEST_COPY_FACTOR = 2 as const;
export const XYG_WASM_AGGREGATE_OUTPUT_COPY_FACTOR = 2 as const;
export const XYG_WASM_AGGREGATE_MAX_POINTS = 8000000 as const;
export const XYG_WASM_AGGREGATE_MAX_GRID_CELLS = 4194304 as const;
export const XYG_WASM_AGGREGATE_OFFSETS = {"version":4,"header_bytes":8,"flags":12,"point_count":16,"width":20,"height":24,"reserved":28,"x0":32,"x1":40,"y0":48,"y1":56} as const;
export const XYG_WASM_AGGREGATE_OUTPUT_OFFSETS = {"version":4,"header_bytes":8,"flags":12,"width":16,"height":20,"max_count":24,"reserved":28} as const;
export const XYG_WASM_STATUS = {
  OK: 0,
  INVALID_HANDLE: 1,
  INVALID_ARGUMENT: 2,
  RESOURCE_LIMIT: 3,
  SCENE_VERSION: 4,
  MALFORMED_SCENE: 5,
  CANCELLED: 6,
  STALE_SEQUENCE: 7,
  PENDING: 8,
  DISPOSED: 9,
  STALE_REVISION: 10,
  SELF_ECHO: 11,
} as const;

export interface XygWasmExports {
  memory: WebAssembly.Memory;
  xyg_wasm_abi_version(): number;
  xyg_wasm_scene_version(): number;
  xyg_wasm_max_arena_bytes(): number;
  xyg_wasm_instance_new(arg0: number): number;
  xyg_wasm_instance_dispose(arg0: number): number;
  xyg_wasm_temporal_execute(arg0: number, arg1: number, arg2: number): number;
  xyg_wasm_arena_resize(arg0: number, arg1: number): number;
  xyg_wasm_arena_ptr(arg0: number): number;
  xyg_wasm_arena_len(arg0: number): number;
  xyg_wasm_cancel(arg0: number, arg1: number): number;
  xyg_wasm_scene_validate(arg0: number, arg1: number, arg2: number, arg3: number): number;
  xyg_wasm_scene_prepare(arg0: number, arg1: number, arg2: number, arg3: number): number;
  xyg_wasm_scene_compile(arg0: number, arg1: number, arg2: number, arg3: number): number;
  xyg_wasm_scene_compile_prepare(arg0: number, arg1: number, arg2: number, arg3: number): number;
  xyg_wasm_aggregate_bin2d(arg0: number, arg1: number, arg2: number, arg3: number): number;
  xyg_wasm_aggregate_step(arg0: number, arg1: number, arg2: number): number;
  xyg_wasm_output_ptr(arg0: number): number;
  xyg_wasm_output_len(arg0: number): number;
  xyg_wasm_last_error_ptr(arg0: number): number;
  xyg_wasm_last_error_len(arg0: number): number;
  xyg_wasm_copy_count(arg0: number): number;
  xyg_wasm_copy_bytes_lo(arg0: number): number;
  xyg_wasm_copy_bytes_hi(arg0: number): number;
  xyg_wasm_arena_high_water(arg0: number): number;
  xyg_wasm_last_scene_records(arg0: number): number;
  xyg_wasm_last_scene_styles(arg0: number): number;
}

export function bindXygWasmExports(instance: WebAssembly.Instance): XygWasmExports {
  const raw = instance.exports as Record<string, unknown>;
  if (!(raw.memory instanceof WebAssembly.Memory)) {
    throw new Error("XYG WASM export memory is missing");
  }
  if (typeof raw.xyg_wasm_abi_version !== "function" || (raw.xyg_wasm_abi_version as Function).length !== 0) {
    throw new Error("XYG WASM export xyg_wasm_abi_version has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_scene_version !== "function" || (raw.xyg_wasm_scene_version as Function).length !== 0) {
    throw new Error("XYG WASM export xyg_wasm_scene_version has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_max_arena_bytes !== "function" || (raw.xyg_wasm_max_arena_bytes as Function).length !== 0) {
    throw new Error("XYG WASM export xyg_wasm_max_arena_bytes has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_instance_new !== "function" || (raw.xyg_wasm_instance_new as Function).length !== 1) {
    throw new Error("XYG WASM export xyg_wasm_instance_new has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_instance_dispose !== "function" || (raw.xyg_wasm_instance_dispose as Function).length !== 1) {
    throw new Error("XYG WASM export xyg_wasm_instance_dispose has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_temporal_execute !== "function" || (raw.xyg_wasm_temporal_execute as Function).length !== 3) {
    throw new Error("XYG WASM export xyg_wasm_temporal_execute has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_arena_resize !== "function" || (raw.xyg_wasm_arena_resize as Function).length !== 2) {
    throw new Error("XYG WASM export xyg_wasm_arena_resize has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_arena_ptr !== "function" || (raw.xyg_wasm_arena_ptr as Function).length !== 1) {
    throw new Error("XYG WASM export xyg_wasm_arena_ptr has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_arena_len !== "function" || (raw.xyg_wasm_arena_len as Function).length !== 1) {
    throw new Error("XYG WASM export xyg_wasm_arena_len has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_cancel !== "function" || (raw.xyg_wasm_cancel as Function).length !== 2) {
    throw new Error("XYG WASM export xyg_wasm_cancel has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_scene_validate !== "function" || (raw.xyg_wasm_scene_validate as Function).length !== 4) {
    throw new Error("XYG WASM export xyg_wasm_scene_validate has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_scene_prepare !== "function" || (raw.xyg_wasm_scene_prepare as Function).length !== 4) {
    throw new Error("XYG WASM export xyg_wasm_scene_prepare has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_scene_compile !== "function" || (raw.xyg_wasm_scene_compile as Function).length !== 4) {
    throw new Error("XYG WASM export xyg_wasm_scene_compile has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_scene_compile_prepare !== "function" || (raw.xyg_wasm_scene_compile_prepare as Function).length !== 4) {
    throw new Error("XYG WASM export xyg_wasm_scene_compile_prepare has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_aggregate_bin2d !== "function" || (raw.xyg_wasm_aggregate_bin2d as Function).length !== 4) {
    throw new Error("XYG WASM export xyg_wasm_aggregate_bin2d has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_aggregate_step !== "function" || (raw.xyg_wasm_aggregate_step as Function).length !== 3) {
    throw new Error("XYG WASM export xyg_wasm_aggregate_step has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_output_ptr !== "function" || (raw.xyg_wasm_output_ptr as Function).length !== 1) {
    throw new Error("XYG WASM export xyg_wasm_output_ptr has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_output_len !== "function" || (raw.xyg_wasm_output_len as Function).length !== 1) {
    throw new Error("XYG WASM export xyg_wasm_output_len has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_last_error_ptr !== "function" || (raw.xyg_wasm_last_error_ptr as Function).length !== 1) {
    throw new Error("XYG WASM export xyg_wasm_last_error_ptr has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_last_error_len !== "function" || (raw.xyg_wasm_last_error_len as Function).length !== 1) {
    throw new Error("XYG WASM export xyg_wasm_last_error_len has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_copy_count !== "function" || (raw.xyg_wasm_copy_count as Function).length !== 1) {
    throw new Error("XYG WASM export xyg_wasm_copy_count has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_copy_bytes_lo !== "function" || (raw.xyg_wasm_copy_bytes_lo as Function).length !== 1) {
    throw new Error("XYG WASM export xyg_wasm_copy_bytes_lo has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_copy_bytes_hi !== "function" || (raw.xyg_wasm_copy_bytes_hi as Function).length !== 1) {
    throw new Error("XYG WASM export xyg_wasm_copy_bytes_hi has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_arena_high_water !== "function" || (raw.xyg_wasm_arena_high_water as Function).length !== 1) {
    throw new Error("XYG WASM export xyg_wasm_arena_high_water has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_last_scene_records !== "function" || (raw.xyg_wasm_last_scene_records as Function).length !== 1) {
    throw new Error("XYG WASM export xyg_wasm_last_scene_records has an incompatible signature");
  }
  if (typeof raw.xyg_wasm_last_scene_styles !== "function" || (raw.xyg_wasm_last_scene_styles as Function).length !== 1) {
    throw new Error("XYG WASM export xyg_wasm_last_scene_styles has an incompatible signature");
  }
  const bound = raw as unknown as XygWasmExports;
  if (bound.xyg_wasm_abi_version() !== XYG_WASM_ABI_VERSION) {
    throw new Error("XYG WASM ABI version is incompatible");
  }
  if (bound.xyg_wasm_scene_version() !== XYG_WASM_SCENE_VERSION) {
    throw new Error("XYG canonical scene version is incompatible");
  }
  return bound;
}

export function readXygWasmError(exports: XygWasmExports, handle: number): string {
  const ptr = exports.xyg_wasm_last_error_ptr(handle) >>> 0;
  const len = exports.xyg_wasm_last_error_len(handle) >>> 0;
  if (!ptr || !len) return "XYG WASM operation failed";
  const end = ptr + len;
  if (!Number.isSafeInteger(end) || end > exports.memory.buffer.byteLength) {
    return "XYG WASM returned an invalid error range";
  }
  return new TextDecoder().decode(new Uint8Array(exports.memory.buffer, ptr, len));
}
