import {createXygWasmWorker,createMapLibreGeoLayer} from '/packages/xy-client/dist/index.js';
import {buildMixedFixture,check,MIXED_BUDGET} from '/tests/browser/geo_mixed_fixture.mjs';
const canvas=document.createElement('canvas'),container=document.createElement('div');canvas.width=canvas.height=64;canvas.style.cssText='width:64px;height:64px';container.style.cssText='position:relative;width:64px;height:64px';container.appendChild(canvas);document.body.appendChild(container);
const gl=canvas.getContext('webgl2',{preserveDrawingBuffer:true,antialias:false});check(gl,'real WebGL2 unavailable');
const live=new Set();for(const [create,remove] of [['createBuffer','deleteBuffer'],['createVertexArray','deleteVertexArray'],['createTexture','deleteTexture'],['createFramebuffer','deleteFramebuffer']]){const make=gl[create].bind(gl),drop=gl[remove].bind(gl);gl[create]=(...args)=>{const value=make(...args);if(value)live.add(value);return value;};gl[remove]=value=>{live.delete(value);return drop(value);};}
const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,64,64,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);
const framebuffer=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,framebuffer);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,texture,0);check(gl.checkFramebufferStatus(gl.FRAMEBUFFER)===gl.FRAMEBUFFER_COMPLETE,'foreign framebuffer');gl.viewport(0,0,64,64);gl.clearColor(0.25,0.25,0.25,1);gl.clear(gl.COLOR_BUFFER_BIT);
const initiallyBound=gl.getParameter(gl.DRAW_FRAMEBUFFER_BINDING)===framebuffer,events=[];canvas.addEventListener('webglcontextlost',event=>{events.push('lost');event.preventDefault();});canvas.addEventListener('webglcontextrestored',()=>events.push('restored'));
const pixel=(x,y)=>{const b=new Uint8Array(4);gl.readPixels(x,y,1,1,gl.RGBA,gl.UNSIGNED_BYTE,b);return [...b];};
let failScheduling=false,schedules=0;const shell={getCanvas:()=>canvas,getContainer:()=>container,triggerRepaint:()=>{schedules++;if(failScheduling)throw Error('injected mixed staging callback failure');}};
const layer=createMapLibreGeoLayer({id:'actual-mixed'});layer.onAdd(shell,gl);
const worker=createXygWasmWorker({wasm:'/packages/xy-client/dist/xyg-wasm.wasm',workerUrl:'/packages/xy-client/dist/wasm-worker.js',maxArenaBytes:MIXED_BUDGET});
let fixture,paint,failedPaint,freeze;
try{
 window.__mixedStage='worker-ready';await worker.ready;window.__mixedStage='fixture';const bridges={source:{execute:r=>worker.geoScaleExecute(r),read:r=>worker.geoScaleRead(r)},tile:{execute:r=>worker.geoTileExecute(r),read:r=>worker.geoTileRead(r)},snapshot:{execute:r=>worker.geoSnapshotExecute(r),read:r=>worker.geoSnapshotRead(r)},async stage(frame){check(!gl.isContextLost(),'initial foreign context lost before product staging');const before=gl.getParameter(gl.DRAW_FRAMEBUFFER_BINDING)===framebuffer;paint=await worker.prepareGeoFrame(frame.handle,frame.nonce,true).result;layer.setPrepared(paint);check(gl.getParameter(gl.DRAW_FRAMEBUFFER_BINDING)===framebuffer,JSON.stringify({message:'stage changed foreign framebuffer',before,initiallyBound,events,lost:gl.isContextLost(),size:[canvas.width,canvas.height],binding:gl.getParameter(gl.DRAW_FRAMEBUFFER_BINDING)}));},async stageFailure(frame){
  layer.render(gl,{});check(pixel(32,32).join(',')==='255,0,0,255','retained point was not painted');const baseline=live.size,previous=pixel(2,2).join(',');failedPaint=await worker.prepareGeoFrame(frame.handle,frame.nonce,true).result;failScheduling=true;let rejected=false;try{layer.setPrepared(failedPaint);}catch(error){rejected=/injected/.test(error.message);}finally{failScheduling=false;failedPaint=undefined;}
  check(rejected&&live.size===baseline,'failed staging leaked or replaced GL resources');layer.render(gl,{});check(pixel(2,2).join(',')===previous&&layer.pick(32,32)===0xffffffffffffffffn,'old mixed painter did not survive staging failure');check(gl.getParameter(gl.DRAW_FRAMEBUFFER_BINDING)===framebuffer,'failure changed foreign framebuffer');
 }};
 fixture=await buildMixedFixture(bridges);window.__mixedStage='painted';layer.render(gl,{});
 check(pixel(32,32).join(',')==='255,0,0,255','analysis exact red pixel');check(pixel(2,2).join(',')==='0,0,255,255','raster exact blue pixel');check(layer.pick(32,32)===0xffffffffffffffffn,'full mixed literal ID pick');check(container.textContent.includes('Tiles'),'Rust footer DOM missing');check(canvas.width===64&&canvas.height===64&&!gl.isContextLost(),'foreign canvas resized/lost');
 freeze=await fixture.freeze();check(String.fromCharCode(...new Uint8Array(freeze.bytes,0,4))==='XYGX','whole frozen envelope');check(new TextDecoder().decode(freeze.bytes).includes('Tiles'),'frozen attribution absent');await freeze.dispose();freeze=undefined;
 // Consumer storage goes first; only then can the Data credit be released.
 layer.releasePrepared();paint=undefined;fixture.scene=undefined;fixture.descriptorBytes=undefined;await fixture.frame.dispose();fixture=undefined;
 for(const rasterColor of [[0,0,0,255],[255,255,255,255]]){
  fixture=await buildMixedFixture({...bridges,rasterColor});layer.render(gl,{});check(pixel(2,2).join(',')===rasterColor.join(','),'contrast raster mismatch');check(container.textContent.includes('Tiles'),'contrast literal footer missing');
  // The test app presents its foreign framebuffer; XYG never changes its target.
  gl.bindFramebuffer(gl.READ_FRAMEBUFFER,framebuffer);gl.bindFramebuffer(gl.DRAW_FRAMEBUFFER,null);gl.blitFramebuffer(0,0,64,64,0,0,64,64,gl.COLOR_BUFFER_BIT,gl.NEAREST);gl.bindFramebuffer(gl.FRAMEBUFFER,framebuffer);
  const box=container.querySelector('[data-xy-slot="graph_label_box"]');check(box&&box.style.backgroundColor==='rgb(255, 255, 255)','Rust opaque footer box missing');
  window.__mixedContrast={waiting:true,color:rasterColor,bounds:container.getBoundingClientRect().toJSON(),box:{x:parseFloat(box.style.left),y:parseFloat(box.style.top),width:parseFloat(box.style.width),height:parseFloat(box.style.height)}};await new Promise(resolve=>{window.__mixedContrastAck=resolve;});window.__mixedContrast.waiting=false;
  layer.releasePrepared();paint=undefined;fixture.scene=fixture.descriptorBytes=undefined;await fixture.frame.dispose();fixture=undefined;
 }
 layer.dispose();check(live.size===2,'mixed consumer GL resources were not released');check(gl.getParameter(gl.DRAW_FRAMEBUFFER_BINDING)===framebuffer&&!gl.isContextLost(),'disposal damaged foreign GL');gl.deleteFramebuffer(framebuffer);gl.deleteTexture(texture);check(live.size===0,'foreign test resources');
 const abi=worker.abiVersion??33;await worker.dispose();window.__mixed={ok:true,abiVersion:abi,schedules,exactPixels:true,wholeFrozen:true,callbackFailureOldPaint:true,literalFooter:true,externalFramebuffer:true,remainingGlObjects:live.size};
}catch(error){window.__mixed={ok:false,error:error.stack??String(error)};}
finally{if(freeze)await freeze.dispose();layer.releasePrepared();paint=failedPaint=undefined;if(fixture){fixture.scene=fixture.descriptorBytes=undefined;await fixture.frame.dispose();}layer.dispose();await worker.dispose();}
