// Test-only genuine Worker MemberData cleanup; no public testing exports.
import {createXygWasmWorker,withGeoWorkerMemberDataOutcome,withGeoWorkerMutationOutcome,beginGeoWorkerMutationCapture} from '../../js/src/47_wasm';
import {encodeGeoScaleRequest as encode,decodeGeoScaleReply as decode,encodeGeoChunkRequest,encodeGeoScaleStyle,driveGeoSession,prepareGeoSceneData} from '../../js/src/63_geo_source';
import {GeoOverviewIndex} from '../../js/src/71_geo_overview_owner';
import {encodeOverviewMembersRequest as request,decodeOverviewMembersReply as reply} from '../../js/src/73_geo_overview_members';
const U64=0xffffffffffffffffn,I64=-0x8000000000000000n,budget={processorBytes:128<<20,maxRowsExamined:1000000n,maxReadBytes:128n<<20n,maxChunks:65536,pageRows:1};
const assert={equal(a,b){if(a!==b)throw Error(`expected ${String(b)}, got ${String(a)}`);},ok(a){if(!a)throw Error('assertion failed');}};
const check=(p,s)=>{if(!p)throw Error(s);};
async function rejects(p){try{await p;}catch(e){return e;}throw Error('expected rejection');}
const requests=new Map(),faults=new WeakMap(),NativeWorker=globalThis.Worker;
globalThis.Worker=class extends NativeWorker{constructor(...args){super(...args);const send=this.postMessage.bind(this);this.postMessage=(message,transfer)=>{if(message.type==='geo.scale.execute'||message.type==='geo.scale.read'){requests.set(`${this.id}:${message.requestId}`,message.request.slice(0));const fault=faults.get(this),v=new DataView(message.request);if(fault&&v.getUint32(8,true)===10&&v.getBigUint64(16,true)===fault.handle){faults.delete(this);throw Error('MemberData10 rejected before Rust');}}send(message,transfer);};this.id=++globalThis.__memberWorkerIds;}};
globalThis.__memberWorkerIds=0;
async function setup(worker){const holder={bridge:worker.geoScaleBridge(),dispose(){}},actual=holder.bridge.execute,control={execute:actual,read:holder.bridge.read,reader:async()=>chunk},bridge=holder.bridge;const descriptor=new Uint8Array(216),v=new DataView(descriptor.buffer);descriptor.set([88,89,71,68]);[1,4,4326,1,0].forEach((n,i)=>v.setUint32(4+i*4,n,true));[5n,5n,6n,0n,0n].forEach((n,i)=>v.setBigUint64(24+i*8,n,true));[0,0,0,0,-90,0,90,0,0,0].forEach((n,i)=>v.setFloat64(64+i*8,n,true));descriptor.set([1,1,1,0,1],144);[U64,9007199254740993n,7n,7n,U64].forEach((n,i)=>v.setBigUint64(152+i*8,n,true));[0,2,3,4,4,5].forEach((n,i)=>v.setUint32(192+i*4,n,true));const chunk=await bridge.read(encodeGeoChunkRequest({descriptor,rows:5,intervals:{starts:BigInt64Array.of(I64,0n,10n,0n,I64),ends:BigInt64Array.of(0n,10n,0n,0n,0n),startValidity:Uint8Array.of(0,1,1,0,0),endValidity:Uint8Array.of(1,1,0,0,1)}},budget.processorBytes));
const builder=decode(await bridge.execute(encode({command:1}))).handle;for(let i=0;i<2;i++)await bridge.execute(encode({command:2,handle:builder,payload:new Uint8Array(chunk)}));await bridge.execute(encode({command:3,handle:builder,generation:U64}));const manifest=await bridge.read(encode({command:21,handle:builder})),source=decode(await bridge.execute(encode({command:4,budget,payload:new Uint8Array(manifest)}))).handle;await bridge.execute(encode({command:10,handle:builder}));const readChunk=(t,s)=>control.reader(t,s),info=(await driveGeoSession(bridge,{handle:source,sequence:0n,budget,readChunk})).source;const q={camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:0,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:32768,previousDirect:true,sourceDigest:info.digest,generation:U64,layerId:U64,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:0},maxProjectedVertices:1000n};await bridge.execute(encode({command:5,handle:source,sequence:1n,budget,query:q}));await driveGeoSession(bridge,{handle:source,sequence:1n,budget,readChunk});const seed=await prepareGeoSceneData(bridge,{handle:source,sequence:1n,budget,style:encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0})});const pages=new Map(),index=await GeoOverviewIndex.fromFrame(seed,{bridge,budget,maxVertices:1000n,readChunk,readPage:async t=>pages.get(`${t.namespace}:${t.page}`),writePage:async(t,b)=>pages.set(`${t.namespace}:${t.page}`,b.slice())});q.maxCells=0;q.previousDirect=false;q.maxProjectedVertices=0n;
return {holder,bridge,actual,actualRead:holder.bridge.read,control,chunk,index,source,seed,q,async close(){control.execute=actual;await index.dispose();await seed.dispose();await bridge.execute(encode({command:10,handle:source}));holder.dispose();}};}
export async function verifyMemberRetirement(){
 const options={wasm:'/packages/xy-client/dist/xyg-wasm.wasm',workerUrl:'/packages/xy-client/dist/wasm-worker.js',maxArenaBytes:128<<20},worker=createXygWasmWorker(options),foreign=createXygWasmWorker(options);await Promise.all([worker.ready,foreign.ready]);
 let f,g,frame,otherFrame,page,otherPage,continuation;
 try{
 f=await setup(worker);g=await setup(foreign);frame=await f.index.update(f.q,{sequence:2n});otherFrame=await g.index.update(g.q,{sequence:2n});
 page=await frame.members(136,{sequence:10n,maxVertices:1000n});otherPage=await otherFrame.members(136,{sequence:10n,maxVertices:1000n});check(page.handle===otherPage.handle,'fresh Worker MemberData handles did not collide');
 Object.defineProperty(frame,'bridge',{value:g.bridge});Object.defineProperty(f.index,'bridge',{value:g.bridge});
 const handle=page.handle,seq=page.sequence,probe=request(6,handle,seq),native=worker.worker,receive=native.onmessage;
 const reads=()=>[...requests].filter(([k,b])=>k.startsWith(`${native.id}:`)&&new DataView(b).getUint32(8,true)===23&&new DataView(b).getBigUint64(16,true)===handle).length,initialReads=reads();
 // Original knownData live receipt: no Data23 read or generic operation6 authority.
 await withGeoWorkerMemberDataOutcome(f.bridge,probe,async outcome=>{await withGeoWorkerMutationOutcome(f.bridge,probe,async generic=>{const packet=await f.actual(probe.slice(0));check(outcome(packet)?.reply===packet,'genuine liveData probe missing');check(!generic(packet),'generic6 scope received MemberData authority');assert.equal(reply(packet).sourceHandle,handle);});});
 const wrong=request(6,handle,seq+1n);let wrongError;await withGeoWorkerMemberDataOutcome(f.bridge,wrong,async outcome=>{try{await f.actual(wrong.slice(0));}catch(error){wrongError=error;check(outcome(error)?.code==='XYG_GEO_SOURCE_STALE','wrongseq real rejection missing');}});check(wrongError,'live wrongseq probe did not reject');
 await withGeoWorkerMemberDataOutcome(f.bridge,probe,async outcome=>{const packet=await g.actual(probe.slice(0));check(!outcome(packet),'colliding foreign Data probe branded');});
 // Lost successful10 remains guarded until a genuine current absence proof.
 let lose=true;native.onmessage=event=>{const q=requests.get(`${native.id}:${event.data?.requestId}`);if(q&&new DataView(q).getUint32(8,true)===10&&new DataView(q).getBigUint64(16,true)===handle&&lose&&event.data.ok){lose=false;receive.call(native,{data:{requestId:event.data.requestId,ok:false,error:{code:'LOST_MEMBER10',message:'actual successful10 confirmation lost'}}});return;}receive.call(native,event);};
 await rejects(page.dispose());check(!lose,'actual MemberData10 not exercised');
 // Saved genuine wrongseq error cannot retire original privateData during retry.
 native.onmessage=event=>{const q=requests.get(`${native.id}:${event.data?.requestId}`);if(q&&new DataView(q).getUint32(8,true)===6&&new DataView(q).getBigUint64(16,true)===handle){const p=worker.pending.get(event.data.requestId);worker.pending.delete(event.data.requestId);p.reject(wrongError);return;}receive.call(native,event);};await rejects(page.dispose());
 native.onmessage=receive;const pressure=Array.from({length:16},()=>beginGeoWorkerMutationCapture(f.bridge,probe));await rejects(page.dispose());pressure.forEach(c=>c.close());await page.dispose();page=undefined;check(reads()===initialReads,'cleanup consumed Data23 quota');
 const live=await frame.members(136,{sequence:11n,maxVertices:1000n});faults.set(native,{handle:live.handle});await rejects(live.dispose());native.onmessage=event=>{const q=requests.get(`${native.id}:${event.data?.requestId}`);if(q&&new DataView(q).getUint32(8,true)===6&&new DataView(q).getBigUint64(16,true)===live.handle){const p=worker.pending.get(event.data.requestId);worker.pending.delete(event.data.requestId);p.reject(wrongError);return;}receive.call(native,event);};await rejects(live.dispose());native.onmessage=receive;const stillLive=reply(await f.actual(request(6,live.handle,live.sequence)));check(stillLive.code===0&&stillLive.sourceHandle===live.handle,'saved wrongseq error retired liveData');await live.dispose();
 // Whole reader callback and ticket ACK settle before attempted Query10.
 let lost45=true;native.onmessage=event=>{const q=requests.get(`${native.id}:${event.data?.requestId}`);if(q&&new DataView(q).getUint32(8,true)===45&&lost45&&event.data.ok){lost45=false;receive.call(native,{data:{requestId:event.data.requestId,ok:false,error:{code:'LOST_MEMBER45',message:'actual45 confirmation lost'}}});return;}receive.call(native,event);};const birthError=await rejects(frame.members(136,{sequence:12n,maxVertices:1000n})),guard=birthError.owner;check(guard,'missing exact45 recovery owner');native.onmessage=receive;
 let enter,release;const entered=new Promise(r=>enter=r),gate=new Promise(r=>release=r);f.control.reader=async()=>{enter();await gate;return f.chunk;};const recovering=guard.recover();const recoveredResult=Promise.allSettled([recovering]);await entered;let closed=false;const closing=guard.dispose().then(()=>closed=true);await new Promise(r=>setTimeout(r,10));check(!closed,'cleanup overtook reader callback');const queryHandle=guard.handle,before10=[...requests].filter(([key,b])=>key.startsWith(`${native.id}:`)&&new DataView(b).getUint32(8,true)===10&&new DataView(b).getBigUint64(16,true)===queryHandle).length;check(before10===0,'Query10 preceded callback ACK');release();await recoveredResult;await closing;check(closed&&guard.closed,'loan cancellation did not settle');f.control.reader=async()=>f.chunk;
 // Known genuine missingData SourceStale is current-call only, not error strings.
 await withGeoWorkerMemberDataOutcome(f.bridge,probe,async outcome=>{try{await f.actual(probe.slice(0));}catch(error){check(outcome(error)?.status===7&&outcome(error)?.code==='XYG_GEO_SOURCE_STALE','genuine missingData proof absent');const fake=Object.assign(Error('XYG_GEO_SOURCE_STALE'),{code:'XYG_GEO_SOURCE_STALE',status:7});check(!outcome(fake),'forged Stale attributes branded');check(!outcome(wrongError),'earlier wrongseq error branded');}});
 // An older genuine rejection after a matching cloned live dispatch is unknown.
 const liveProbe=request(6,otherPage.handle,otherPage.sequence),wrongOther=request(6,otherPage.handle,otherPage.sequence+1n);
 let earlier;await withGeoWorkerMemberDataOutcome(g.bridge,wrongOther,async outcome=>{try{await g.actual(wrongOther.slice(0));}catch(error){earlier=error;check(outcome(error),'genuine earlier wrongseq missing');}});
 await withGeoWorkerMemberDataOutcome(g.bridge,liveProbe,async outcome=>{const first=await g.actual(liveProbe.slice(0));const second=await g.actual(liveProbe.slice(0));check(outcome(second)?.reply===second&&!outcome(first)&&!outcome(earlier),'latest cloned dispatch did not fence old authority');let scalar;check(outcome(second),'live scalar authentication missing');scalar=reply(second).handle;queueMicrotask(()=>new DataView(second).setBigUint64(16,999n,true));await Promise.resolve();check(scalar===otherPage.handle,'microtask retagged captured handle');});
 // Dispose all original producers; private Page continuation retains source reader.
 await frame.dispose();frame=undefined;await f.index.dispose();await f.seed.dispose();await f.bridge.execute(encode({command:10,handle:f.source}));
 await otherFrame.dispose();otherFrame=undefined;await g.index.dispose();await g.seed.dispose();await g.bridge.execute(encode({command:10,handle:g.source}));
 continuation=await otherPage.nextPage({sequence:11n,maxVertices:1000n});check(continuation.record(0).sourceRow===4n,'private continuation changed physical row');await continuation.dispose();continuation=undefined;
 for(const bad of [request(6,0n,seq),request(6,handle,0n),request(6,handle,seq,budget)]){let failed=false;try{await withGeoWorkerMemberDataOutcome(f.bridge,bad,async()=>{});}catch{failed=true;}check(failed,'nonminimal probe admitted');}
 const captures=Array.from({length:16},()=>beginGeoWorkerMutationCapture(f.bridge,probe));await rejects(withGeoWorkerMemberDataOutcome(f.bridge,probe,async()=>{}));captures.forEach(c=>c.close());
 return {lostSuccessful10Recovered:true,preRustFailureLiveProbeRetry:true,originalPrivatePublicationSequence:true,publicBridgeDecorationCannotRetag:true,generic6Unbranded:true,foreignCollidingDataRejected:true,olderWrongSequenceErrorRejected:true,forgedStaleAttributesRejected:true,clonedLatestDispatch:true,synchronousScalarBeforeMicrotask:true,physicalContinuation:true,nonminimalRejected:true,sharedCapacity16:true,pressureRetainsCleanupGuard:true,wholeCallbackAckBefore10:true,noExtraDataRead:true};
 }finally{if(continuation)await continuation.dispose();if(page)await page.dispose();if(otherPage)await otherPage.dispose();if(frame)await frame.dispose();if(otherFrame)await otherFrame.dispose();if(f){try{await f.close();}catch{}}if(g){try{await g.close();}catch{}}worker.dispose();foreign.dispose();globalThis.Worker=NativeWorker;}
}
