import {createXygWasmWorker,createGeoSelectedScope,claimGeoSelectedState,encodeGeoScaleRequest as encode,decodeGeoScaleReply as decode,encodeGeoChunkRequest,encodeGeoScaleStyle,driveGeoSession,driveGeoIndexSession,prepareGeoSceneData,beginGeoWorkerMutationCapture} from '/selected-capture-proof.js';
import {hydrateWasmPainter} from '/packages/xy-client/dist/index.js';
const budget={processorBytes:128<<20,maxRowsExamined:1000000n,maxReadBytes:128n<<20n,maxChunks:65536,pageRows:4096},MAX=0xffffffffffffffffn;
const check=(value,message)=>{if(!value)throw Error(message);},reject=async(p,message)=>{let failed=false;try{await p;}catch{failed=true;}check(failed,message);};
const nextFrame=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))),workers=[],contexts=[],requests=[],scopes=[];
const nativePost=Worker.prototype.postMessage;
Worker.prototype.postMessage=function(message,transfer){if(message.type==='geo.scale.execute'){const v=new DataView(message.request);requests.push({worker:this,id:message.requestId,command:v.getUint32(8,true),handle:v.getBigUint64(16,true),sequence:v.getBigUint64(24,true),request:message.request.slice(0)});}return nativePost.call(this,message,transfer);};
function worker(){const w=createXygWasmWorker({workerUrl:'/packages/xy-client/dist/wasm-worker.js',wasm:'/packages/xy-client/dist/xyg-wasm.wasm',maxArenaBytes:budget.processorBytes});workers.push(w);return w;}
async function fixture(w){
 await w.ready;const bridge=w.geoScaleBridge(),descriptor=new Uint8Array(120),v=new DataView(descriptor.buffer);descriptor.set([88,89,71,68]);[1,1,4326,1,0].forEach((n,i)=>v.setUint32(4+4*i,n,true));v.setBigUint64(24,2n,true);v.setBigUint64(32,2n,true);[0,0,90,1].forEach((n,i)=>v.setFloat64(64+8*i,n,true));descriptor.set([1,1],96);v.setBigUint64(104,MAX,true);v.setBigUint64(112,9007199254740993n,true);
 const chunk=await bridge.read(encodeGeoChunkRequest({descriptor,rows:2,intervals:{starts:BigInt64Array.of(-(1n<<63n),-(1n<<63n)),ends:BigInt64Array.of((1n<<63n)-1n,(1n<<63n)-1n),startValidity:Uint8Array.of(1,1),endValidity:Uint8Array.of(1,1)}},budget.processorBytes));
 const builder=decode(await bridge.execute(encode({command:1}))).handle;let source,seed,index;
 try{await bridge.execute(encode({command:2,handle:builder,payload:new Uint8Array(chunk)}));await bridge.execute(encode({command:3,handle:builder,generation:MAX}));const manifest=await bridge.read(encode({command:21,handle:builder}));source=decode(await bridge.execute(encode({command:4,payload:new Uint8Array(manifest),budget}))).handle;
  const readChunk=async()=>chunk.slice(0),info=(await driveGeoSession(bridge,{handle:source,sequence:0n,budget,readChunk})).source;
  const query={camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:0,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:32768,previousDirect:true,sourceDigest:info.digest.slice(),generation:MAX,layerId:MAX,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:1,instant:-(1n<<63n)},maxProjectedVertices:1000000n};
  await bridge.execute(encode({command:5,handle:source,sequence:1n,query,budget}));await driveGeoSession(bridge,{handle:source,sequence:1n,budget,readChunk});const style=encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0});seed=await prepareGeoSceneData(bridge,{handle:source,sequence:1n,budget,style});
  const p=new Uint8Array(16),pv=new DataView(p.buffer);pv.setUint32(0,16,true);pv.setBigUint64(8,1000000n,true);index=decode(await bridge.execute(encode({command:17,handle:seed.handle,sequence:1n,budget,payload:p}))).handle;const pages=new Map(),readPage=async t=>pages.get(t.page).slice(),writePage=async(t,b)=>{check(pages.size<32,'external page cache bound');pages.set(t.page,b.slice());};await driveGeoIndexSession(bridge,{handle:index,sequence:1n,budget,readChunk,readPage,writePage});
  const context={w,bridge,source,seed,index,query,style,readChunk,readPage,pages};contexts.push(context);return context;
 }catch(error){if(seed)await seed.dispose();if(index)await bridge.execute(encode({command:10,handle:index}));if(source)await bridge.execute(encode({command:10,handle:source}));throw error;}finally{await bridge.execute(encode({command:10,handle:builder}));}
}
async function state(x){const scope=await createGeoSelectedScope(x.bridge,{frameHandle:x.seed.handle,sequence:1n,namespace:MAX,layerId:MAX,budget});scopes.push(scope);const s=await scope.state({revision:2n,ids:BigUint64Array.of(MAX),fill:Uint8Array.of(0,255,0,255),budget});return {scope,s};}
function fault(w,command,transform){const native=w.worker,receive=native.onmessage;let armed=true;native.onmessage=event=>{const request=requests.find(r=>r.worker===native&&r.id===event.data?.requestId);if(armed&&request?.command===command&&event.data?.ok){armed=false;transform(event,request,receive,native);return;}receive.call(native,event);};return ()=>{native.onmessage=receive;check(!armed,'fault never reached actual Worker');};}
const holder=document.createElement('div');document.body.append(holder);let view,paint;
try{
 window.__selectedStage='seed';const w=worker(),x=await fixture(w),foreign=worker(),y=await fixture(foreign);check(x.source===y.source&&x.seed.handle===y.seed.handle,'fixture omitted colliding Worker handles');
 paint=await w.prepareGeoFrame(x.seed.handle,1n).result;view=hydrateWasmPainter(holder,paint);view.draw();await nextFrame();const ids=view.gpuTraces.flatMap((t,i)=>Array.from({length:t._sceneIds.lo.length},(_,row)=>view.sceneStableId(i,row)));check(ids.includes(MAX),'old literal u64 paint missing');
 const pixel=()=>{const c=document.createElement('canvas');c.width=800;c.height=600;const g=c.getContext('2d');g.fillStyle='white';g.fillRect(0,0,800,600);g.drawImage(view.canvas,0,0);return [...g.getImageData(400,300,1,1).data];},before=pixel();check(before.join(',')==='255,0,0,255','old paint oracle '+before);
 window.__selectedStage='admission';let {scope,s}=await state(x);let admissionError;try{await s.begin({command:35,handle:x.source,sequence:2n,query:{...x.query,stateRevision:2n},budget:{...budget,processorBytes:4096}});}catch(error){admissionError={code:error.code,status:error.status};}check(admissionError,'low-budget35 unexpectedly accepted');window.__admissionError=admissionError;s.check();await reject(s.begin({command:35,handle:x.source,sequence:1n,query:{...x.query,stateRevision:2n},budget}),'stale35 unexpectedly accepted');s.check();await reject(s.begin({command:35,handle:x.source,sequence:2n,query:{...x.query,layerId:1n,stateRevision:2n},budget}),'invalid-binding35 unexpectedly accepted');s.check();window.__selectedStage='lost35';window.__selectedStage='lost35.dispatch';const restore=fault(w,35,(event,r,receive,native)=>{receive.call(native,{data:{...event.data,ok:false,error:{code:'XYG_WASM_RESOURCE_LIMIT',message:'synthetic after actual35',status:3}}});});await reject(s.begin({command:35,handle:x.source,sequence:2n,query:{...x.query,stateRevision:2n},budget}),'lost35 cleared ownership');restore();check(s.pendingOperation,'lost35 omitted attempt');window.__selectedStage='lost35.recover';let accepted=await s.pendingOperation.recover();check(!accepted.fallback&&accepted.operation.handle===x.source,'lost35 replay retagged Source');window.__selectedStage='lost35.cancel';await accepted.operation.cancel();window.__selectedStage='lost35.dispose';await s.pendingOperation.dispose();window.__selectedStage='lost35.scope-close';check(!requests.some(r=>r.worker===w.worker&&r.command===10&&r.handle===x.source),'mutation cleanup disposed caller Source');await x.bridge.execute(encode({command:10,handle:x.source}));x.sourceDisposed=true;await scope.dispose();view.draw();await nextFrame();check(pixel().join(',')===before.join(','),'failed35 changed accepted paint');
 window.__selectedStage='foreign';({scope,s}=await state(x));const foreignBridge=foreign.geoScaleBridge();await reject(Promise.resolve().then(()=>claimGeoSelectedState(s,foreignBridge)),'foreign producer accepted State');await s.dispose();await scope.dispose();
 window.__selectedStage='fallback';({scope,s}=await state(x));accepted=await s.begin({command:36,handle:x.index,sequence:2n,query:{...x.query,stateRevision:2n},budget:{...budget,maxChunks:1}});check(accepted.fallback&&accepted.reason===2,'genuine fallback missing');s.check();accepted=await s.begin({command:36,handle:x.index,sequence:2n,query:{...x.query,stateRevision:2n},budget});await accepted.operation.cancel();await accepted.operation.dispose();await s.pendingOperation.dispose();
 window.__selectedStage='forged immediate fallback';s=await scope.state({revision:2n,ids:BigUint64Array.of(MAX),fill:Uint8Array.of(0,255,0,255),budget});const immediate=fault(w,36,(event,r,receive,native)=>{const v=new DataView(event.data.value);v.setUint32(8,10,true);v.setBigUint64(16,x.index,true);v.setUint32(48,2,true);receive.call(native,event);});await reject(s.begin({command:36,handle:x.index,sequence:3n,query:{...x.query,stateRevision:2n},budget}),'immediate forged fallback accepted');immediate();await reject(Promise.resolve().then(()=>s.check()),'corrupt reply released State');accepted=await s.pendingOperation.recover();check(!accepted.fallback,'forged fallback replay failed');await accepted.operation.cancel();await accepted.operation.dispose();await s.pendingOperation.dispose();
 for(let hops=1;hops<=12;hops++){
  window.__selectedStage='microtask'+hops;s=await scope.state({revision:2n,ids:BigUint64Array.of(MAX),fill:Uint8Array.of(0,255,0,255),budget});let changed=false;const undo=fault(w,36,(event,r,receive,native)=>{const packet=event.data.value;receive.call(native,event);const mutate=n=>queueMicrotask(()=>{if(n>1)mutate(n-1);else{const v=new DataView(packet);v.setUint32(8,10,true);v.setBigUint64(16,x.index,true);v.setUint32(48,2,true);changed=true;}});mutate(hops);});
  try{accepted=await s.begin({command:36,handle:x.index,sequence:BigInt(3+hops),query:{...x.query,stateRevision:2n},budget});}catch{accepted=await s.pendingOperation.recover();}undo();check(changed&&accepted&&!accepted.fallback,'queued mutation granted false fallback');await accepted.operation.cancel();await accepted.operation.dispose();await s.pendingOperation.dispose();
 }
 await x.bridge.execute(encode({command:10,handle:x.index}));x.indexDisposed=true;await scope.dispose();window.__selectedStage='capture cap';const canonical=encode({command:35,handle:x.source,sequence:3n,query:{...x.query,stateRevision:2n},budget,payload:new Uint8Array(8)}),caps=Array.from({length:16},()=>beginGeoWorkerMutationCapture(x.bridge,canonical));let cap=false;try{beginGeoWorkerMutationCapture(x.bridge,canonical);}catch{cap=true;}for(const c of caps)c.close();check(cap,'capture17 admitted');
 view.draw();await nextFrame();check(pixel().join(',')===before.join(','),'selected controls changed old paint');check(x.seed.data.record(0).featureId===MAX&&x.seed.data.identity.time.instant===-(1n<<63n),'old CPU authority changed');
 window.__selectedMutation={ok:true,genuineWorker:true,literalU64:true,exactI64:true,lost35ExactReplay:true,forgedFallbackRejected:true,genuineFallbackStatePreserved:true,genuineAdmissionRejectedStatePreserved:true,queuedMutation12:true,foreignCollidingRegistryRejected:true,captureCapacity16:true,oldPixel:before,oldPaintPreserved:true,scope:'Bounded35/36 journal adoption; selected19 recovery and massive performance remain pending.'};
}catch(error){window.__selectedMutation={ok:false,stage:window.__selectedStage,error:error.stack??String(error),code:error.code,status:error.status,admissionError:window.__admissionError,requests:requests.slice(-10).map(r=>({command:r.command,handle:String(r.handle),sequence:String(r.sequence)}))};}
finally{if(view)view.destroy();view=paint=undefined;for(const x of contexts)try{await x.seed.dispose();if(!x.indexDisposed)await x.bridge.execute(encode({command:10,handle:x.index}));if(!x.sourceDisposed)await x.bridge.execute(encode({command:10,handle:x.source}));}catch{}for(const s of scopes)try{await s.dispose();}catch{}for(const w of workers)try{await w.dispose();}catch{}Worker.prototype.postMessage=nativePost;holder.remove();}
