import {createXygWasmWorker,createGeoSelectedScope,claimGeoSelectedState,encodeGeoScaleRequest as encode,decodeGeoScaleReply as decode,encodeGeoChunkRequest,encodeGeoScaleStyle,driveGeoSession,driveGeoIndexSession,prepareGeoSceneData,beginGeoWorkerMutationCapture} from '/selected-publication-proof.js';
import {hydrateWasmPainter} from '/packages/xy-client/dist/index.js';
const budget={processorBytes:128<<20,maxRowsExamined:1000000n,maxReadBytes:128n<<20n,maxChunks:65536,pageRows:4096},MAX=0xffffffffffffffffn;
const check=(value,message)=>{if(!value)throw Error(message);},reject=async(p,message)=>{let failed=false;try{await p;}catch{failed=true;}check(failed,message);};
const nextFrame=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))),workers=[],contexts=[],requests=[],scopes=[];
const nativePost=Worker.prototype.postMessage;
Worker.prototype.postMessage=function(message,transfer){if(['geo.scale.execute','geo.scale.read'].includes(message.type)){const v=new DataView(message.request);requests.push({worker:this,id:message.requestId,command:v.getUint32(8,true),handle:v.getBigUint64(16,true),sequence:v.getBigUint64(24,true),request:message.request.slice(0)});}return nativePost.call(this,message,transfer);};
function worker(){const w=createXygWasmWorker({workerUrl:'/packages/xy-client/dist/wasm-worker.js',wasm:'/packages/xy-client/dist/xyg-wasm.wasm',maxArenaBytes:budget.processorBytes});workers.push(w);return w;}
async function fixture(w){
 await w.ready;const bridge=w.geoScaleBridge(),descriptor=new Uint8Array(120),v=new DataView(descriptor.buffer);descriptor.set([88,89,71,68]);[1,1,4326,1,0].forEach((n,i)=>v.setUint32(4+4*i,n,true));v.setBigUint64(24,2n,true);v.setBigUint64(32,2n,true);[0,0,90,1].forEach((n,i)=>v.setFloat64(64+8*i,n,true));descriptor.set([1,1],96);v.setBigUint64(104,MAX,true);v.setBigUint64(112,9007199254740993n,true);
 const chunk=await bridge.read(encodeGeoChunkRequest({descriptor,rows:2,intervals:{starts:BigInt64Array.of(-(1n<<63n),-(1n<<63n)),ends:BigInt64Array.of((1n<<63n)-1n,(1n<<63n)-1n),startValidity:Uint8Array.of(1,1),endValidity:Uint8Array.of(1,1)}},budget.processorBytes));
 const builder=decode(await bridge.execute(encode({command:1}))).handle;let source,seed,index;
 try{await bridge.execute(encode({command:2,handle:builder,payload:new Uint8Array(chunk)}));await bridge.execute(encode({command:3,handle:builder,generation:MAX}));const manifest=await bridge.read(encode({command:21,handle:builder}));source=decode(await bridge.execute(encode({command:4,payload:new Uint8Array(manifest),budget}))).handle;
  const readChunk=async()=>chunk.slice(0),info=(await driveGeoSession(bridge,{handle:source,sequence:0n,budget,readChunk})).source;
  const query={camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:0,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:32768,previousDirect:true,sourceDigest:info.digest.slice(),generation:MAX,layerId:MAX,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:1,instant:-(1n<<63n)},maxProjectedVertices:1000000n};
  await bridge.execute(encode({command:5,handle:source,sequence:1n,query,budget}));await driveGeoSession(bridge,{handle:source,sequence:1n,budget,readChunk});const style=encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0});seed=await prepareGeoSceneData(bridge,{handle:source,sequence:1n,budget,style});
  const p=new Uint8Array(16),pv=new DataView(p.buffer);pv.setUint32(0,16,true);pv.setBigUint64(8,1000000n,true);index=decode(await bridge.execute(encode({command:17,handle:seed.handle,sequence:1n,budget,payload:p}))).handle;const pages=new Map(),readPage=async t=>pages.get(t.page).slice(),writePage=async(t,b)=>{check(pages.size<32,'external page cache bound');pages.set(t.page,b.slice());};await driveGeoIndexSession(bridge,{handle:index,sequence:1n,budget,readChunk,readPage,writePage});
  const context={w,bridge,source,seed,index,query,style,readChunk,readPage,pages};contexts.push(context);return context;
 }catch(error){if(seed)await seed.dispose();if(index)await bridge.execute(encode({command:10,handle:index}));if(source)await bridge.execute(encode({command:10,handle:source}));throw error;}finally{await bridge.execute(encode({command:10,handle:builder}));}
}
async function state(x){const scope=await createGeoSelectedScope(x.bridge,{frameHandle:x.seed.handle,sequence:1n,namespace:MAX,layerId:MAX,budget});scopes.push(scope);const s=await scope.state({revision:2n,ids:BigUint64Array.of(MAX),fill:Uint8Array.of(0,255,0,255),budget});return {scope,s};}
function fault(w,command,transform){const native=w.worker,receive=native.onmessage;let armed=true;native.onmessage=event=>{const request=requests.find(r=>r.worker===native&&r.id===event.data?.requestId);if(armed&&request?.command===command&&event.data?.ok){armed=false;transform(event,request,receive,native);return;}receive.call(native,event);};return ()=>{native.onmessage=receive;check(!armed,'fault never reached actual Worker');};}
const holder=document.createElement('div');document.body.append(holder);let view,paint;
try{
 window.__selectedStage='seed';const w=worker(),x=await fixture(w),foreign=worker(),y=await fixture(foreign);check(x.seed.handle===y.seed.handle,'colliding issuers omitted');
 paint=await w.prepareGeoFrame(x.seed.handle,1n).result;view=hydrateWasmPainter(holder,paint);view.draw();await nextFrame();const pixel=()=>{const c=document.createElement('canvas');c.width=800;c.height=600;const g=c.getContext('2d');g.fillStyle='white';g.fillRect(0,0,800,600);g.drawImage(view.canvas,0,0);return [...g.getImageData(400,300,1,1).data];},before=pixel();check(before.join(',')==='255,0,0,255','old red oracle');
 const initial=await state(x),scope=initial.scope;await initial.s.dispose();let sequence=2n,frames=[],restores=[];
 for(const mode of ['lost19','corrupt19','confirm','read',...Array.from({length:12},(_,i)=>'micro'+(i+1))]){
  window.__selectedStage=mode;const s=await scope.state({revision:2n,ids:BigUint64Array.of(MAX),fill:Uint8Array.of(0,255,0,255),budget}),accepted=await s.begin({command:36,handle:x.index,sequence,query:{...x.query,stateRevision:2n},budget}),op=accepted.operation;await op.drive({readPage:x.readPage});let changed=false;
  const command=mode==='confirm'?47:mode==='read'?23:19;let restore;
  if(mode==='read'){
   const native=w.worker,receive=native.onmessage;let armed=true;native.onmessage=event=>{const r=requests.find(r=>r.worker===native&&r.id===event.data?.requestId);if(armed&&r?.command===23&&event.data?.ok){armed=false;receive.call(native,{data:{...event.data,ok:false,error:{code:'XYG_WASM_RESOURCE_LIMIT',status:3,message:'lost read23'}}});return;}receive.call(native,event);};restore=()=>{native.onmessage=receive;check(!armed,'read fault not reached');};
  }else restore=fault(w,command,(event,r,receive,native)=>{if(mode.startsWith('micro')){const packet=event.data.value;receive.call(native,event);const mutate=n=>queueMicrotask(()=>{if(n>1)mutate(n-1);else{new DataView(packet).setBigUint64(16,999999n,true);new DataView(packet).setBigUint64(32,1n,true);changed=true;}});mutate(Number(mode.slice(5)));}else if(mode==='lost19'||mode==='read')receive.call(native,{data:{...event.data,ok:false,error:{code:'XYG_WASM_RESOURCE_LIMIT',status:3,message:'synthetic after actual19'}}});else{new DataView(event.data.value).setBigUint64(16,999999n,true);receive.call(native,event);}});
  let frame,error;try{frame=await op.prepare(x.style);}catch(e){error=e;}restore();if(!frame){check(op.publicationPending,'lost publication guard dropped');await reject(op.cancel(),'uncertain publication treated as Query');check(x.seed.data.record(0).featureId===MAX,'old CPU frame changed');frame=await op.prepare(x.style);}
  check(frame.handle===s.handle&&frame.data.record(0).featureId===MAX&&frame.data.selection.visibleVertices===1n,'publication retagged frame');check(!mode.startsWith('micro')||changed,'microtask not reached');await s.pendingOperation.dispose();
  const p=await w.prepareGeoFrame(frame.handle,sequence).result,h=document.createElement('div');document.body.append(h);const green=hydrateWasmPainter(h,p);green.draw();await nextFrame();const c=document.createElement('canvas');c.width=800;c.height=600;const g=c.getContext('2d');g.drawImage(green.canvas,0,0);const rgba=[...g.getImageData(400,300,1,1).data];check(rgba.join(',')==='0,255,0,255','selected green pixel '+rgba);green.destroy();h.remove();await frame.dispose();sequence++;
 }
 for(let i=0;i<20;i++){const s=await scope.state({revision:2n,ids:BigUint64Array.of(MAX),fill:Uint8Array.of(0,255,0,255),budget}),op=(await s.begin({command:36,handle:x.index,sequence,query:{...x.query,stateRevision:2n},budget})).operation;await op.drive({readPage:x.readPage});const frame=await op.prepare(x.style);await frame.dispose();await s.pendingOperation.dispose();sequence++;}
 await x.bridge.execute(encode({command:10,handle:x.index}));x.indexDisposed=true;await scope.dispose();view.draw();await nextFrame();check(pixel().join(',')===before.join(','),'old paint changed');check(!requests.some(r=>r.worker===w.worker&&r.command===10&&r.handle===x.source),'publication disposed original Source');
 window.__selectedMutation={ok:true,actualWorker:true,fullU64:true,exactI64:true,lost19ExactReplay:true,corrupt19Guard:true,strict47Confirm:true,read23Retry:true,microtask12:true,selectedGreenPixel:true,oldRedPaint:true,sequential20Capacity:true,collidingWorkers:true,scope:'Bounded public selected19 recovery; no massive latency claim.'};

}catch(error){window.__selectedMutation={ok:false,stage:window.__selectedStage,error:error.stack??String(error),code:error.code,status:error.status,admissionError:window.__admissionError,requests:requests.slice(-10).map(r=>({command:r.command,handle:String(r.handle),sequence:String(r.sequence)}))};}
finally{if(view)view.destroy();view=paint=undefined;for(const x of contexts)try{await x.seed.dispose();if(!x.indexDisposed)await x.bridge.execute(encode({command:10,handle:x.index}));if(!x.sourceDisposed)await x.bridge.execute(encode({command:10,handle:x.source}));}catch{}for(const s of scopes)try{await s.dispose();}catch{}for(const w of workers)try{await w.dispose();}catch{}Worker.prototype.postMessage=nativePost;holder.remove();}
