// Actual native-issued XYOV, shared GL painter and binary host CAS under strict CSP.
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import {overviewHostFixture} from '../../packages/xy-node/test/geo-native-overview-host-fixture.mjs';
const f=await overviewHostFixture({splitTime:true});let corrupt=false,lostCommit=false,hold=false,held=false,releaseHold;
const server=createServer(async(req,res)=>{try{
 if(req.url==='/'){res.setHeader('Content-Security-Policy',"default-src 'none'; script-src 'self'; style-src 'unsafe-inline'; connect-src 'self'; img-src data:; object-src 'none'; base-uri 'none'");res.setHeader('Content-Type','text/html');res.end('<!doctype html><div id="chart" tabindex="0"></div><script type="module" src="/page.js"></script>');return;}
 if(req.url==='/index.js'){res.setHeader('Content-Type','text/javascript');res.end(await readFile('packages/xy-client/dist/index.js'));return;}
 if(req.url==='/page.js'){res.setHeader('Content-Type','text/javascript');res.end(`import {XygGeoHostView} from '/index.js';let callback;window.view=new XygGeoHostView(document.getElementById('chart'),{onMessage:c=>{callback=c;return()=>callback=undefined;},send:(message,buffers)=>{fetch('/rpc',{method:'POST',headers:{'x-request':message.request,'x-mount':message.mount},body:buffers[0]}).then(async r=>{if(!r.ok){callback?.({type:'geo_host',request:message.request,...await r.json()},[]);return;}const b=await r.arrayBuffer(),v=new DataView(b),out=[];let at=4;for(let i=0;i<v.getUint32(0,true);i++){const n=v.getUint32(at,true);at+=4;out.push(b.slice(at,at+n));at+=n;}callback?.({type:'geo_host',request:message.request},out);}).catch(e=>callback?.({type:'geo_host',request:message.request,error:e.message},[]));}});window.ready=window.view.ready;`);return;}
 if(req.url!=='/rpc'){res.statusCode=404;res.end();return;}
 const chunks=[];let length=0;for await(const b of req){length+=b.length;if(length>256)throw Error('oversized host request');chunks.push(b);}const raw=Uint8Array.from(Buffer.concat(chunks)).buffer,op=new DataView(raw).getUint32(8,true);
 const [message,attachments]=await f.adapter.handle({type:'geo_host',request:req.headers['x-request'],mount:req.headers['x-mount']},[raw]);
 if(op===6&&hold){hold=false;held=true;await new Promise(r=>releaseHold=r);held=false;}
 if(message.error){res.statusCode=400;res.end(JSON.stringify(message));return;}
 if(op===7&&lostCommit){lostCommit=false;res.end(Buffer.alloc(4));return;}
 const parts=[Buffer.alloc(4)];parts[0].writeUInt32LE(attachments.length);for(let i=0;i<attachments.length;i++){const value=attachments[i],b=Buffer.from(value instanceof ArrayBuffer?new Uint8Array(value):value);if(op===6&&i===2&&corrupt){corrupt=false;b[0]^=1;}const size=Buffer.alloc(4);size.writeUInt32LE(b.length);parts.push(size,b);}res.setHeader('Content-Type','application/octet-stream');res.end(Buffer.concat(parts));
 }catch(error){res.statusCode=500;res.end(JSON.stringify({error:error.message}));}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({executablePath:process.env.XYG_CHROMIUM??chromium.executablePath(),args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});const page=await browser.newPage({viewport:{width:1000,height:1400}}),errors=[],external=[];
page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===origin||!['http:','https:'].includes(u.protocol))return r.continue();external.push(u.href);return r.abort();});
const update=seq=>page.evaluate(sequence=>{const v=window.view,i=v.identity;return v.update({operation:3,args:[1,0],sequence:BigInt(sequence),cameraRevision:BigInt(sequence),timeRevision:BigInt(sequence),stateRevision:i.stateRevision,time:{kind:0}});},String(seq));
try{
 await page.goto(origin);await page.waitForFunction(()=>window.ready);await page.evaluate(()=>window.ready);
 const initial=await page.evaluate(()=>{const v=window.view;return {owner:v.owner.toString(),sequence:v.identity.sequence.toString(),camera:[v.identity.camera.width,v.identity.camera.height],canvas:[v.view.canvas.width,v.view.canvas.height],counts:Array.from(document.querySelectorAll('[data-domain-cell]')).map(r=>r.innerText),notice:document.querySelector('[data-xy-overview-counts] [role=status]').textContent};});assert.equal(initial.sequence,'2');assert.equal(initial.counts.length,32);assert.deepEqual(initial.camera,[800,600]);assert.deepEqual(initial.canvas,[800,600]);assert.match(initial.notice,/spatial refinement pending/);assert.equal(f.index.current,undefined);
 for(let i=0;i<4;i++)await page.getByRole('button',{name:'Next 32 domain cells'}).click();await page.locator('[data-domain-cell="136"]').focus();assert.equal(await page.locator('[data-domain-cell="136"] td').innerText(),'1');await page.keyboard.press('ArrowRight');await page.waitForTimeout(50);assert.equal(f.adapter.sequence,2n);
 const countText=await page.locator('[data-xy-overview-counts]').innerText();corrupt=true;await assert.rejects(update(3));assert.equal(await page.locator('[data-xy-overview-counts]').innerText(),countText);assert.equal(f.adapter.sequence,2n);
 hold=true;await page.evaluate(()=>{window.updating=window.view.update({operation:3,args:[1,0],sequence:4n,cameraRevision:4n,timeRevision:4n,stateRevision:1n,time:{kind:0}});});for(let i=0;i<100&&!held;i++)await new Promise(r=>setTimeout(r,10));assert.equal(held,true);assert.equal(await page.locator('[data-xy-overview-counts]').innerText(),countText);releaseHold();await page.evaluate(()=>window.updating);assert.equal(await page.evaluate(()=>document.activeElement.dataset.domainCell),'136');assert.equal(await page.locator('[data-domain-cell]').count(),32);assert.equal(f.index.current,undefined);assert.equal(await page.locator('[data-domain-cell="136"] td').innerText(),'2');
 lostCommit=true;await assert.rejects(update(5));assert.equal(await page.evaluate(()=>window.view.identity.sequence),4n);await page.evaluate(()=>window.view.recover());assert.equal(f.adapter.sequence,5n);assert.equal(await page.evaluate(()=>window.view.identity.sequence),5n);
 assert.equal(await page.evaluate(()=>{try{window.view.pick({x:400,y:300});return false;}catch{return true;}}),true);
 const pixels=await page.evaluate(()=>{const v=window.view.view;v._drawNow();const c=v.canvas;let p;if(v._glHost)p=v._present2d.getImageData(0,0,c.width,c.height).data;else{const gl=v.gl;p=new Uint8Array(gl.drawingBufferWidth*gl.drawingBufferHeight*4);gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,p);}let blue=0;for(let i=0;i<p.length;i+=4)if(p[i+2]>p[i]+40&&p[i+2]>p[i+1])blue++;return {blue,width:c.width,height:c.height};});assert.ok(pixels.blue>0,JSON.stringify(pixels));
 const before=f.adapter.frame;await f.index.dispose();await f.seed.dispose();await f.source.dispose();assert.equal(before.data.final,false);await page.evaluate(()=>window.view.dispose());assert.equal(f.adapter.mounted,false);assert.equal(await page.locator('[data-domain-cell]').count(),0);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 const report={ok:true,browser:browser.version(),initial,pixels,oldCountsDuringPending:true,exactTemporalCountBefore:1,exactTemporalCountAfter:2,hydrateFailureKeepsPaint:true,focusedOrdinalPreserved:true,tableKeyboardDoesNotPan:true,lostCommitExactReplay:true,exclusiveCurrent:true,noFeaturePicking:true,producerDisposedBeforeRelease:true,external,errors};if(process.env.XYG_GEO_NATIVE_OVERVIEW_REPORT)await writeFile(process.env.XYG_GEO_NATIVE_OVERVIEW_REPORT,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}finally{releaseHold?.();await browser.close();await new Promise(r=>server.close(r));await f.dispose();}
