import {createXygWasmWorker,XygWasmWorker,XygGeographicChart,GeoOverviewIndex,encodeGeoScaleRequest as encode,decodeGeoScaleReply as decode,encodeGeoChunkRequest,encodeGeoScaleStyle,driveGeoSession,prepareGeoSceneData,createMapLibreGeoLayer} from '/packages/xy-client/dist/index.js';
const budget={processorBytes:128<<20,maxRowsExamined:1000000n,maxReadBytes:128n<<20n,maxChunks:65536,pageRows:4096},MAX=0xffffffffffffffffn;
const check=(p,s)=>{if(!p)throw Error(s);},reject=async(p,s)=>{let failed=false;try{await p;}catch{failed=true;}check(failed,s);};
const frame=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
const worker=()=>createXygWasmWorker({wasm:'/packages/xy-client/dist/xyg-wasm.wasm',workerUrl:'/packages/xy-client/dist/wasm-worker.js',maxArenaBytes:budget.processorBytes});
let a,b,index,indexB,chart,borrowed,uncertainChart,layer;const containers=[];
const host=()=>{const e=document.createElement('div');document.body.append(e);containers.push(e);return e;};
async function build(w,shift=0){
 const bridge=w.geoScaleBridge(),descriptor=new Uint8Array(144),v=new DataView(descriptor.buffer);descriptor.set([88,89,71,68]);[1,1,4326,1,0].forEach((n,i)=>v.setUint32(4+4*i,n,true));v.setBigUint64(24,3n,true);v.setBigUint64(32,3n,true);[-179+shift,0,179,0,0,0].forEach((n,i)=>v.setFloat64(64+8*i,n,true));descriptor.set([1,1,1],112);[MAX,1n<<63n,7n].forEach((n,i)=>v.setBigUint64(120+8*i,n,true));
 const chunk=await bridge.read(encodeGeoChunkRequest({descriptor,rows:3,intervals:{starts:BigInt64Array.of(-(1n<<63n),0n,10n),ends:BigInt64Array.of(5n,10n,(1n<<63n)-1n),startValidity:Uint8Array.of(1,1,1),endValidity:Uint8Array.of(1,1,1)}},budget.processorBytes));
 const builder=decode(await bridge.execute(encode({command:1}))).handle;let source,seed;
 try{await bridge.execute(encode({command:2,handle:builder,payload:new Uint8Array(chunk)}));await bridge.execute(encode({command:3,handle:builder,generation:MAX}));const manifest=await bridge.read(encode({command:21,handle:builder}));source=decode(await bridge.execute(encode({command:4,payload:new Uint8Array(manifest),budget}))).handle;
 const readChunk=async()=>chunk.slice(0),info=(await driveGeoSession(bridge,{handle:source,sequence:0n,budget,readChunk})).source;
 const query={camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:0,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:1,previousDirect:true,sourceDigest:info.digest.slice(),generation:MAX,layerId:MAX,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:0},maxProjectedVertices:1000000n};
 await bridge.execute(encode({command:5,handle:source,sequence:1n,budget,query}));await driveGeoSession(bridge,{handle:source,sequence:1n,budget,readChunk});seed=await prepareGeoSceneData(bridge,{handle:source,sequence:1n,budget,style:encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0})});
 const pages=new Map();let bad=false,gate;
 const callbacks={readChunk,async readPage(t){if(gate){const g=gate;gate=undefined;g.entered.resolve();await g.release.promise;}const p=pages.get(`${t.namespace}:${t.page}`);check(p,'missing overview page');return bad?p.slice(0,-1):p.slice();},async writePage(t,p){check(pages.size<32,'fixture page bound');pages.set(`${t.namespace}:${t.page}`,p.slice());}};
 const result=await GeoOverviewIndex.fromFrame(seed,{bridge,budget,maxVertices:1000000n,...callbacks});return {index:result,query:{...query,time:{kind:1,instant:0n},maxCells:0,previousDirect:false,maxProjectedVertices:0n},pages,bad(value){bad=value;},gated(){gate={entered:deferred(),release:deferred()};return gate;}};
 }finally{if(seed)await seed.dispose();if(source)await bridge.execute(encode({command:10,handle:source}));await bridge.execute(encode({command:10,handle:builder}));}
}
const pixel=(el,x=160,y=284)=>{const source=el.querySelector('canvas[role="img"]'),c=document.createElement('canvas');check(source,'paint canvas missing');c.width=800;c.height=600;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,800,600);ctx.drawImage(source,0,0);return [...ctx.getImageData(x,y,1,1).data];};
try{
 a=worker();b=worker();await Promise.all([a.ready,b.ready]);const aa=await build(a),bb=await build(b,1);index=aa.index;indexB=bb.index;const callerFrame=await index.update(aa.query,{sequence:3n});
 check(index.handle===indexB.handle,'fixture did not produce colliding handles');check(aa.query.sourceDigest.some((n,i)=>n!==bb.query.sourceDigest[i]),'foreign fixture digest was identical');check(index.bridge===a.geoScaleBridge()&&Object.isFrozen(index.bridge),'stable frozen bridge absent');
 await reject(XygGeographicChart.fromOverview({mode:'temporal-domain-overview',el:host(),worker:b,index,query:aa.query,sequence:7n}),'foreign colliding issuer accepted');
 await reject(XygGeographicChart.fromOverview({mode:'temporal-domain-overview',el:host(),worker:Object.create(XygWasmWorker.prototype),index,query:aa.query,sequence:7n}),'prototype lookalike accepted');
 await reject(GeoOverviewIndex.fromFrame({handle:1n},{bridge:{execute:r=>a.geoScaleExecute(r),read:r=>a.geoScaleRead(r)},budget,maxVertices:1n,...{readChunk:async()=>new ArrayBuffer(0),readPage:async()=>new ArrayBuffer(0),writePage:async()=>{}}}),'numeric source owner/lookalike closures issued authority');
 Object.defineProperty(index,'bridge',{value:b.geoScaleBridge()});Object.defineProperty(index,'handle',{value:indexB.handle});
 const originalPrepare=a.prepareGeoFrame.bind(a),native=a.worker,originalReceiver=native.onmessage;let privateFrameHandle=0n;native.onmessage=event=>{const value=event.data?.value;if(value instanceof ArrayBuffer&&value.byteLength===256&&new DataView(value).getUint32(8,true)===16&&new DataView(value).getBigUint64(24,true)===7n)privateFrameHandle=new DataView(value).getBigUint64(16,true);originalReceiver.call(native,event);};
 let redirected=0;for(const method of ['geoScaleExecute','geoScaleRead','geoScaleTransport','queueOwnedGeo','checkOwnedGeoCapacity','assertLive','allocateRequest','promiseFor','prepareGeoFrame','acquireGeoTransport'])a[method]=()=>{redirected++;throw Error('mutable dispatch invoked');};
 const el=host(),errors=[],initialGate=aa.gated();el.dataset.overviewProof='ordinary';chart=await XygGeographicChart.fromOverview({mode:'temporal-domain-overview',el,worker:a,index,query:aa.query,sequence:7n,onChange(){throw Error('isolated observer');},onError:e=>errors.push(String(e))});await initialGate.entered.promise;check(el.querySelector('tbody').children.length===0&&[...el.querySelectorAll('button')].every(b=>b.disabled),'unpublished companion invented zero counts');initialGate.release.resolve();await chart.ready;await frame();
 check(redirected===0,'genuine issuer used edited public/underlying dispatch');check(pixel(el).join(',')==='55,155,255,255','ordinary overview pixel');check(typeof chart.pick!=='function'&&typeof chart.sourceRows!=='function','overview exposed source-feature route');check(chart.snapshot().counts[128]===1n&&chart.snapshot().counts[143]===1n&&chart.snapshot().final===false,'private temporal counts/flags');
 check(index.current===callerFrame&&privateFrameHandle!==0n&&privateFrameHandle!==callerFrame.handle,'controller frame aliased caller index.current');native.onmessage=originalReceiver;index.current.data.count=()=>MAX;index.current.data.identity.sequence=99n;await callerFrame.dispose();let probe=await originalPrepare(privateFrameHandle,7n).result;check(probe.painter.byteLength>0,'caller current disposal released controller Data authority');probe=undefined;check(chart.snapshot().sequence===7n&&chart.snapshot().counts[128]===1n,'mutable parsed decorations changed private count snapshot');
 const tbody=el.querySelector('tbody');check(tbody.children.length===32,'companion DOM not bounded');check(el.textContent.includes('spatial refinement pending'),'nonfinal companion notice');
 const next=[...el.querySelectorAll('button')].find(e=>e.textContent==='Next 32 domain cells');for(let i=0;i<4;i++)next.click();const focused=tbody.querySelector('[data-domain-cell="128"]');focused.focus();check(document.activeElement===focused&&focused.getAttribute('aria-label').includes('1 exact temporal vertices'),'exact labeled domain focus');
 window.__overviewVisualReady=true;while(!window.__overviewContinue)await new Promise(r=>setTimeout(r,10));
 let copied=0;const giant=new Uint8Array(1024);giant.slice=()=>{copied++;throw Error('oversized digest copied');};await reject(chart.update({...aa.query,sourceDigest:giant},{sequence:8n}),'oversized digest accepted');check(copied===0,'oversized digest copied before rejection');
 let enumerated=0;const fixedCamera={...aa.query.camera};Object.defineProperty(fixedCamera,'unboundedExtra',{enumerable:true,get(){enumerated++;throw Error('extra camera field read');}});
 await chart.update({...aa.query,camera:fixedCamera,time:{kind:1,instant:10n},timeRevision:2n},{sequence:8n});await frame();check(enumerated===0,'camera extras traversed');check(chart.snapshot().counts.reduce((x,y)=>x+y,0n)===1n&&chart.snapshot().time.instant===10n,'time update count snapshot');check(document.activeElement?.dataset.domainCell==='128','accepted update lost domain focus');
 const accepted=chart.snapshot(),prior=pixel(el);aa.bad(true);await reject(chart.update({...aa.query,timeRevision:3n},{sequence:9n}),'corrupt overview page published');aa.bad(false);await frame();check(chart.snapshot().sequence===accepted.sequence&&pixel(el).join(',')===prior.join(',')&&tbody.children.length===32,'failed query changed paint/table');
 const abort=new AbortController();abort.abort();await reject(chart.update(aa.query,{sequence:10n,signal:abort.signal}),'pre-aborted query published');
 const gated=aa.gated(),cancel=new AbortController(),running=chart.update(aa.query,{sequence:11n,signal:cancel.signal});await gated.entered.promise;cancel.abort();let settled=false;running.catch(()=>{}).finally(()=>{settled=true;});await new Promise(r=>setTimeout(r,30));check(!settled,'callback loan ACK before settlement');gated.release.resolve();await reject(running,'cancelled query published');await chart.update(aa.query,{sequence:12n});await frame();check(pixel(el).join(',')==='55,155,255,255','recovery pixel');
 const qgate=aa.gated(),first=chart.update(aa.query,{sequence:13n});await qgate.entered.promise;const queued=[];for(let i=0;i<15;i++)queued.push(chart.update(aa.query,{sequence:BigInt(14+i)}));await reject(chart.update(aa.query,{sequence:29n}),'queue17 accepted');qgate.release.resolve();await first;await Promise.all(queued);await frame();check(chart.snapshot().sequence===28n&&tbody.children.length===32,'accepted serial queue lost samples');
 const closeGate=aa.gated(),closingQuery=chart.update(aa.query,{sequence:29n});await closeGate.entered.promise;const busyHost=host(),busy=await XygGeographicChart.fromOverview({mode:'temporal-domain-overview',el:busyHost,worker:a,index,query:aa.query,sequence:30n});await reject(busy.ready,'sharedIndex concurrent query silently queued');check(busyHost.children.length===0&&chart.snapshot().sequence===28n,'busy sharedIndex changed accepted frame or leaked DOM');let closed=false;const closing=chart.dispose();check(closing===chart.dispose(),'pending disposal not coalesced');closing.then(()=>{closed=true;});await new Promise(r=>setTimeout(r,30));check(!closed&&tbody.children.length===32,'close released borrower before settlement');closeGate.release.resolve();await reject(closingQuery,'close published in-flight query');await closing;chart=undefined;check(el.children.length===0,'owned DOM survived close');
 const canvas=document.createElement('canvas'),shell=host();canvas.width=800;canvas.height=600;shell.style.cssText='position:relative;width:800px;height:600px';shell.append(canvas);const gl=canvas.getContext('webgl2',{preserveDrawingBuffer:true,antialias:false});check(gl,'borrowed context absent');layer=createMapLibreGeoLayer({id:'public-overview'});layer.onAdd({getCanvas:()=>canvas,getContainer:()=>shell,triggerRepaint(){}},gl);
 const set=layer.setPrepared.bind(layer),release=layer.releasePrepared.bind(layer);let failRelease=true,failSet=false,releaseAttempts=0;const callbacks={setPrepared(prepared){if(failSet){failSet=false;throw Error('candidate borrowed prepare failure');}set(prepared);},releasePrepared(){releaseAttempts++;if(failRelease){failRelease=false;throw Error('transient borrowed release failure');}release();}};const borrowedHost=host();borrowed=await XygGeographicChart.fromOverview({mode:'temporal-domain-overview',el:borrowedHost,worker:a,index,query:aa.query,sequence:30n,layer:callbacks});callbacks.setPrepared=()=>{throw Error('replaced layer callback');};callbacks.releasePrepared=()=>{throw Error('replaced layer release');};await borrowed.ready;gl.viewport(0,0,800,600);gl.clearColor(1,1,1,1);gl.clear(gl.COLOR_BUFFER_BIT);layer.render(gl,{});const rgba=new Uint8Array(4);gl.readPixels(160,600-284,1,1,gl.RGBA,gl.UNSIGNED_BYTE,rgba);check([...rgba].join(',')==='55,155,255,255','borrowed overview pixel');check(layer.pick(160,284)===null,'overview gained feature picking');failSet=true;await reject(borrowed.update({...aa.query,time:{kind:1,instant:10n},timeRevision:2n},{sequence:31n}),'borrowed candidate failure published');gl.clear(gl.COLOR_BUFFER_BIT);layer.render(gl,{});gl.readPixels(160,600-284,1,1,gl.RGBA,gl.UNSIGNED_BYTE,rgba);check(borrowed.snapshot().sequence===30n&&[...rgba].join(',')==='55,155,255,255'&&borrowedHost.querySelector('tbody').children.length===32,'borrowed candidate failure changed oldpaint/table');await index.dispose();index=undefined;await reject(borrowed.update(aa.query,{sequence:31n}),'closed index allocated');check(borrowed.snapshot().sequence===30n,'closed index changed accepted frame');await reject(borrowed.dispose(),'failed layer release was ignored');check(borrowed.snapshot().sequence===30n&&releaseAttempts===1,'failed release lost frame authority');await borrowed.dispose();borrowed=undefined;check(releaseAttempts===2,'failed disposal was cached permanently');check(!gl.isContextLost()&&canvas.width===800&&shell.contains(canvas),'borrowed close destroyed foreign canvas');layer.dispose();layer=undefined;
 const genuineB=b.geoScaleBridge(),backing=b.worker,receiver=backing.onmessage,heldGate=deferred();let intercepted=false;backing.onmessage=event=>{const value=event.data?.value;if(!intercepted&&value instanceof ArrayBuffer&&value.byteLength===256&&new DataView(value).getUint32(8,true)===0){intercepted=true;heldGate.resolve(event);return;}receiver.call(backing,event);};const holding=b.geoScaleBridge().execute(encode({command:1}));const heldEvent=await heldGate.promise;const queuedOrigin=b.geoScaleBridge().execute(encode({command:6,handle:0n,budget}));b.worker=a.worker;const attached=encode({command:1});await reject(genuineB.execute(attached),'changed backing worker accepted');check(attached.byteLength===256,'changed origin detached input before rejection');receiver.call(backing,heldEvent);await reject(queuedOrigin,'queued operation ignored changed backing after await');const heldBuilder=decode(await holding).handle;b.worker=backing;backing.onmessage=receiver;await b.geoScaleBridge().execute(encode({command:10,handle:heldBuilder}));
 const uncertainHost=host();uncertainChart=await XygGeographicChart.fromOverview({mode:'temporal-domain-overview',el:uncertainHost,worker:b,index:indexB,query:bb.query,sequence:7n});await uncertainChart.ready;await frame();const oldPixel=pixel(uncertainHost),actual=b.worker,original=actual.onmessage;let corrupted=false;const dataReceipts=[],cleanupReceipts=[];actual.onmessage=event=>{const value=event.data?.value;if(value instanceof ArrayBuffer&&value.byteLength===256){const v=new DataView(value),code=v.getUint32(8,true);if(code===16){dataReceipts.push(new Uint8Array(value).slice());if(!corrupted){corrupted=true;v.setUint32(4,999,true);}}else if(code===0)cleanupReceipts.push({handle:v.getBigUint64(16,true),sequence:v.getBigUint64(24,true)});}original.call(actual,event);};await reject(uncertainChart.update({...bb.query,timeRevision:2n},{sequence:8n}),'corrupt allocation confirmation published');check(corrupted&&indexB.pendingOperation,'uncertain allocation was not retained');await frame();check(uncertainChart.snapshot().sequence===7n&&pixel(uncertainHost).join(',')===oldPixel.join(',')&&uncertainHost.querySelector('tbody').children.length===32,'uncertain allocation changed old paint/table');await reject(uncertainChart.update(bb.query,{sequence:9n}),'unsettled producer allocated again');await uncertainChart.dispose();uncertainChart=undefined;await indexB.dispose();indexB=undefined;actual.onmessage=original;check(dataReceipts.length===2,'known29 publication did not replay exactly once');check(dataReceipts[0].every((n,i)=>n===dataReceipts[1][i]),'29 recovery replaced its original immutable receipt');const target=new DataView(dataReceipts[0].buffer).getBigUint64(16,true),confirmation=cleanupReceipts.findIndex(r=>r.handle===target&&r.sequence===8n),disposal=cleanupReceipts.findIndex(r=>r.handle===target&&r.sequence===0n);check(confirmation>=0&&disposal>confirmation,'captured29 birth was not confirmed before knownData10');
 window.__overviewController={ok:true,publicComposition:true,privateIssuer:true,collidingWorkers:true,capturedDispatch:true,originCheckedAfterQueuedAwait:true,changedOriginInputAttached:true,ordinaryPixel:[55,155,255,255],borrowedPixel:[...rgba],boundedRows:32,noUnpublishedZeroCounts:true,exactCounts:true,fullU64Ids:true,fullI64Intervals:true,timeUpdate:true,focusPreserved:true,oversizedDigestNoCopy:true,extraCameraIgnored:true,oldPaintTable:true,callbackCancelAck:true,serialAccepted:16,overflowRejected:true,borrowedCallbacksCaptured:true,sourceIndexDisposal:true,pendingCloseLoan:true,sharedIndexBusyExplicit:true,borrowedCandidateOldPaint:true,privateSnapshotIgnoresDecoration:true,callerCurrentDisposalIndependent:true,disposalRetry:true,uncertainAllocationOldPaint:true,unknownAllocationRecovery:'exact-command29-receipt-replay-confirmed-before-data10',recoveredReceiptBytes:256,recoveredReceiptMatchesOriginal:true,featurePickingUnavailable:true,observerIsolated:errors.length>0};
}catch(error){window.__overviewController={ok:false,error:error.stack??String(error)};}
finally{if(uncertainChart)await uncertainChart.dispose();if(chart)await chart.dispose();if(borrowed)await borrowed.dispose();if(layer)layer.dispose();if(index)try{await index.dispose();}catch{}if(indexB)try{await indexB.dispose();}catch{}if(a)await a.dispose();if(b)await b.dispose();for(const e of containers)e.remove();}
