import {createXygWasmWorker,XygWasmWorker,XygGeographicChart,GeoOverviewIndex,encodeGeoScaleRequest as encode,decodeGeoScaleReply as decode,encodeGeoChunkRequest,encodeGeoScaleStyle,driveGeoSession,prepareGeoSceneData,createMapLibreGeoLayer} from '/packages/xy-client/dist/index.js';
const budget={processorBytes:128<<20,maxRowsExamined:1000000n,maxReadBytes:128n<<20n,maxChunks:65536,pageRows:4096},MAX=0xffffffffffffffffn;
const check=(p,s)=>{if(!p)throw Error(s);},reject=async(p,s)=>{let failed=false;try{await p;}catch{failed=true;}check(failed,s);};
const frame=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
const worker=()=>createXygWasmWorker({wasm:'/packages/xy-client/dist/xyg-wasm.wasm',workerUrl:'/packages/xy-client/dist/wasm-worker.js',maxArenaBytes:budget.processorBytes});
let a,b,index,indexB,chart,borrowed,uncertainChart,layer;const containers=[];
const host=()=>{const e=document.createElement('div');document.body.append(e);containers.push(e);return e;};
async function build(w,shift=0){
 const bridge=w.geoScaleBridge(),descriptor=new Uint8Array(144),v=new DataView(descriptor.buffer);descriptor.set([88,89,71,68]);[1,1,4326,1,0].forEach((n,i)=>v.setUint32(4+4*i,n,true));v.setBigUint64(24,3n,true);v.setBigUint64(32,3n,true);[-179+shift,0,179,0,0,0].forEach((n,i)=>v.setFloat64(64+8*i,n,true));descriptor.set([1,1,1],112);[MAX,1n<<63n,7n].forEach((n,i)=>v.setBigUint64(120+8*i,n,true));
 const chunk=await bridge.read(encodeGeoChunkRequest({descriptor,rows:3,intervals:{starts:BigInt64Array.of(-(1n<<63n),0n,10n),ends:BigInt64Array.of(5n,10n,(1n<<63n)-1n),startValidity:Uint8Array.of(1,1,1),endValidity:Uint8Array.of(1,1,1)}},budget.processorBytes));
 const builder=decode(await bridge.execute(encode({command:1}))).handle;let source,seed;
 try{await bridge.execute(encode({command:2,handle:builder,payload:new Uint8Array(chunk)}));await bridge.execute(encode({command:3,handle:builder,generation:MAX}));const manifest=await bridge.read(encode({command:21,handle:builder}));source=decode(await bridge.execute(encode({command:4,payload:new Uint8Array(manifest),budget}))).handle;
 const readChunk=async()=>chunk.slice(0),info=(await driveGeoSession(bridge,{handle:source,sequence:0n,budget,readChunk})).source;
 const query={camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:0,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:1,previousDirect:true,sourceDigest:info.digest.slice(),generation:MAX,layerId:MAX,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:0},maxProjectedVertices:1000000n};
 await bridge.execute(encode({command:5,handle:source,sequence:1n,budget,query}));await driveGeoSession(bridge,{handle:source,sequence:1n,budget,readChunk});seed=await prepareGeoSceneData(bridge,{handle:source,sequence:1n,budget,style:encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0})});
 const pages=new Map();let bad=false,gate;
 const callbacks={readChunk,async readPage(t){if(gate){const g=gate;gate=undefined;g.entered.resolve();await g.release.promise;}const p=pages.get(`${t.namespace}:${t.page}`);check(p,'missing overview page');return bad?p.slice(0,-1):p.slice();},async writePage(t,p){check(pages.size<32,'fixture page bound');pages.set(`${t.namespace}:${t.page}`,p.slice());}};
 const result=await GeoOverviewIndex.fromFrame(seed,{bridge,budget,maxVertices:1000000n,...callbacks});return {index:result,query:{...query,time:{kind:1,instant:0n},maxCells:0,previousDirect:false,maxProjectedVertices:0n},pages,bad(value){bad=value;},gated(){gate={entered:deferred(),release:deferred()};return gate;}};
 }finally{if(seed)await seed.dispose();if(source)await bridge.execute(encode({command:10,handle:source}));await bridge.execute(encode({command:10,handle:builder}));}
}
const pixel=(el,x=160,y=284)=>{const source=el.querySelector('canvas[role="img"]'),c=document.createElement('canvas');check(source,'paint canvas missing');c.width=800;c.height=600;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,800,600);ctx.drawImage(source,0,0);return [...ctx.getImageData(x,y,1,1).data];};
const snapshotRequest=(command,handle,sequence=0n,format=0)=>{const b=new ArrayBuffer(256),v=new DataView(b);new Uint8Array(b).set([88,89,71,74]);v.setUint32(4,1,true);v.setUint32(8,command,true);v.setBigUint64(16,handle,true);v.setBigUint64(24,sequence,true);if(command===2){v.setBigUint64(32,128n<<20n,true);v.setUint32(40,format,true);v.setUint32(44,90,true);v.setFloat64(48,1,true);}return b;};
const nativePost=Worker.prototype.postMessage,requests=[];let failCleanup=0;const blockedSnapshots=new Set();let poisonPending;
Worker.prototype.postMessage=function(message,transfer){if(message.type==='geo.snapshot.execute'||message.type==='geo.snapshot.read'){if(blockedSnapshots.has(this))throw Error('snapshot transport deliberately unavailable');if(poisonPending?.worker===this){const w=poisonPending.owner,p=w.pending.get(message.requestId);check(p,'pending capture unavailable');w.pending.set(message.requestId,{...p,mutation:{bridge:Object.freeze({}),request:Uint8Array.of(0)}});poisonPending=undefined;}const v=new DataView(message.request),command=v.getUint32(8,true);if(command===3&&failCleanup){failCleanup--;throw Error('injected pre-Rust cleanup failure');}requests.push({worker:this,command,handle:v.getBigUint64(16,true),requestId:message.requestId,action:v.getUint32(48,true),nonce:v.getBigUint64(240,true)});}return nativePost.call(this,message,transfer);};
const workers=[],charts=[],outputs=[];
function newWorker(){const w=worker();workers.push(w);return w;}
function observe(w){const native=w.worker,receive=native.onmessage;let gate,latestSnapshot=0n,accepted=0n,reads=0;
 native.onmessage=event=>{const p=event.data?.value;if(p instanceof ArrayBuffer){const v=new DataView(p);if(p.byteLength===256&&v.getUint32(0,true)===0x5a475958&&v.getUint32(8,true)===16)accepted=v.getBigUint64(16,true);if(p.byteLength===256&&v.getUint32(0,true)===0x57475958&&v.getBigUint64(32,true)>0n){latestSnapshot=v.getBigUint64(16,true);if(gate?.kind==='mutation'){const g=gate;gate=undefined;g.entered.resolve();void g.release.promise.then(()=>{if(g.mode==='lost')receive.call(native,{data:{requestId:event.data.requestId,ok:false,error:{code:'XYG_GEO_RESOURCE_LIMIT',message:'forged resource rejection after actual Rust allocation'}}});else{if(g.mode==='corrupt')new DataView(p).setUint32(12,1,true);receive.call(native,event);}});return;}}
 if(v.getUint32(0,true)===0x58475958){reads++;if(gate?.kind==='read'){const g=gate;gate=undefined;g.entered.resolve();void g.release.promise.then(()=>receive.call(native,event));return;}}}receive.call(native,event);};
 return {native,get snapshot(){return latestSnapshot;},get accepted(){return accepted;},get reads(){return reads;},gate(kind='mutation',mode='hold'){gate={kind,mode,entered:deferred(),release:deferred()};return gate;}};
}
async function mount(w,callbacks){await w.ready;const fixture=await build(w),o=observe(w),el=host(),c=await XygGeographicChart.fromOverview({mode:'temporal-domain-overview',el,worker:w,index:fixture.index,query:fixture.query,sequence:7n,...(callbacks?{layer:callbacks}:{})});charts.push(c);await c.ready;await frame();return {fixture,o,el,c};}
try{
 window.__binaryStage='initial';a=newWorker();const x=await mount(a);chart=x.c;index=x.fixture.index;
 const count=()=>requests.filter(r=>r.worker===x.o.native&&r.command===6).length;
 await reject(chart.freezeBinary({budgetBytes:1}),'tiny framing accepted');check(count()===0&&chart.snapshot().sequence===7n,'local admission mutated accepted frame');
 await reject(chart.freezeBinary({budgetBytes:256}),'tiny Rust phase accepted');check(chart.snapshot().sequence===7n,'Rust admission changed accepted frame');
 const pre=new AbortController();pre.abort();const n=count();await reject(chart.freezeBinary({signal:pre.signal}),'preaborted freeze');check(count()===n,'preabort allocated');
 window.__binaryStage='pending update';const gate=x.o.gate(),freeze=chart.freezeBinary();await Promise.race([gate.entered.promise,freeze.then(()=>{throw Error("freeze completed before receipt gate");})]);let updated=false;const update=chart.update({...x.fixture.query,time:{kind:1,instant:10n},timeRevision:2n},{sequence:8n}).then(()=>{updated=true;});await new Promise(r=>setTimeout(r,30));check(!updated&&chart.snapshot().sequence===7n,'pending mutation published candidate');await frame();check(pixel(x.el).join(',')==='55,155,255,255','pending mutation changed old paint');gate.release.resolve();let frozen=await freeze;outputs.push(frozen);await update;check(frozen.kind==='xygx-v4'&&frozen.sequence===7n,'frozen publication changed');const v=new DataView(frozen.bytes.buffer,frozen.bytes.byteOffset);check(v.getBigInt64(56,true)===0n&&v.getBigUint64(384+128*8,true)===1n&&v.getBigUint64(384+143*8,true)===1n,'frozen time/counts changed to candidate');
 const readCount=x.o.reads;check(frozen.bytes===frozen.bytes&&x.o.reads===readCount,'getter consumed immutable read slots');let second=await a.geoSnapshotRead(snapshotRequest(20,x.o.snapshot));check(second.byteLength===frozen.bytes.byteLength,'second immutable slot failed');second=undefined;await reject(a.geoSnapshotRead(snapshotRequest(20,x.o.snapshot)),'third immutable read allowed');
 for(let format=0;format<6;format++){let code;try{await a.geoSnapshotExecute(snapshotRequest(2,x.o.snapshot,0n,format));}catch(e){code=e.code;}check(code==='XYG_GEO_SNAPSHOT_UNSUPPORTED_EXPORT','WASM artifact format silently supported');}
 failCleanup=1;await reject(frozen.dispose(),'cleanup pre-Rust failure missing');check(!frozen.closed,'failed cleanup marked closed');let unavailable=false;try{void frozen.bytes;}catch{unavailable=true;}check(unavailable,'dispose kept byte borrow visible');await frozen.dispose();check(frozen.closed,'cleanup retry did not complete');
 window.__binaryStage='quota';const held=[];for(let i=0;i<8;i++)held.push(await chart.freezeBinary());await reject(chart.freezeBinary(),'ninth snapshot allowed');check(chart.snapshot().sequence===8n,'snapshot capacity failure changed publication');for(const f of held)await f.dispose();
 window.__binaryStage='independent';for(const name of ['geoSnapshotExecute','geoSnapshotRead','geoScaleTransport','queueOwnedGeo','assertLive','allocateRequest','promiseFor'])a[name]=()=>{throw Error('mutable snapshot dispatch used');};frozen=await chart.freezeBinary();outputs.push(frozen);await index.dispose();x.fixture.pages.clear();await chart.dispose();await a.dispose();check(x.el.children.length===0&&frozen.bytes.length>2432,'source/index/controller/Worker disposal invalidated frozen binary');await frozen.dispose();
 window.__binaryStage='borrowed';const bw=newWorker(),canvas=document.createElement('canvas'),shell=host();canvas.width=800;canvas.height=600;shell.style.cssText='position:relative;width:800px;height:600px';shell.append(canvas);const gl=canvas.getContext('webgl2',{preserveDrawingBuffer:true,antialias:false});check(gl,'borrowed GL absent');layer=createMapLibreGeoLayer({id:'overview-binary'});layer.onAdd({getCanvas:()=>canvas,getContainer:()=>shell,triggerRepaint(){}},gl);let sets=0;const localLayer=layer,callbacks={setPrepared(p){sets++;localLayer.setPrepared(p);},releasePrepared(){localLayer.releasePrepared();}},borrow=await mount(bw,callbacks);callbacks.setPrepared=callbacks.releasePrepared=()=>{throw Error('mutable borrowed callback used');};const draw=()=>{gl.viewport(0,0,800,600);gl.clearColor(1,1,1,1);gl.clear(gl.COLOR_BUFFER_BIT);localLayer.render(gl,{});const b=new Uint8Array(4);gl.readPixels(160,600-284,1,1,gl.RGBA,gl.UNSIGNED_BYTE,b);return [...b];};check(draw().join(',')==='55,155,255,255','borrowed accepted paint');const bg=borrow.o.gate(),bf=borrow.c.freezeBinary();await Promise.race([bg.entered.promise,bf.then(()=>{throw Error('borrowed freeze missed gate');})]);const oldSets=sets;let bp=false;const bu=borrow.c.update({...borrow.fixture.query,time:{kind:1,instant:10n},timeRevision:2n},{sequence:8n}).then(()=>{bp=true;});await new Promise(r=>setTimeout(r,20));check(!bp&&sets===oldSets&&draw().join(',')==='55,155,255,255','borrowed publication skipped pin');bg.release.resolve();const binary=await bf;outputs.push(binary);await bu;await borrow.fixture.index.dispose();await borrow.c.dispose();check(!gl.isContextLost()&&canvas.width===800&&shell.contains(canvas)&&binary.bytes.length>2432,'borrowed cleanup invalidated binary or foreign canvas');await binary.dispose();layer.dispose();layer=undefined;
 window.__binaryStage='close read';b=newWorker();const y=await mount(b),readGate=y.o.gate('read');const creating=y.c.freezeBinary();await Promise.race([readGate.entered.promise,creating.then(()=>{throw Error("freeze completed before read gate");})]);let closed=false;const closing=y.c.dispose().then(()=>{closed=true;});await new Promise(r=>setTimeout(r,20));check(!closed&&y.el.children.length>0,'close skipped immutable read settlement');const ackCount=requests.filter(r=>r.worker===y.o.native&&r.command===3).length;readGate.release.resolve();await reject(creating,'close did not cancel outstanding freeze');await closing;check(requests.filter(r=>r.worker===y.o.native&&r.command===3).length===ackCount+1&&y.el.children.length===0,'close ACK or DOM cleanup mismatch');await y.fixture.index.dispose();
 window.__binaryStage='uncertain';for(const mode of ['lost','corrupt']){const w=newWorker(),z=await mount(w),bad=z.o.gate('mutation',mode),before=requests.filter(r=>r.worker===z.o.native&&r.command===6).length;const creation=z.c.freezeBinary();await bad.entered.promise;bad.release.resolve();let error;try{await creation;}catch(e){error=e;}check(error?.name==='GeoOverviewBinaryUncertainAllocation'&&error.owner,'unknown confirmation omitted issued recovery owner');await reject(z.c.freezeBinary(),'uncertain reallocated');await reject(z.c.update({...z.fixture.query,time:{kind:1,instant:10n},timeRevision:2n},{sequence:8n}),'uncertain published');check(z.c.snapshot().sequence===7n&&pixel(z.el).join(',')==='55,155,255,255','uncertain lost oldpaint');const recovery=error.owner.recover();check(recovery===error.owner.recover(),'recovery not coalesced');const output=await recovery;outputs.push(output);check(output.sequence===7n&&output.bytes.length>2432,'recovery did not freeze original snapshot');check(requests.filter(r=>r.worker===z.o.native&&r.command===6).length===before+2,'recovery allocated new birth instead of one exact replay');const births=requests.filter(r=>r.worker===z.o.native&&r.command===6).slice(-2);check(births[0].nonce===births[1].nonce&&births[0].handle===births[1].handle,'recovery changed birth identity');await z.c.update({...z.fixture.query,time:{kind:1,instant:10n},timeRevision:2n},{sequence:8n});await output.dispose();await z.c.dispose();await z.fixture.index.dispose();}
 window.__binaryStage='uncertain close';{const w=newWorker(),z=await mount(w),g=z.o.gate('mutation','lost'),p=z.c.freezeBinary();await g.entered.promise;g.release.resolve();await reject(p,'lost mutation accepted');await z.c.dispose();check(z.el.children.length===0,'controllerclose did not resolve exact birth before Data release');await z.fixture.index.dispose();}
 window.__binaryStage='lost retirement';{const w=newWorker(),z=await mount(w),output=await z.c.freezeBinary();outputs.push(output);const native=z.o.native,original=native.onmessage;let lost3=false,lost2=false;native.onmessage=event=>{const r=requests.find(r=>r.worker===native&&r.requestId===event.data?.requestId);if(event.data?.ok&&r&&(r.command===3&&!lost3||r.command===7&&r.action===2&&!lost2)){if(r.command===3)lost3=true;else lost2=true;original.call(native,{data:{requestId:event.data.requestId,ok:false,error:{code:'INJECTED_LOST_RETIREMENT',message:'actual retirement confirmation lost'}}});return;}original.call(native,event);};await reject(output.dispose(),'lost Release2 confirmation accepted');check(!output.closed&&lost3&&lost2,'lost cleanup did not retain known owner');await output.dispose();check(output.closed,'authority-free Release2 retry failed');native.onmessage=original;await z.c.dispose();await z.fixture.index.dispose();}
 window.__binaryStage='private dispatch';{const w=newWorker(),z=await mount(w);poisonPending={worker:z.o.native,owner:w};const output=await z.c.freezeBinary();check(output.sequence===7n&&output.bytes.length>2432,'public pending metadata retagged genuine outcome');await output.dispose();await z.c.dispose();await z.fixture.index.dispose();}
 window.__binaryStage='terminal decoration';{const w=newWorker(),z=await mount(w),g=z.o.gate('mutation','lost'),p=z.c.freezeBinary();await g.entered.promise;g.release.resolve();await reject(p,'lost mutation accepted');blockedSnapshots.add(z.o.native);w.disposed=true;await reject(z.c.dispose(),'mutable disposed decoration forged terminal authority');w.disposed=false;let fakeTerminate=0;z.o.native.terminate=()=>{fakeTerminate++;};await w.dispose();check(fakeTerminate===0,'public native terminate forged terminal marker');await z.c.dispose();check(z.el.children.length===0,'genuine termination did not allow local cleanup');blockedSnapshots.delete(z.o.native);}
 window.__binaryStage='foreign';const c=newWorker(),d=newWorker();const cc=await mount(c),dd=await mount(d);const original=c.worker;c.worker=d.worker;await reject(cc.c.freezeBinary(),'changed producer accepted snapshot');c.worker=original;await cc.c.dispose();await cc.fixture.index.dispose();await dd.c.dispose();await dd.fixture.index.dispose();
 window.__overviewBinary={ok:true,acceptedFrameBinary:true,pendingUpdateBarrier:true,borrowedPinAndCapturedCallbacks:true,exactOldTimeCounts:true,sourceIndexControllerDisposal:true,workerDisposalBinaryIndependent:true,repeatedBorrowNoRead:true,twoReadQuota:true,eightSnapshotCapacity:true,lowBudgetAtomic:true,capturedSnapshotDispatch:true,knownCleanupRetry:true,pendingReadCloseAck:true,lostCorruptGuard:true,noBlindReallocation:true,privateRequestIdOutcomeBinding:true,terminalDecorationCannotForge:true,exactSnapshotLocalReplay:true,confirmBeforeRead:true,lostRetirementConfirmation:true,controllerCloseRecovery:true,foreignProducerRejected:true,wasmArtifactFormats:'all-six-Unsupported',temporalExact:true,dataSpace:true,final:false};
}catch(error){window.__overviewBinary={ok:false,stage:window.__binaryStage,error:String(error),stack:error.stack};}
finally{Worker.prototype.postMessage=nativePost;for(const w of workers)try{await w.dispose();}catch{}for(const c of charts)try{await c.dispose();}catch{}for(const f of outputs)try{await f.dispose();}catch{}for(const e of containers)e.remove();}
