// Actual native executable/C ABI/wasm32 catalog processor, including metadata.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import test from 'node:test';import {fileURLToPath} from 'node:url';
import {decodeGeoCatalogResponse as decodeBrowserCatalog} from '../../xy-client/dist/index.js';
import {encodeGeoCatalogRequest,decodeGeoCatalogResponse,geoCatalogCompile} from '../src/geocatalog.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..');
const camera={crs:4326,centerX:0,centerY:0,zoom:0,width:800,height:600,worldWrap:true};
const points={geometry:1,crs:4326,xy:Float64Array.of(0,0,5,5),validity:Uint8Array.of(1,1,0),featureIds:BigUint64Array.of(0xffffffffffffffffn,0x8000000000000000n,17n)};
const line={geometry:2,crs:4326,xy:Float64Array.of(-5,0,5,0),validity:Uint8Array.of(1),featureIds:BigUint64Array.of(0xffffffffffffffffn),offsets0:Uint32Array.of(0,2)};
const polygon={geometry:3,crs:4326,xy:Float64Array.of(-5,-5,5,-5,5,5,-5,5,-5,-5),validity:Uint8Array.of(1),featureIds:BigUint64Array.of(0xffffffffffffffffn),offsets0:Uint32Array.of(0,1),offsets1:Uint32Array.of(0,5)};
function native(request,budget=128<<20){const r=spawnSync(process.env.XYG_GEO_CATALOG_NATIVE??path.join(root,'target/debug/geo_layers_conformance'),[String(budget)],{input:Buffer.from(request),maxBuffer:128<<20});if(r.error)throw r.error;return {status:r.status,bytes:new Uint8Array(r.stdout),error:r.stderr.toString().trim()};}
async function wasm(budget=128<<20){const{instance}=await WebAssembly.instantiate(fs.readFileSync(process.env.XYG_WASM_ARTIFACT??path.join(root,'packages/xy-client/dist/xyg-wasm.wasm')),{}),x=instance.exports,h=x.xyg_wasm_instance_new(budget);let sequence=0;return {run(request){assert.equal(x.xyg_wasm_arena_resize(h,request.byteLength),0);new Uint8Array(x.memory.buffer,x.xyg_wasm_arena_ptr(h)>>>0,request.byteLength).set(new Uint8Array(request));const status=x.xyg_wasm_geo_catalog_compile(h,++sequence,0,request.byteLength);assert.equal(x.xyg_wasm_arena_len(h),0);return {status,bytes:new Uint8Array(x.memory.buffer,x.xyg_wasm_output_ptr(h)>>>0,x.xyg_wasm_output_len(h)).slice(),error:new TextDecoder().decode(new Uint8Array(x.memory.buffer,x.xyg_wasm_last_error_ptr(h)>>>0,x.xyg_wasm_last_error_len(h)))};},dispose(){assert.equal(x.xyg_wasm_instance_dispose(h),0);}};}
function sceneSame(a,b){assert.equal(a.byteLength,b.byteLength);const aa=new Uint8Array(a).slice(),bb=new Uint8Array(b).slice(),av=new DataView(aa.buffer),bv=new DataView(bb.buffer);const count=Number(av.getBigUint64(16,true)),at=160+16*Number(av.getBigUint64(24,true));for(let i=0;i<count;i++)for(const o of[16,24,32,40]){const p=at+i*56+o,delta=Math.abs(av.getFloat64(p,true)-bv.getFloat64(p,true));assert.ok(delta<=1e-6,`record${i} delta${delta}`);av.setFloat64(p,0,true);bv.setFloat64(p,0,true);}assert.deepEqual(aa,bb);}
function same(a,b){const av=decodeGeoCatalogResponse(a.buffer.slice(a.byteOffset,a.byteOffset+a.byteLength)),bv=decodeGeoCatalogResponse(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength));sceneSame(av.scene,bv.scene);assert.deepEqual(av.styleOwners,bv.styleOwners);assert.deepEqual(av.rebuildKey,bv.rebuildKey);assert.deepEqual(av.focus,bv.focus);assert.deepEqual(av.hits,bv.hits);assert.equal(av.layers.length,bv.layers.length);for(let i=0;i<av.layers.length;i++){const x={...av.layers[i]},y={...bv.layers[i]};if(x.bounds){for(let j=0;j<4;j++)assert.ok(Math.abs(x.bounds[j]-y.bounds[j])<=1e-6);x.bounds=y.bounds=null;}assert.deepEqual(x,y);}return bv;}
for(const kind of[1,2,3,4,5,6,7])test(`catalog kind${kind} actual native/C ABI/wasm32`,async()=>{const w=await wasm();try{const source=kind===3||kind===4?line:kind===5||kind===6?polygon:points,layer={layerId:0xffffffffffffffffn,kind,source,style:{fill:Uint8Array.of(255,0,0,255),strokeWidth:kind===3||kind===4?2:0},legendLabel:'δοκιμή'};if(kind===2||kind===6){layer.values=kind===2?Float64Array.of(0,1,NaN):Float64Array.of(1);layer.valueDomain=[0,2];layer.colorStops=Uint8Array.of(0,0,255,255,0,0);}if(kind===7)layer.density={columns:2,rows:2};if(kind===4)layer.arc={bend:.25,steps:8};const req=encodeGeoCatalogRequest({camera,layers:[layer],legend:{title:'Layers',location:0,fontSize:12}}),n=native(req),b=w.run(req);assert.equal(n.status,0,n.error);assert.equal(b.status,0,b.error);const out=same(n.bytes,b.bytes);assert.deepEqual(new Uint8Array(geoCatalogCompile(req)),n.bytes);assert.deepEqual(out.layers[0].featureIds,source.featureIds);assert.deepEqual(out.layers[0].validity,source.validity);assert.ok(out.layers[0].visibleFeatureIndices.length>0);if(kind===7){assert.deepEqual([...out.layers[0].density.featureIndices].sort(),[0,1]);assert.equal(out.layers[0].droppedChannels,7);}}finally{w.dispose();}});
test('layer ownership/full u64 and hidden/null source rows',async()=>{const w=await wasm();try{const req=encodeGeoCatalogRequest({camera,layers:[{layerId:1n,kind:1,source:points,stateFlags:Uint8Array.of(1,2,4),selected:{fill:Uint8Array.of(0,255,0,255)}},{layerId:2n,kind:1,source:points}]});const n=native(req),b=w.run(req);assert.equal(n.status,0,n.error);assert.equal(b.status,0,b.error);const out=same(n.bytes,b.bytes);assert.deepEqual([...out.layers[0].visibleFeatureIndices],[1]);assert.deepEqual([...out.layers[0].stateFlags],[1,2,4]);assert.ok(out.styleOwners.includes(0)&&out.styleOwners.includes(1));assert.deepEqual(out.layers[1].featureIds,points.featureIds);}finally{w.dispose();}});
test('malformed/reserved/padding/overflow/resource fail closed then recovery',async()=>{const w=await wasm();try{const req=encodeGeoCatalogRequest({camera,layers:[{layerId:1n,kind:1,source:points}]});for(const mutate of[b=>b[96]=1,b=>b[128+328]=1,b=>b[128+16]=64,b=>b[512+20]=1,b=>new DataView(b.buffer).setBigUint64(392,0xffffffffffffffffn,true),b=>new DataView(b.buffer).setFloat64(24,NaN,true)]){const bad=new Uint8Array(req.slice(0));mutate(bad);const n=native(bad),b=w.run(bad.buffer);assert.notEqual(n.status,0);assert.equal(n.status,b.status);assert.equal(n.error,b.error);assert.equal(b.bytes.length,0);}assert.equal(native(req,65536).status,3);const b=w.run(req);assert.equal(b.status,0,b.error);const out=b.bytes;for(const at of[96,127]){const bad=out.slice();bad[at]=1;assert.throws(()=>decodeGeoCatalogResponse(bad.buffer),TypeError);}assert.throws(()=>decodeGeoCatalogResponse(new Uint8Array([...out,0]).buffer),TypeError);}finally{w.dispose();}});
test('typed framing allocates one packet and preserves full source buffers',()=>{const ArrayType=globalThis.ArrayBuffer;let allocations=0;globalThis.ArrayBuffer=class extends ArrayType{constructor(n){super(n);allocations++;}};try{const req=encodeGeoCatalogRequest({camera,layers:[{layerId:1n,kind:1,source:points}]});assert.equal(allocations,1);assert.equal(new Uint8Array(req)[0],88);assert.equal(points.xy.byteLength,32);assert.equal(points.featureIds[0],0xffffffffffffffffn);}finally{globalThis.ArrayBuffer=ArrayType;}assert.throws(()=>encodeGeoCatalogRequest({camera:{...camera,worldWrap:'false'},layers:[]}),TypeError);assert.throws(()=>encodeGeoCatalogRequest({camera,layers:[{layerId:1n,kind:1,source:{...points,xy:new Float32Array(6)}}]}),TypeError);});
test('native pre-copy failure does not allocate size-query state',()=>{const T=globalThis.BigUint64Array;globalThis.BigUint64Array=class{constructor(){throw new Error('allocator must not run');}};try{assert.throws(()=>geoCatalogCompile(new ArrayBuffer(65537),65536),e=>e.nativeCode===-9);assert.throws(()=>geoCatalogCompile(new ArrayBuffer(1)),e=>e.nativeCode===-1);}finally{globalThis.BigUint64Array=T;}});
for(const event of[{operation:1,coordinates:[400,300]},{operation:2,coordinates:[400,300]},{operation:3,coordinates:[390,290,410,310]},{operation:4},{operation:5,delta:1},{operation:6,layerId:1n,featureId:0xffffffffffffffffn},{operation:7,layerId:1n,featureId:0xffffffffffffffffn,mode:2}])test(`catalog interaction${event.operation} native/C ABI/wasm32`,async()=>{const w=await wasm();try{const source={...points,xy:Float64Array.of(0,0,0,0),featureIds:BigUint64Array.of(0xffffffffffffffffn,0xffffffffffffffffn,17n)},req=encodeGeoCatalogRequest({camera,layers:[{layerId:1n,kind:1,source}],event}),n=native(req),b=w.run(req);assert.equal(n.status,0,n.error);assert.equal(b.status,0,b.error);const out=same(n.bytes,b.bytes);assert.deepEqual(new Uint8Array(geoCatalogCompile(req)),n.bytes);if(event.operation!==4){assert.equal(out.hits[0].featureId,0xffffffffffffffffn);assert.deepEqual([...out.hits[0].featureIndices],[0,1]);}if(event.operation===5||event.operation===6){assert.equal(out.focus.featureId,0xffffffffffffffffn);assert.deepEqual([...out.layers[0].stateFlags],[8,8,0]);}if(event.operation===2||event.operation===3||event.operation===7)assert.deepEqual([...out.layers[0].stateFlags],[2,2,0]);}finally{w.dispose();}});
test('compile-only canonical focus survives camera snapshots',async()=>{const w=await wasm();try{for(const zoom of[0,2]){const req=encodeGeoCatalogRequest({camera:{...camera,zoom},layers:[{layerId:1n,kind:1,source:points,stateFlags:Uint8Array.of(8,8,8)}]}),n=native(req),b=w.run(req);assert.equal(n.status,0,n.error);assert.equal(b.status,0,b.error);const out=same(n.bytes,b.bytes);assert.deepEqual(new Uint8Array(geoCatalogCompile(req)),n.bytes);assert.deepEqual(out.focus,{layerId:1n,featureId:0xffffffffffffffffn});assert.deepEqual([...out.layers[0].stateFlags],[8,0,0]);assert.deepEqual(out.hits,[]);}}finally{w.dispose();}});

test('MultiPoint density counts vertices and deduplicates source rows in all public decoders',async()=>{
 const w=await wasm();try{
 const source={geometry:4,crs:4326,xy:Float64Array.of(0,0,0,0),validity:Uint8Array.of(1),featureIds:BigUint64Array.of(0xffffffffffffffffn),offsets0:Uint32Array.of(0,2)};
 const request=encodeGeoCatalogRequest({camera,layers:[{layerId:9n,kind:7,source,density:{columns:1,rows:1}}]}),n=native(request),b=w.run(request);
 assert.equal(n.status,0,n.error);assert.equal(b.status,0,b.error);const out=same(n.bytes,b.bytes);
 assert.deepEqual(new Uint8Array(geoCatalogCompile(request)),n.bytes);
 for(const decoded of[out,decodeBrowserCatalog(b.bytes.buffer)]) {const d=decoded.layers[0].density;assert.deepEqual([...d.counts],[2]);assert.deepEqual([...d.offsets],[0,1]);assert.deepEqual([...d.featureIndices],[0]);assert.equal(decoded.layers[0].featureIds[0],0xffffffffffffffffn);}
 }finally{w.dispose();}
});
