// Actual native and packaged wasm32 hierarchy transport, no host geometry policy.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {RetainedGeoSource} from '../src/geo-retained.js';
import {GeoHierarchy,GeoHierarchyFallback,isHierarchyFrame} from '../src/geo-hierarchy.js';
import {decodeGeoHierarchyReply,encodeGeoHierarchyRequest} from '../src/geo-hierarchy-wire.js';
import {nativeGeoScaleBridge,encodeGeoScaleStyle} from '../src/geoscale.js';
import {fixture,budget,U64,I64} from './geoscale-fixture.mjs';
const style=()=>encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0});
function query(info){return {camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:0,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:32768,previousDirect:true,sourceDigest:info.digest,generation:info.generation,layerId:U64,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:1,instant:I64},maxProjectedVertices:1000000n};}
async function setup(bridge){const raw=await fixture(bridge),chunk=Uint8Array.from(Buffer.from(raw.chunk,'hex')),manifest=Uint8Array.from(Buffer.from(raw.manifest,'hex'));const source=await RetainedGeoSource.create(manifest,()=>chunk,{budget,bridge});return{source,frame:await source.update(query(source.info),{sequence:1n,style:style()})};}
function storage(pages){return {grid:1024,maxVertices:1000000n,maxWriteBytes:64n<<20n,readPage:t=>pages.get(`${t.namespace}:${t.page}`),writePage:(t,b)=>pages.set(`${t.namespace}:${t.page}`,b.slice())};}
const packets=[];
for(const name of['native','wasm']){
 test(`${name} hierarchy exact Scene, independent frame/Rows/retain after disposal`,async()=>{
  const holder=await bridgeFor(name),{source,frame:old}=await setup(holder.bridge);let index,frame,retained;
  try{index=await GeoHierarchy.fromFrame(old,source,storage(new Map()));await source.dispose();frame=await index.update(query(index.info),{sequence:2n,style:style()});assert.deepEqual(frame.data.scene,old.data.scene);assert.equal(frame.data.record(0).featureId,U64);assert.equal(frame._source,source);assert.equal(frame.hierarchyStats.passes,1);assert.equal(isHierarchyFrame(frame),true);assert.equal(isHierarchyFrame(old),false);retained=await frame.retain();assert.equal(isHierarchyFrame(retained),true);await index.dispose();await frame.dispose();const rows=await retained.rows();try{assert.equal(rows.data.record(0).featureId,U64);const stable=new Uint8Array(rows.data.packet.slice(0));stable.fill(0,16,24);packets.push({host:name,kind:'rows',hash:createHash('sha256').update(stable).digest('hex')});}finally{await rows.dispose();}const hit=await retained.pick({style:style(),x:400,y:300,tolerance:0,mode:0,maxHits:4});assert.equal(hit.data.count,1n);await hit.dispose();packets.push({host:name,kind:'scene',hash:createHash('sha256').update(retained.data.scene).digest('hex')});}
  finally{if(retained)await retained.dispose();if(frame)await frame.dispose();if(index)await index.dispose();await old.dispose();await source.dispose();holder.dispose();}
 });
 test(`${name} mutated callback authority settles exact ACK and failed query retains old frame`,async()=>{
  const holder=await bridgeFor(name),{source,frame:old}=await setup(holder.bridge);let index,frame;const pages=new Map();let corrupt=false;
  try{await assert.rejects(GeoHierarchy.fromFrame(old,source,{...storage(pages),writePage:(t,b)=>{t.raw.fill(0);t.namespace=0n;t.encodedBytes*=2;throw new Error('write failed');}}),/write failed/);index=await GeoHierarchy.fromFrame(old,source,{...storage(pages),readPage:t=>{const bytes=pages.get(`${t.namespace}:${t.page}`);if(corrupt){t.raw.fill(0);t.encodedBytes*=2;return new Uint8Array(bytes.length*2);}return bytes;}});frame=await index.update(query(index.info),{sequence:2n,style:style()});corrupt=true;await assert.rejects(index.update(query(index.info),{sequence:3n,style:style()}),/bounded/);assert.equal(index.current,frame);assert.equal(frame.data.record(0).featureId,U64);corrupt=false;const recovery=await index.update(query(index.info),{sequence:4n,style:style()});await recovery.dispose();}
  finally{if(frame)await frame.dispose();if(index)await index.dispose();await old.dispose();await source.dispose();holder.dispose();}
 });
 test(`${name} cancel pending write awaits callback settlement and exact private ACK`,async()=>{
  const holder=await bridgeFor(name),{source,frame:old}=await setup(holder.bridge);const controller=new AbortController();let enter,release;const started=new Promise(r=>enter=r),gate=new Promise(r=>release=r);const pending=GeoHierarchy.fromFrame(old,source,{...storage(new Map()),signal:controller.signal,writePage:async(t,b)=>{t.kind=1;t.raw.fill(0);enter();await gate;}});
  try{await Promise.race([started,pending.then(()=>{throw new Error('write not entered');})]);controller.abort();let settled=false;pending.then(()=>settled=true,()=>settled=true);await new Promise(r=>setTimeout(r,10));assert.equal(settled,false);release();await assert.rejects(pending,/abort|cancel/i);assert.equal(old.data.record(0).featureId,U64);const index=await GeoHierarchy.fromFrame(old,source,storage(new Map()));await index.dispose();}
  finally{release();await pending.catch(()=>{});await old.dispose();await source.dispose();holder.dispose();}
 });
 test(`${name} local budget/forged ticket rejects and exact fallback retains current frame`,async()=>{
  const holder=await bridgeFor(name),{source,frame:old}=await setup(holder.bridge);let index,frame;
  try{source.budget.maxChunks=1;index=await GeoHierarchy.fromFrame(old,source,storage(new Map()));await assert.rejects(index.update(query(index.info),{sequence:2n,style:style()}),e=>e instanceof GeoHierarchyFallback&&e.reasonCode===2);assert.equal(source.current,old);assert.equal(old.data.record(0).featureId,U64);await assert.rejects(holder.bridge.execute(encodeGeoHierarchyRequest({command:37,handle:old.handle,sequence:1n,budget:{...budget,processorBytes:4096},payload:new Uint8Array(24)})));}
  finally{if(frame)await frame.dispose();if(index)await index.dispose();await old.dispose();await source.dispose();holder.dispose();}
 });
}
async function bridgeFor(name){if(name==='native')return{bridge:nativeGeoScaleBridge(budget.processorBytes),dispose(){}};const file=process.env.XYG_HIERARCHY_WASM??'../../xy-client/dist/xyg-wasm.wasm';const {instance}=await WebAssembly.instantiate(await readFile(file),{}),x=instance.exports,id=x.xyg_wasm_instance_new(budget.processorBytes);assert.ok(id);let sequence=0;async function call(request,read){assert.equal(x.xyg_wasm_arena_resize(id,request.byteLength),0);new Uint8Array(x.memory.buffer,x.xyg_wasm_arena_ptr(id)>>>0,request.byteLength).set(new Uint8Array(request));const status=x[read?'xyg_wasm_geo_scale_read':'xyg_wasm_geo_scale_execute'](id,++sequence,0,request.byteLength);if(status){const error=new Error(`WASM ${status}: `+new TextDecoder().decode(new Uint8Array(x.memory.buffer,x.xyg_wasm_last_error_ptr(id)>>>0,x.xyg_wasm_last_error_len(id))));error.nativeCode=status===3?-9:status;error.wasmStatus=status;throw error;}return new Uint8Array(x.memory.buffer,x.xyg_wasm_output_ptr(id)>>>0,x.xyg_wasm_output_len(id)).slice().buffer;}return{bridge:{execute:r=>call(r,false),read:r=>call(r,true)},dispose(){assert.equal(x.xyg_wasm_instance_dispose(id),0);}};}
test('strict hierarchy reply parser rejects reserved bytes and native/wasm packets match',async()=>{const b=new ArrayBuffer(256),v=new DataView(b);new Uint8Array(b).set([88,89,71,90]);v.setUint32(4,1,true);v.setUint32(8,18,true);v.setBigUint64(16,1n,true);v.setBigUint64(24,U64,true);v.setBigUint64(48,1n,true);assert.equal(decodeGeoHierarchyReply(b).sequence,U64);new Uint8Array(b)[200]=1;assert.throws(()=>decodeGeoHierarchyReply(b),/reserved/);for(const kind of['scene','rows'])assert.equal(packets.find(p=>p.host==='native'&&p.kind===kind).hash,packets.find(p=>p.host==='wasm'&&p.kind===kind).hash);if(process.env.XYG_HIERARCHY_HOST_REPORT)await writeFile(process.env.XYG_HIERARCHY_HOST_REPORT,JSON.stringify({status:'passed',packets,claims:['actual native and packaged wasm32 thin hierarchy driver','exact Scene/Rows IDs and immutable lifetime','cancelled callback settlement/private ACK','mutation/backing budget rejection and old-frame recovery'],limitations:['no selected hierarchy','no massive host latency or browser paint claim']},null,2)+'\n');});
