import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture,budget as base,U64} from './geoscale-fixture.mjs';
import {nativeGeoScaleBridge,geoScaleExecute,encodeGeoScaleRequest as encode,decodeGeoScaleReply as decode,driveGeoSession,prepareGeoSceneData,encodeGeoScaleStyle,withGeoNativeMemberDataOutcome} from '../src/geoscale.js';
import {GeoOverviewIndex} from '../src/geo-overview-source.js';
import {encodeOverviewMembersRequest as request,decodeOverviewMembersReply as reply} from '../src/geo-overview-members.js';
// The existing ABI tracer throws AFTER the actual CABI call, simulating lost
// confirmation without replacing the genuinely issued producer with a wrapper.
await import('../src/native.js');
const { _testConfigureGeneratedAbiTrace }=await import('../src/_abi_generated.js');
let afterCall;
_testConfigureGeneratedAbiTrace(event=>{if(event.symbol==='xyg_geo_scale_execute'&&event.outcome==='ok'&&afterCall){const action=afterCall;afterCall=undefined;action();}});
const budget={...base,pageRows:1};
async function setup(wrapped=false){const actual=nativeGeoScaleBridge(budget.processorBytes),bridge=wrapped?{execute:b=>actual.execute(b),read:actual.read}:actual,raw=await fixture(bridge),chunk=Uint8Array.from(Buffer.from(raw.chunk,'hex')),manifest=Uint8Array.from(Buffer.from(raw.manifest,'hex')),source=decode(await bridge.execute(encode({command:4,budget,payload:manifest}))).handle,readChunk=async()=>chunk,info=(await driveGeoSession(bridge,{handle:source,sequence:0n,budget,readChunk})).source;
const q={camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:0,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:32768,previousDirect:true,sourceDigest:info.digest,generation:info.generation,layerId:U64,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:0},maxProjectedVertices:1000000n};await bridge.execute(encode({command:5,handle:source,sequence:1n,budget,query:q}));await driveGeoSession(bridge,{handle:source,sequence:1n,budget,readChunk});const seed=await prepareGeoSceneData(bridge,{handle:source,sequence:1n,budget,style:encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0})}),storage=new Map(),index=await GeoOverviewIndex.fromFrame(seed,{bridge,budget,maxVertices:1000000n,readChunk,readPage:async t=>storage.get(`${t.namespace}:${t.page}`),writePage:async(t,b)=>storage.set(`${t.namespace}:${t.page}`,b.slice())});q.maxCells=0;q.previousDirect=false;q.maxProjectedVertices=0n;const frame=await index.update(q,{sequence:2n}),page=await frame.members(136,{sequence:10n,maxVertices:1000000n});return {bridge,source,seed,index,frame,page,async gone(){await frame.dispose();await index.dispose();await seed.dispose();await bridge.execute(encode({command:10,handle:source}));},async close(){afterCall=undefined;await page.dispose();await frame.dispose();await index.dispose();await seed.dispose();try{await bridge.execute(encode({command:10,handle:source}));}catch{}}};}

test('actual native lost MemberData10 closes via original sequence after every producer is gone',async()=>{const f=await setup();try{const handle=f.page.handle,seq=f.page.sequence;await f.gone();afterCall=()=>{throw Error('lost successful10');};await assert.rejects(f.page.dispose(),/lost successful10/);assert.throws(()=>f.page.record(0),/disposed/);await f.page.dispose();await f.page.dispose();await assert.rejects(geoScaleExecute(request(6,handle,seq)),e=>e.nativeCode===-10||e.code===-10);}finally{await f.close();}});

test('wrong-sequence genuine error and fake public SourceStale never authorize original liveData',async()=>{const f=await setup();try{let saved;try{await geoScaleExecute(request(6,f.page.handle,f.page.sequence+1n));}catch(e){saved=e;}assert.ok(saved);const probe=request(6,f.page.handle,f.page.sequence);for(const e of [saved,Object.assign(Error('XYG_GEO_SOURCE_STALE'),{nativeCode:-10,status:-10})]){await withGeoNativeMemberDataOutcome(f.bridge,probe,async outcome=>{const live=await geoScaleExecute(probe.slice(0));assert.equal(reply(live).sourceHandle,f.page.handle);assert.equal(outcome(e),undefined);assert.ok(outcome(live)?.reply);},geoScaleExecute);}}finally{await f.close();}});

test('native exact clone newer dispatch invalidates earlier genuine wrong-sequence error',async()=>{const f=await setup();try{const probe=request(6,f.page.handle,f.page.sequence+1n);await withGeoNativeMemberDataOutcome(f.bridge,probe,async outcome=>{let first;try{await geoScaleExecute(probe.slice(0));}catch(e){first=e;}assert.equal(outcome(first)?.status,-10);let second;try{await geoScaleExecute(probe.slice(0));}catch(e){second=e;}assert.equal(outcome(first),undefined);assert.equal(outcome(second)?.status,-10);},geoScaleExecute);}finally{await f.close();}});

test('generic wrapped native producer remains guarded after lost actual10',async()=>{const f=await setup(true);try{afterCall=()=>{throw Error('lost actual10');};await assert.rejects(f.page.dispose(),/lost actual10/);await assert.rejects(f.page.dispose(),e=>e.nativeCode===-10);assert.throws(()=>f.page.record(0),/disposed/); // explicit guard: no guessed generic Stale cleanup
}finally{afterCall=undefined;await f.frame.dispose();await f.index.dispose();await f.seed.dispose();await f.bridge.execute(encode({command:10,handle:f.source}));}});

test('member probe shares the existing16 active contexts and finally refunds capacity',async()=>{const f=await setup();try{const probe=request(6,f.page.handle,f.page.sequence);let release;const gate=new Promise(r=>release=r),entered=[];const flights=Array.from({length:16},()=>withGeoNativeMemberDataOutcome(f.bridge,probe,async()=>{entered.push(1);await gate;},geoScaleExecute));assert.equal(entered.length,16);await assert.rejects(withGeoNativeMemberDataOutcome(f.bridge,probe,async()=>{},geoScaleExecute),/capacity/);release();await Promise.all(flights);await withGeoNativeMemberDataOutcome(f.bridge,probe,async outcome=>assert.ok(outcome(await geoScaleExecute(probe.slice(0)))?.reply),geoScaleExecute);}finally{await f.close();}});
