import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {budget as base,U64,I64} from './geoscale-fixture.mjs';
import {nativeGeoScaleBridge,encodeGeoScaleRequest as encode,decodeGeoScaleReply as decode,encodeGeoChunkRequest,encodeGeoScaleStyle,driveGeoSession,prepareGeoSceneData} from '../src/geoscale.js';
import {GeoOverviewIndex} from '../src/geo-overview-source.js';
import {encodeOverviewMembersRequest as request,decodeOverviewMembersReply as reply,GeoOverviewMembershipUncertain,GeoOverviewMembershipCleanupPending,GeoOverviewMembershipPublicationPending} from '../src/geo-overview-members.js';
const budget={...base,pageRows:1},packets=new Map(),recoveryPackets=new Map();
async function transport(host){if(host==='native')return {bridge:nativeGeoScaleBridge(budget.processorBytes),dispose(){}};const {instance}=await WebAssembly.instantiate(await readFile(process.env.XYG_GEO_OVERVIEW_WASM),{}),x=instance.exports,id=x.xyg_wasm_instance_new(budget.processorBytes);assert.ok(id);let seq=0;async function call(b,read){assert.equal(x.xyg_wasm_arena_resize(id,b.byteLength),0);new Uint8Array(x.memory.buffer,x.xyg_wasm_arena_ptr(id)>>>0,b.byteLength).set(new Uint8Array(b));const status=x[read?'xyg_wasm_geo_scale_read':'xyg_wasm_geo_scale_execute'](id,++seq,0,b.byteLength);if(status)throw Error(new TextDecoder().decode(new Uint8Array(x.memory.buffer,x.xyg_wasm_last_error_ptr(id)>>>0,x.xyg_wasm_last_error_len(id))));return new Uint8Array(x.memory.buffer,x.xyg_wasm_output_ptr(id)>>>0,x.xyg_wasm_output_len(id)).slice().buffer;}return {bridge:{execute:b=>call(b,false),read:b=>call(b,true)},dispose(){assert.equal(x.xyg_wasm_instance_dispose(id),0);}};}
async function setup(host){const holder=await transport(host),actual=holder.bridge.execute,control={execute:actual,read:holder.bridge.read,reader:async()=>chunk},bridge={execute:b=>control.execute(b),read:b=>control.read(b)};const descriptor=new Uint8Array(216),v=new DataView(descriptor.buffer);descriptor.set([88,89,71,68]);[1,4,4326,1,0].forEach((n,i)=>v.setUint32(4+i*4,n,true));[5n,5n,6n,0n,0n].forEach((n,i)=>v.setBigUint64(24+i*8,n,true));[0,0,0,0,-90,0,90,0,0,0].forEach((n,i)=>v.setFloat64(64+i*8,n,true));descriptor.set([1,1,1,0,1],144);[U64,9007199254740993n,7n,7n,U64].forEach((n,i)=>v.setBigUint64(152+i*8,n,true));[0,2,3,4,4,5].forEach((n,i)=>v.setUint32(192+i*4,n,true));const chunk=await bridge.read(encodeGeoChunkRequest({descriptor,rows:5,intervals:{starts:BigInt64Array.of(I64,0n,10n,0n,I64),ends:BigInt64Array.of(0n,10n,0n,0n,0n),startValidity:Uint8Array.of(0,1,1,0,0),endValidity:Uint8Array.of(1,1,0,0,1)}},budget.processorBytes));
const builder=decode(await bridge.execute(encode({command:1}))).handle;for(let i=0;i<2;i++)await bridge.execute(encode({command:2,handle:builder,payload:new Uint8Array(chunk)}));await bridge.execute(encode({command:3,handle:builder,generation:U64}));const manifest=await bridge.read(encode({command:21,handle:builder})),source=decode(await bridge.execute(encode({command:4,budget,payload:new Uint8Array(manifest)}))).handle;await bridge.execute(encode({command:10,handle:builder}));const readChunk=(t,s)=>control.reader(t,s),info=(await driveGeoSession(bridge,{handle:source,sequence:0n,budget,readChunk})).source;const q={camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:0,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:32768,previousDirect:true,sourceDigest:info.digest,generation:U64,layerId:U64,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:0},maxProjectedVertices:1000n};await bridge.execute(encode({command:5,handle:source,sequence:1n,budget,query:q}));await driveGeoSession(bridge,{handle:source,sequence:1n,budget,readChunk});const seed=await prepareGeoSceneData(bridge,{handle:source,sequence:1n,budget,style:encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0})});const pages=new Map(),index=await GeoOverviewIndex.fromFrame(seed,{bridge,budget,maxVertices:1000n,readChunk,readPage:async t=>pages.get(`${t.namespace}:${t.page}`),writePage:async(t,b)=>pages.set(`${t.namespace}:${t.page}`,b.slice())});q.maxCells=0;q.previousDirect=false;q.maxProjectedVertices=0n;
return {holder,bridge,actual,actualRead:holder.bridge.read,control,chunk,index,source,seed,q,async close(){control.execute=actual;await index.dispose();await seed.dispose();await bridge.execute(encode({command:10,handle:source}));holder.dispose();}};}

for(const host of process.env.XYG_GEO_OVERVIEW_WASM?['native','wasm']:['native']){
for(const corrupt of [false,true])test(`${host}: exact45 replay survives parent disposal and does not invent a Query`,async()=>{const f=await setup(host);let frame,page,guard;const calls=[],births=[];let fail=true;try{frame=await f.index.update(f.q,{sequence:2n});f.control.execute=async b=>{const bytes=new Uint8Array(b).slice(),v=new DataView(bytes.buffer),r=await f.actual(b);if(v.getUint32(8,true)===45){calls.push(bytes);births.push(reply(r).handle);assert.ok(v.getBigUint64(240,true)>0n);if(fail){fail=false;if(corrupt)return new ArrayBuffer(256);throw Error('lost successful45');}}return r;};await assert.rejects(frame.members(136,{sequence:10n,maxVertices:1000n}),e=>{guard=e.owner;return e instanceof GeoOverviewMembershipUncertain;});await frame.dispose();frame=undefined;await f.index.dispose();await f.seed.dispose();await f.bridge.execute(encode({command:10,handle:f.source}));page=await guard.recover();assert.equal(page.record(0).featureId,U64);const normalized=page.copyBytes();normalized.fill(0,16,24);recoveryPackets.set(`${host}:${corrupt}`,Buffer.from(normalized).toString('hex'));assert.equal(calls.length,2);assert.deepEqual(calls[0],calls[1]);assert.equal(births[0],births[1]);await assert.rejects(guard.recover(),/closed/);await page.dispose();page=undefined;f.holder.dispose();}finally{if(page)await page.dispose();if(guard)await guard.dispose();if(frame){await frame.dispose();await f.close();}}});
test(`${host}: lost successfulConfirm retries47 before any IO, with whole recovery singleflight`,async()=>{const f=await setup(host),frame=await f.index.update(f.q,{sequence:2n});let fail=true,guard,page;const calls=[];try{f.control.execute=async b=>{const v=new DataView(b),c=v.getUint32(8,true),action=c===47?v.getUint32(260,true):0;calls.push(c);const r=await f.actual(b);if(c===47&&action===0&&fail){fail=false;throw Error('lost Confirm');}return r;};await assert.rejects(frame.members(136,{sequence:10n,maxVertices:1000n}),e=>{guard=e.owner;return e instanceof GeoOverviewMembershipUncertain;});assert.equal(calls.includes(6),false);const first=guard.recover(),second=guard.recover();assert.equal(first,second);page=await first;assert.equal(calls.filter(c=>c===45).length,1);assert.deepEqual(calls.slice(0,3),[45,47,47]);assert.equal(frame.data.count(136),6n);}finally{if(page)await page.dispose();if(guard)await guard.dispose();await frame.dispose();await f.close();}});
test(`${host}: lost Query10 exact retirement blocks higher nonce until cleanup; MemberData survives`,async()=>{const f=await setup(host),frame=await f.index.update(f.q,{sequence:2n});let guard,page,lose45=true,lose10=false;try{f.control.execute=async b=>{const c=new DataView(b).getUint32(8,true),r=await f.actual(b);if(c===45&&lose45){lose45=false;throw Error('lost45');}if(c===10&&lose10){lose10=false;throw Error('lost Query10');}return r;};await assert.rejects(frame.members(136,{sequence:10n,maxVertices:1000n}),e=>{guard=e.owner;return e instanceof GeoOverviewMembershipUncertain;});await guard.admit();lose10=true;await assert.rejects(guard.dispose(),/lost Query10/);await assert.rejects(frame.members(136,{sequence:11n,maxVertices:1000n}),e=>e.owner===guard);await guard.dispose();assert.equal(guard.closed,true);page=await frame.members(136,{sequence:11n,maxVertices:1000n});assert.equal(page.record(0).featureId,U64);assert.equal(frame.data.count(136),6n);}finally{if(page)await page.dispose();if(guard)await guard.dispose();await frame.dispose();await f.close();}});
}

for(const host of process.env.XYG_GEO_OVERVIEW_WASM?['native','wasm']:['native'])test(`${host}: recovery coalesces callbacks and closing holds loan until exactACK`,async()=>{const f=await setup(host),frame=await f.index.update(f.q,{sequence:2n});let guard,fail=true,entered,release;const at=new Promise(r=>entered=r),gate=new Promise(r=>release=r),events=[];try{f.control.execute=async b=>{const c=new DataView(b).getUint32(8,true),r=await f.actual(b);if(c===45&&fail){fail=false;throw Error('lost45');}if(c===8)events.push('ack');return r;};await assert.rejects(frame.members(136,{sequence:10n,maxVertices:1000n}),e=>{guard=e.owner;return e instanceof GeoOverviewMembershipUncertain;});f.control.reader=async()=>{events.push('read');entered();await gate;events.push('settled');return f.chunk;};const first=guard.recover(),second=guard.recover();assert.equal(first,second);const results=Promise.allSettled([first,second]);await at;let closed=false;const closing=guard.dispose().then(()=>closed=true);await new Promise(r=>setImmediate(r));assert.equal(closed,false);assert.deepEqual(events,['read']);release();assert.ok((await results).every(r=>r.status==='rejected'));await closing;assert.deepEqual(events,['read','settled','ack']);assert.equal(guard.closed,true);assert.equal(frame.data.count(136),6n);}finally{release?.();if(guard)await guard.dispose();await frame.dispose();await f.close();}});

for(const host of process.env.XYG_GEO_OVERVIEW_WASM?['native','wasm']:['native']){
test(`${host}: consumed45 release rejection keeps convertedData cleanup retryable`,async()=>{const f=await setup(host),frame=await f.index.update(f.q,{sequence:2n});let guard,fail45=true,fail2=true,page;try{f.control.execute=async b=>{const v=new DataView(b),c=v.getUint32(8,true),action=c===47?v.getUint32(260,true):0;if(c===47&&action===2&&fail2){fail2=false;throw Error('ReleaseBirth rejected beforeRust');}const r=await f.actual(b);if(c===45&&fail45){fail45=false;throw Error('lost45');}return r;};await assert.rejects(frame.members(136,{sequence:10n,maxVertices:1000n}),e=>{guard=e.owner;return e instanceof GeoOverviewMembershipUncertain;});await assert.rejects(guard.recover(),/ReleaseBirth/);page=await guard.recover();assert.equal(page.record(0).featureId,U64);assert.equal(frame.data.count(136),6n);}finally{if(page)await page.dispose();if(guard)await guard.dispose();await frame.dispose();await f.close();}});
test(`${host}: continuation45 recovers from privatePage after every original producer is gone`,async()=>{const f=await setup(host),frame=await f.index.update(f.q,{sequence:2n});let first,second,guard,fail=true;try{first=await frame.members(136,{sequence:10n,maxVertices:1000n});assert.equal(first.hasNext,true);await frame.dispose();await f.index.dispose();await f.seed.dispose();await f.bridge.execute(encode({command:10,handle:f.source}));f.control.execute=async b=>{const r=await f.actual(b);if(new DataView(b).getUint32(8,true)===45&&fail){fail=false;throw Error('lost continuation45');}return r;};await assert.rejects(first.nextPage({sequence:11n,maxVertices:1000n}),e=>{guard=e.owner;return e instanceof GeoOverviewMembershipUncertain;});await first.dispose();first=undefined;second=await guard.recover();assert.equal(second.record(0).sourceRow,4n);assert.equal(second.cumulativeVertices,3n);await second.dispose();second=undefined;f.holder.dispose();}finally{if(first)await first.dispose();if(second)await second.dispose();if(guard)await guard.dispose();}});
}

if(process.env.XYG_GEO_OVERVIEW_WASM)test('recovered complete XYOM packet native/WASM parity',()=>{for(const corrupt of [false,true])assert.equal(recoveryPackets.get(`native:${corrupt}`),recoveryPackets.get(`wasm:${corrupt}`));});
if(process.env.XYG_GEO_MEMBERS_RECOVERY_REPORT)after(async()=>{await writeFile(process.env.XYG_GEO_MEMBERS_RECOVERY_REPORT,JSON.stringify({schema:1,contract:'XYOMv1; exact45 recovery with47 Confirm',normalization:'only process owner16..24',cases:Object.fromEntries(recoveryPackets),limits:'bounded domain membership; finalfalse; no MemberData10 absence classifier'},null,2)+'\n');});

for(const host of process.env.XYG_GEO_OVERVIEW_WASM?['native','wasm']:['native'])test(`${host}: lostoriginal45 already retired confirms target0 and never resurrects Query`,async()=>{const f=await setup(host),frame=await f.index.update(f.q,{sequence:2n});let fail=true,guard,page,created=0;try{f.control.execute=async b=>{const v=new DataView(b),c=v.getUint32(8,true),r=await f.actual(b);if(c===45){created++;if(fail){fail=false;await f.actual(request(10,reply(r).handle,10n));throw Error('lost original after Query retirement');}}return r;};await assert.rejects(frame.members(136,{sequence:10n,maxVertices:1000n}),e=>{guard=e.owner;return e instanceof GeoOverviewMembershipUncertain;});await assert.rejects(guard.recover(),/retired/);assert.equal(guard.closed,true);await guard.dispose();assert.equal(created,2);page=await frame.members(136,{sequence:11n,maxVertices:1000n});assert.equal(page.record(0).featureId,U64);}finally{if(page)await page.dispose();if(guard)await guard.dispose();await frame.dispose();await f.close();}});
