import test from 'node:test';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {fixture,budget,U64} from './geoscale-fixture.mjs';
import {nativeGeoScaleBridge,encodeGeoScaleRequest as encode,decodeGeoScaleReply as decode,driveGeoSession,prepareGeoSceneData,encodeGeoScaleStyle} from '../src/geoscale.js';
import {GeoOverviewIndex,GeoOverviewUncertainAllocation,overviewFrameAuthority} from '../src/geo-overview-source.js';
import {encodeGeoOverviewRequest as request,decodeGeoOverviewReply as reply} from '../src/geo-overview.js';
async function transport(host){if(host==='native')return {bridge:nativeGeoScaleBridge(budget.processorBytes),dispose(){}};const {instance}=await WebAssembly.instantiate(await readFile(process.env.XYG_GEO_OVERVIEW_WASM),{}),x=instance.exports,id=x.xyg_wasm_instance_new(budget.processorBytes);assert.ok(id);let seq=0;async function call(b,read){assert.equal(x.xyg_wasm_arena_resize(id,b.byteLength),0);new Uint8Array(x.memory.buffer,x.xyg_wasm_arena_ptr(id)>>>0,b.byteLength).set(new Uint8Array(b));const code=x[read?'xyg_wasm_geo_scale_read':'xyg_wasm_geo_scale_execute'](id,++seq,0,b.byteLength);if(code){const e=new Error(new TextDecoder().decode(new Uint8Array(x.memory.buffer,x.xyg_wasm_last_error_ptr(id)>>>0,x.xyg_wasm_last_error_len(id))));e.nativeCode=code===3?-9:code;throw e;}return new Uint8Array(x.memory.buffer,x.xyg_wasm_output_ptr(id)>>>0,x.xyg_wasm_output_len(id)).slice().buffer;}return {bridge:{execute:b=>call(b,false),read:b=>call(b,true)},dispose(){assert.equal(x.xyg_wasm_instance_dispose(id),0);}};}
async function setup(host,direct=false){const holder=await transport(host),actualExecute=holder.bridge.execute,control={execute:actualExecute},bridge=direct?holder.bridge:{execute:b=>control.execute(b),read:holder.bridge.read},raw=await fixture(bridge),chunk=Uint8Array.from(Buffer.from(raw.chunk,'hex')),manifest=Uint8Array.from(Buffer.from(raw.manifest,'hex'));const source=decode(await bridge.execute(encode({command:4,budget,payload:manifest}))).handle;const readChunk=async()=>chunk,info=(await driveGeoSession(bridge,{handle:source,sequence:0n,budget,readChunk})).source;
const q={camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:0,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:32768,previousDirect:true,sourceDigest:info.digest,generation:info.generation,layerId:U64,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:0},maxProjectedVertices:1000000n};
await bridge.execute(encode({command:5,handle:source,sequence:1n,budget,query:q}));await driveGeoSession(bridge,{handle:source,sequence:1n,budget,readChunk});const seed=await prepareGeoSceneData(bridge,{handle:source,sequence:1n,budget,style:encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0})});const pages=new Map();const index=await GeoOverviewIndex.fromFrame(seed,{bridge,budget,maxVertices:1000000n,readChunk,readPage:async t=>pages.get(`${t.namespace}:${t.page}`),writePage:async(t,b)=>{pages.set(`${t.namespace}:${t.page}`,b.slice());}});return {bridge,actualExecute,setExecute(fn){control.execute=fn;},source,seed,index,holder,chunk,q:{...q,maxCells:0,previousDirect:false,maxProjectedVertices:0n},async close(){await index.dispose();await seed.dispose();await bridge.execute(encode({command:10,handle:source}));holder.dispose();}};}
function rejected(handle,sequence){const b=new ArrayBuffer(256),v=new DataView(b);v.setUint32(0,0x5a475958,true);v.setUint32(4,1,true);v.setUint32(8,2,true);v.setBigUint64(16,handle,true);v.setBigUint64(24,sequence,true);return b;}
for(const host of process.env.XYG_GEO_OVERVIEW_WASM?['native','wasm']:['native']){
test('private issued producer survives public method edits and immutable copies survive index disposal',async()=>{const f=await setup(host);let frame,held;try{f.index.begin=()=>{throw Error('public override');};frame=await f.index.update(f.q,{sequence:2n});const auth=overviewFrameAuthority(frame);assert.equal(auth.header.byteLength,2304);auth.header.fill(0);assert.equal(overviewFrameAuthority(frame).header[0],0x58);held=await frame.retain();await f.index.dispose();await frame.dispose();assert.equal(held.data.final,false);let count=0n;for(let i=0;i<256;i++)count+=held.data.count(i);assert.equal(count,2n);}finally{if(held)await held.dispose();if(frame)await frame.dispose();await f.close();}});
test('resolved rejected Data disposal retains known handle and explicit retry succeeds',async()=>{const f=await setup(host);const frame=await f.index.update(f.q,{sequence:2n}),actual=f.actualExecute;try{f.setExecute(b=>new DataView(b).getUint32(8,true)===10?Promise.resolve(rejected(frame.handle,0n)):actual(b));await assert.rejects(frame.dispose(),/confirm settlement/);f.setExecute(actual);await frame.dispose();await frame.dispose();}finally{f.setExecute(actual);await frame.dispose();await f.close();}});
test('deferred28 admission is settled before index cleanup, with no handle-zero mutation',async()=>{const f=await setup(host),actual=f.actualExecute;let release,entered;const gate=new Promise(r=>release=r),started=new Promise(r=>entered=r),commands=[];try{f.setExecute(async b=>{const v=new DataView(b);commands.push([v.getUint32(8,true),v.getBigUint64(16,true)]);const result=await actual(b);if(v.getUint32(8,true)===28){entered();await gate;}return result;});const begin=f.index.begin(f.q,{sequence:2n});await started;const closing=f.index.dispose();release();await begin;await closing;assert.ok(!commands.some(([c,h])=>c===10&&h===0n));}finally{release?.();f.setExecute(actual);await f.close();}});
test('lost28 blocks reallocation while original Data remains usable',async()=>{const f=await setup(host),actual=f.actualExecute;let lost;const frame=await f.index.update(f.q,{sequence:2n});try{f.setExecute(async b=>{const result=await actual(b);if(new DataView(b).getUint32(8,true)===28){lost=reply(result).handle;throw Error('lost real receipt');}return result;});await assert.rejects(f.index.update(f.q,{sequence:3n}),e=>e instanceof GeoOverviewUncertainAllocation&&e.owner===f.index.pendingOperation);await assert.rejects(f.index.begin(f.q,{sequence:4n}),/busy/);assert.equal(frame.data.final,false);}finally{f.setExecute(actual);await actual(request({command:10,handle:lost,sequence:3n}));await frame.dispose();/* Test-only observed receipt permits cleanup; product owner deliberately remains poisoned. */await actual(request({command:10,handle:f.index.handle,sequence:1n}));await f.seed.dispose();await actual(encode({command:10,handle:f.source}));f.holder.dispose();}});
test('transferred wire requests never detach privately retained overview query authority',async()=>{const f=await setup(host),actual=f.actualExecute;let frame;try{f.setExecute(async b=>{const result=await actual(b);structuredClone(b,{transfer:[b]});return result;});frame=await f.index.update(f.q,{sequence:2n});const auth=overviewFrameAuthority(frame);assert.equal(auth.query.byteLength,256);const copy=await frame.retain();await copy.dispose();assert.equal(frame.data.final,false);}finally{f.setExecute(actual);if(frame)await frame.dispose();await f.close();}});
test('rejected ACK retains exact private loan until retry; old paint and next query recover',async()=>{const f=await setup(host),actual=f.actualExecute;const old=await f.index.update(f.q,{sequence:2n});let fault=true,acks=0;try{f.setExecute(async b=>{const v=new DataView(b);if(v.getUint32(8,true)===8){acks++;if(fault)return rejected(v.getBigUint64(16,true),v.getBigUint64(24,true));}return actual(b);});await assert.rejects(f.index.update({...f.q,time:{kind:1,instant:0n}},{sequence:3n}),/confirm settlement/);assert.equal(old.data.final,false);assert.ok(f.index.pendingOperation);fault=false;await f.index.pendingOperation.dispose();const next=await f.index.update(f.q,{sequence:4n});assert.equal(next.data.final,false);await next.dispose();assert.ok(acks>=3);}finally{fault=false;f.setExecute(actual);await old.dispose();await f.close();}});
test('lost26 poisons only the issued duplicate guard; original stays valid and no allocation repeats',async()=>{const f=await setup(host),actual=f.actualExecute,frame=await f.index.update(f.q,{sequence:2n});let lost,attempts=0;try{f.setExecute(async b=>{const result=await actual(b);if(new DataView(b).getUint32(8,true)===26){attempts++;lost=reply(result).handle;throw Error('lost real26');}return result;});let guard;await assert.rejects(frame.retain(),e=>{guard=e.owner;return e instanceof GeoOverviewUncertainAllocation;});await assert.rejects(frame.retain(),e=>e.owner===guard);await assert.rejects(guard.dispose(),GeoOverviewUncertainAllocation);assert.equal(attempts,1);assert.equal(frame.data.final,false);}finally{f.setExecute(actual);await actual(request({command:10,handle:lost,sequence:0n}));await frame.dispose();await f.close();}});

test('lost27 retains builder guard; no guessed disposal and seed/other index remain valid',async()=>{const f=await setup(host),actual=f.actualExecute;let lost;try{f.setExecute(async b=>{const result=await actual(b);if(new DataView(b).getUint32(8,true)===27){lost=reply(result).handle;throw Error('lost real27');}return result;});let owner;await assert.rejects(GeoOverviewIndex.fromFrame(f.seed,{bridge:f.bridge,budget,maxVertices:1000000n,readChunk:async()=>new Uint8Array(),readPage:async()=>new Uint8Array(),writePage:async()=>{}}),e=>{owner=e.owner;return e instanceof GeoOverviewUncertainAllocation;});await assert.rejects(owner.dispose(),GeoOverviewUncertainAllocation);assert.equal(f.seed.data.record(0).featureId,U64);}finally{f.setExecute(actual);await actual(request({command:10,handle:lost,sequence:1n}));await f.close();}});
test('lost29 retains publication guard and blocks new query; old immutable Data survives',async()=>{const f=await setup(host),actual=f.actualExecute,old=await f.index.update(f.q,{sequence:2n});let data,query;try{f.setExecute(async b=>{const result=await actual(b),c=new DataView(b).getUint32(8,true);if(c===28)query=reply(result).handle;if(c===29){data=reply(result).handle;throw Error('lost real29');}return result;});let guard;await assert.rejects(f.index.update(f.q,{sequence:3n}),e=>{guard=e.owner;return e instanceof GeoOverviewUncertainAllocation;});await assert.rejects(guard.dispose(),GeoOverviewUncertainAllocation);await assert.rejects(f.index.begin(f.q,{sequence:4n}),/busy/);assert.equal(old.data.final,false);}finally{f.setExecute(actual);await actual(request({command:10,handle:data,sequence:0n}));await actual(request({command:10,handle:query,sequence:3n}));await old.dispose();await actual(request({command:10,handle:f.index.handle,sequence:1n}));await f.seed.dispose();await actual(encode({command:10,handle:f.source}));f.holder.dispose();}});
test('foreign bridge and mutable public seed handle reject before allocation',async()=>{const f=await setup(host);const input={bridge:{execute:f.bridge.execute,read:f.bridge.read},budget,maxVertices:1000000n,readChunk:async()=>new Uint8Array(),readPage:async()=>new Uint8Array(),writePage:async()=>{}};try{await assert.rejects(GeoOverviewIndex.fromFrame(f.seed,input),/privately issued/);const original=f.seed.handle;f.seed.handle=f.index.handle;await assert.rejects(GeoOverviewIndex.fromFrame(f.seed,{...input,bridge:f.bridge}),/privately issued/);f.seed.handle=original;}finally{await f.close();}});

test('five issued views keep independent snapshots within existing Data/handle caps',async()=>{const f=await setup(host),lanes=[f.index],frames=[],pages=new Map();try{for(let i=1;i<5;i++)lanes.push(await GeoOverviewIndex.fromFrame(f.seed,{bridge:f.bridge,budget,maxVertices:1000000n,readChunk:async()=>f.chunk,readPage:async t=>pages.get(`${t.namespace}:${t.page}`),writePage:async(t,b)=>pages.set(`${t.namespace}:${t.page}`,b.slice())}));for(let i=0;i<5;i++)frames.push(await lanes[i].update({...f.q,camera:{...f.q.camera,centerX:i},cameraRevision:BigInt(i+2)},{sequence:BigInt(i+2)}));const newer=await lanes[0].update({...f.q,camera:{...f.q.camera,centerX:30},cameraRevision:99n},{sequence:99n});assert.equal(newer.data.identity.camera.centerX,30);for(let i=0;i<5;i++)assert.equal(frames[i].data.identity.camera.centerX,i);await newer.dispose();}finally{for(const frame of frames)await frame.dispose();for(const lane of lanes.slice(1))await lane.dispose();await f.close();}});

}

test('public native density composition exports immutable nonfinal receipt in six formats',async()=>{const {geoChart,geoLayer}=await import('../src/charts.js'),f=await setup('native',true);let frame;try{const chart=geoChart(geoLayer('density',{source:f.index,layerId:U64,query:f.q,sequence:2n}),{camera:f.q.camera});frame=await chart.compileRetained();assert.equal(frame.data.final,false);assert.throws(()=>chart.host({frame}),/overview host/);for(const format of ['png','jpeg','webp','svg','pdf','html']){const artifact=await chart.toImage(format,{frame});assert.ok(artifact.bytes.byteLength>50);if(format==='html')assert.ok(!Buffer.from(artifact.bytes).includes(Buffer.from('<script')));await artifact.dispose();}}finally{if(frame)await frame.dispose();await f.close();}});

if(process.env.XYG_GEO_OVERVIEW_WASM)test('public WASM bridge retagging cannot claim native export provenance',async()=>{const f=await setup('wasm',true),native=await setup('native',true);const original=f.bridge.execute;let frame;try{const {geoScaleExecute}=await import('../src/geoscale.js');f.bridge.execute=geoScaleExecute;frame=await f.index.update(f.q,{sequence:2n});assert.equal(frame.data.final,false);assert.throws(()=>frame.export('svg'),/native issuing transport/);assert.equal(native.seed.data.record(0).featureId,U64);}finally{f.bridge.execute=original;if(frame)await frame.dispose();await f.close();await native.close();}});
