// Actual native executable, C ABI, and wasm32 camera/geometry parity (#48).
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import test from 'node:test';import {fileURLToPath} from 'node:url';import {tmpdir} from 'node:os';
import {encodeGeoViewportRequest,decodeGeoViewportResponse,geoViewportExecute,encodeGeoViewportColumnRequest as encodeNativeColumnRequest} from '../src/geoviewport.js';
import {encodeWasmGeoDescriptor,encodeGeoViewportRequest as encodeBrowserCamera,encodeGeoViewportColumnRequest,encodeWasmGeoSceneRequest} from '../../xy-client/dist/index.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..');
const camera={crs:4326,centerX:0,centerY:0,zoom:2,width:800,height:600,bearing:0,pitch:0,worldWrap:true};
async function wasm(budget=64<<20){const{instance}=await WebAssembly.instantiate(fs.readFileSync(process.env.XYG_WASM_ARTIFACT??path.join(root,'packages/xy-client/dist/xyg-wasm.wasm')),{}),x=instance.exports,h=x.xyg_wasm_instance_new(budget);let sequence=0;return{run(request){assert.equal(x.xyg_wasm_arena_resize(h,request.byteLength),0);new Uint8Array(x.memory.buffer,x.xyg_wasm_arena_ptr(h)>>>0,request.byteLength).set(new Uint8Array(request));const status=x.xyg_wasm_geo_viewport_execute(h,++sequence,0,request.byteLength);assert.equal(x.xyg_wasm_arena_len(h),0);return{status,bytes:new Uint8Array(x.memory.buffer,x.xyg_wasm_output_ptr(h)>>>0,x.xyg_wasm_output_len(h)).slice(),error:new TextDecoder().decode(new Uint8Array(x.memory.buffer,x.xyg_wasm_last_error_ptr(h)>>>0,x.xyg_wasm_last_error_len(h)))};},dispose(){assert.equal(x.xyg_wasm_instance_dispose(h),0);}};}
function native(request,budget=64<<20){
 // The bounded oracle can reject its budget before reading stdin. An owned
 // file descriptor preserves the exact input without a platform EPIPE race.
 const directory=fs.mkdtempSync(path.join(tmpdir(),'xyg-geo-viewport-oracle-'));let fd;
 try{const input=path.join(directory,'request.bin');fs.writeFileSync(input,Buffer.from(request));fd=fs.openSync(input,'r');const r=spawnSync(path.join(root,'target/debug/geo_viewport_conformance'),[String(budget)],{stdio:[fd,'pipe','pipe'],maxBuffer:128<<20});if(r.error)throw r.error;return{status:r.status,bytes:new Uint8Array(r.stdout),error:r.stderr.toString().trim()};}
 finally{if(fd!==undefined)fs.closeSync(fd);fs.rmSync(directory,{recursive:true,force:true});}
}
function same(a,b){assert.equal(a.length,b.length);const av=decodeGeoViewportResponse(a.buffer.slice(a.byteOffset,a.byteOffset+a.byteLength)),bv=decodeGeoViewportResponse(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength));assert.equal(av.operation,bv.operation);assert.equal(av.kind,bv.kind);assert.equal(av.bounds===null,bv.bounds===null);if(av.bounds)for(let i=0;i<4;i++)assert.ok(Math.abs(av.bounds[i]-bv.bounds[i])<=1e-4);for(let i=0;i<2;i++)assert.ok(Math.abs(av.polygonOrigin[i]-bv.polygonOrigin[i])<=1e-6);for(const key of['crs','worldWrap'])assert.equal(av.camera[key],bv.camera[key]);for(const key of['centerX','centerY','zoom','width','height','bearing','pitch'])assert.ok(Math.abs(av.camera[key]-bv.camera[key])<=1e-9);for(let i=0;i<2;i++)assert.ok(Math.abs(av.result[i]-bv.result[i])<=1e-6);for(const name of['featureIds','visibleFeatureIds','offsets','ringOffsets','polygonOffsets','polygonFeatureIds','ringIsHole'])assert.deepEqual(av[name],bv[name]);for(const name of['xy','polygonXY']){assert.equal(av[name].length,bv[name].length);for(let i=0;i<av[name].length;i++)assert.ok(Math.abs(av[name][i]-bv[name][i])<=1e-4);}assert.deepEqual(av.metadataDigest,bv.metadataDigest);return bv;}
for(const[op,args]of[[0,[]],[1,[0,0]],[2,[400,300]],[3,[100,50]],[4,[24]],[5,[1024,768]],[6,[1080]],[7,[30]],[8,[170,80]],[9,[170,-10,-170,10,20]]])test(`native/C ABI/actual wasm32 camera command ${op}`,async()=>{const w=await wasm();try{const req=encodeGeoViewportRequest(camera,op,args),n=native(req),b=w.run(req);assert.deepEqual(new Uint8Array(req),new Uint8Array(encodeBrowserCamera(camera,op,args)));assert.equal(n.status,0);assert.equal(b.status,0);const snapshot=same(n.bytes,b.bytes);assert.ok(snapshot.bounds?.every(Number.isFinite));assert.ok(snapshot.bounds[0]<snapshot.bounds[2]&&snapshot.bounds[1]<snapshot.bounds[3]);assert.deepEqual(new Uint8Array(geoViewportExecute(req)),n.bytes);if(op===1)assert.deepEqual(decodeGeoViewportResponse(b.bytes.buffer).result,[400,300]);}finally{w.dispose();}});
for(const crs of[4326,3857])test(`projection inverse polar/dateline roundtrip EPSG${crs}`,async()=>{const w=await wasm();try{for(const point of crs===4326?[[179,85],[-179,-85],[0,0]]:[[20000000,20000000],[-20000000,-20000000],[0,0]]){const cam={...camera,crs,bearing:37,pitch:0},p=w.run(encodeGeoViewportRequest(cam,1,point));assert.equal(p.status,0);const screen=decodeGeoViewportResponse(p.bytes.buffer).result,q=w.run(encodeGeoViewportRequest(cam,2,screen));assert.equal(q.status,0);const source=decodeGeoViewportResponse(q.bytes.buffer).result;for(let i=0;i<2;i++)assert.ok(Math.abs(source[i]-point[i])<=(crs===4326?1e-9:1e-6));}}finally{w.dispose();}});
const golden=JSON.parse(fs.readFileSync(path.join(root,'tests/fixtures/geo_cross_host.json')));const kinds={point:1,linestring:2,polygon:3,multipoint:4,multilinestring:5,multipolygon:6};
for(const c of golden.cases.filter(c=>c.status===0&&c.descriptor))test(`canonical projected planes ${c.name}`,async()=>{const w=await wasm();try{const d=c.descriptor,crs=Number(JSON.parse(c.extension_metadata).crs.split(':')[1]),source=encodeWasmGeoDescriptor({geometry:kinds[c.extension_name.split('.')[1]],crs,xy:new Float64Array(BigUint64Array.from(d.xy,h=>BigInt('0x'+h)).buffer),validity:Uint8Array.from(d.validity),featureIds:d.feature_ids===null?null:BigUint64Array.from(d.feature_ids,BigInt),...Object.fromEntries([0,1,2].map(i=>['offsets'+i,Uint32Array.from(d['offsets'+i]??[])]))}),req=encodeGeoViewportRequest({...camera,crs,zoom:0},10,[],source),n=native(req),b=w.run(req);assert.equal(n.status,0);assert.equal(b.status,0);const out=same(n.bytes,b.bytes);assert.deepEqual(new Uint8Array(geoViewportExecute(req)),n.bytes);assert.ok([...out.xy,...out.polygonXY].every(Number.isFinite));assert.ok([...out.visibleFeatureIds].every(id=>d.feature_ids===null||d.feature_ids.includes(String(id))));}finally{w.dispose();}});
test('malformed camera/framing/resource failure is atomic and stable',async()=>{const w=await wasm();try{for(const changes of[{zoom:25},{width:0},{centerX:NaN},{crs:999}]){const req=encodeGeoViewportRequest({...camera,...changes}),n=native(req),b=w.run(req);assert.equal(b.status,n.status);assert.notEqual(b.status,0);assert.equal(b.error,n.error);assert.equal(b.bytes.length,0);}const req=encodeGeoViewportRequest(camera),bad=req.slice(0);new Uint8Array(bad)[127]=1;assert.equal(w.run(bad).status,2);assert.throws(()=>decodeGeoViewportResponse(new ArrayBuffer(256)));const n=native(req,8191);assert.equal(n.status,3);}finally{w.dispose();}});

test('no-op camera transitions preserve normalized snapshot rebuild key',()=>{const base=decodeGeoViewportResponse(geoViewportExecute(encodeGeoViewportRequest(camera)));for(const[op,args]of[[0,[]],[3,[0,0]],[4,[2]],[5,[800,600]],[6,[720]],[7,[0]],[8,[0,0]]]){const out=decodeGeoViewportResponse(geoViewportExecute(encodeGeoViewportRequest(camera,op,args)));assert.deepEqual(out.rebuildKey,base.rebuildKey);}});

test('overbudget camera input fails before host allocation/native call',()=>{const request=encodeGeoViewportRequest(camera),ArrayType=globalThis.BigUint64Array;globalThis.BigUint64Array=class{constructor(){throw new Error('output-size allocation must not be invoked');}};try{assert.throws(()=>geoViewportExecute(request,127),error=>error.nativeCode===-9);assert.throws(()=>geoViewportExecute(new ArrayBuffer(1)),error=>error.nativeCode===-1);}finally{globalThis.BigUint64Array=ArrayType;}});

test('typed column encoder allocates one prefixed transferable request',()=>{const descriptor={geometry:1,crs:4326,xy:Float64Array.of(1,2),validity:Uint8Array.of(1),featureIds:BigUint64Array.of(0xffffffffffffffffn)},source=encodeWasmGeoDescriptor(descriptor),expected=encodeGeoViewportRequest(camera,10,[],source),ArrayType=globalThis.ArrayBuffer;let allocations=0;globalThis.ArrayBuffer=class extends ArrayType{constructor(length){super(length);allocations++;}};try{const actual=encodeGeoViewportColumnRequest(camera,descriptor);assert.equal(allocations,1);assert.deepEqual(new Uint8Array(actual),new Uint8Array(expected));assert.equal(descriptor.xy.byteLength,16);assert.deepEqual(new Uint8Array(encodeNativeColumnRequest(camera,descriptor)),new Uint8Array(expected));}finally{globalThis.ArrayBuffer=ArrayType;}});

test('camera wrap framing rejects nonbooleans and preserves false',()=>{const descriptor={geometry:1,crs:4326,xy:Float64Array.of(0,0),validity:Uint8Array.of(1)};for(const worldWrap of['false',2,null]){const invalid={...camera,worldWrap};assert.throws(()=>encodeGeoViewportRequest(invalid),TypeError);assert.throws(()=>encodeBrowserCamera(invalid),TypeError);assert.throws(()=>encodeGeoViewportColumnRequest(invalid,descriptor),TypeError);assert.throws(()=>encodeNativeColumnRequest(invalid,descriptor),TypeError);assert.throws(()=>encodeWasmGeoSceneRequest(descriptor,invalid),TypeError);}assert.equal(decodeGeoViewportResponse(geoViewportExecute(encodeGeoViewportRequest({...camera,worldWrap:false}))).camera.worldWrap,false);});

test('pitched front ground roundtrip preserves source coordinates',async()=>{const w=await wasm();try{const cam={...camera,bearing:37,pitch:40};for(const source of[[0,0],[5,5],[-5,-5]]){const p=w.run(encodeGeoViewportRequest(cam,1,source));assert.equal(p.status,0);const screen=decodeGeoViewportResponse(p.bytes.buffer).result,q=w.run(encodeGeoViewportRequest(cam,2,screen));assert.equal(q.status,0);const back=decodeGeoViewportResponse(q.bytes.buffer).result;for(let i=0;i<2;i++)assert.ok(Math.abs(source[i]-back[i])<1e-9);}}finally{w.dispose();}});

test('native typed column framing rejects source narrowing',()=>{const descriptor={geometry:1,crs:4326,xy:Float64Array.of(1,2),validity:Uint8Array.of(1),featureIds:BigUint64Array.of(0xffffffffffffffffn)};for(const bad of[{...descriptor,xy:Float32Array.of(1,2)},{...descriptor,featureIds:Uint32Array.of(1)},{...descriptor,offsets0:Float64Array.of(0,1)}])assert.throws(()=>encodeNativeColumnRequest(camera,bad),TypeError);});
