// Actual native and packaged wasm32 hierarchy transport, no host geometry policy.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {RetainedGeoSource,attachRetainedFrame} from '../src/geo-retained.js';
import {GeoHierarchy,GeoHierarchyFallback,GeoHierarchyUnsupportedSelected,isHierarchyFrame} from '../src/geo-hierarchy.js';
import {decodeGeoHierarchyReply,encodeGeoHierarchyRequest} from '../src/geo-hierarchy-wire.js';
import {nativeGeoScaleBridge,encodeGeoScaleStyle,encodeGeoChunkRequest,encodeGeoScaleRequest as canonical,decodeGeoScaleReply as ordinary,driveGeoSession,prepareGeoSceneData} from '../src/geoscale.js';
import {fixture,budget,U64,I64} from './geoscale-fixture.mjs';
const style=()=>encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0});
function query(info){return {camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:0,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:32768,previousDirect:true,sourceDigest:info.digest,generation:info.generation,layerId:U64,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:1,instant:I64},maxProjectedVertices:1000000n};}
async function setup(bridge,spread=false){const raw=await fixture(bridge);let chunk=Uint8Array.from(Buffer.from(raw.chunk,'hex'));if(spread){const request=Uint8Array.from(Buffer.from(raw.chunk_request,'hex'));new DataView(request.buffer).setFloat64(256+32+64,77,true);chunk=new Uint8Array(await bridge.read(request.buffer));}const builder=ordinary(await bridge.execute(canonical({command:1}))).handle;let manifest;try{await bridge.execute(canonical({command:2,handle:builder,payload:chunk}));await bridge.execute(canonical({command:3,handle:builder,generation:U64}));manifest=await bridge.read(canonical({command:21,handle:builder}));}finally{await bridge.execute(canonical({command:10,handle:builder}));}const source=await RetainedGeoSource.create(manifest,()=>chunk,{budget,bridge});return{source,frame:await source.update(query(source.info),{sequence:1n,style:style()})};}
function storage(pages){return {grid:1024,maxVertices:1000000n,maxWriteBytes:64n<<20n,readPage:t=>pages.get(`${t.namespace}:${t.page}`),writePage:(t,b)=>pages.set(`${t.namespace}:${t.page}`,b.slice())};}
const packets=[];
for(const name of['native','wasm']){
 test(`${name} hierarchy exact Scene, independent frame/Rows/retain after disposal`,async()=>{
  const holder=await bridgeFor(name),{source,frame:old}=await setup(holder.bridge);let index,frame,retained;
  try{index=await GeoHierarchy.fromFrame(old,source,storage(new Map()));await source.dispose();frame=await index.update(query(index.info),{sequence:2n,style:style()});assert.deepEqual(frame.data.scene,old.data.scene);assert.equal(frame.data.record(0).featureId,U64);assert.equal(frame._source,source);assert.equal(frame.hierarchyStats.passes,1);assert.equal(isHierarchyFrame(frame),true);assert.equal(isHierarchyFrame(old),false);retained=await frame.retain();assert.equal(isHierarchyFrame(retained),true);await index.dispose();await frame.dispose();const rows=await retained.rows();try{assert.equal(rows.data.record(0).featureId,U64);const stable=new Uint8Array(rows.data.packet.slice(0));stable.fill(0,16,24);packets.push({host:name,kind:'rows',hash:createHash('sha256').update(stable).digest('hex')});}finally{await rows.dispose();}const hit=await retained.pick({style:style(),x:400,y:300,tolerance:0,mode:0,maxHits:4});assert.equal(hit.data.count,1n);await hit.dispose();packets.push({host:name,kind:'scene',hash:createHash('sha256').update(retained.data.scene).digest('hex')});}
  finally{if(retained)await retained.dispose();if(frame)await frame.dispose();if(index)await index.dispose();await old.dispose();await source.dispose();holder.dispose();}
 });
 test(`${name} mutated callback authority settles exact ACK and failed query retains old frame`,async()=>{
  const holder=await bridgeFor(name),{source,frame:old}=await setup(holder.bridge);let index,frame;const pages=new Map();let corrupt=false;
  try{await assert.rejects(GeoHierarchy.fromFrame(old,source,{...storage(pages),writePage:(t,b)=>{t.raw.fill(0);t.namespace=0n;t.encodedBytes*=2;throw new Error('write failed');}}),/write failed/);index=await GeoHierarchy.fromFrame(old,source,{...storage(pages),readPage:t=>{const bytes=pages.get(`${t.namespace}:${t.page}`);if(corrupt){t.raw.fill(0);t.encodedBytes*=2;return new Uint8Array(bytes.length*2);}return bytes;}});frame=await index.update(query(index.info),{sequence:2n,style:style()});corrupt=true;await assert.rejects(index.update(query(index.info),{sequence:3n,style:style()}),/bounded/);assert.equal(index.current,frame);assert.equal(frame.data.record(0).featureId,U64);corrupt=false;const recovery=await index.update(query(index.info),{sequence:4n,style:style()});await recovery.dispose();}
  finally{if(frame)await frame.dispose();if(index)await index.dispose();await old.dispose();await source.dispose();holder.dispose();}
 });
 test(`${name} cancel pending write awaits callback settlement and exact private ACK`,async()=>{
  const holder=await bridgeFor(name),{source,frame:old}=await setup(holder.bridge);const controller=new AbortController();let enter,release;const started=new Promise(r=>enter=r),gate=new Promise(r=>release=r);const pending=GeoHierarchy.fromFrame(old,source,{...storage(new Map()),signal:controller.signal,writePage:async(t,b)=>{t.kind=1;t.raw.fill(0);enter();await gate;}});
  try{await Promise.race([started,pending.then(()=>{throw new Error('write not entered');})]);controller.abort();let settled=false;pending.then(()=>settled=true,()=>settled=true);await new Promise(r=>setTimeout(r,10));assert.equal(settled,false);release();await assert.rejects(pending,/abort|cancel/i);assert.equal(old.data.record(0).featureId,U64);const index=await GeoHierarchy.fromFrame(old,source,storage(new Map()));await index.dispose();}
  finally{release();await pending.catch(()=>{});await old.dispose();await source.dispose();holder.dispose();}
 });
 test(`${name} local budget/forged ticket rejects and exact fallback retains current frame`,async()=>{
  const holder=await bridgeFor(name),{source,frame:old}=await setup(holder.bridge);let index,frame;
  try{source.budget.maxChunks=1;index=await GeoHierarchy.fromFrame(old,source,storage(new Map()));await assert.rejects(index.update(query(index.info),{sequence:2n,style:style()}),e=>e instanceof GeoHierarchyFallback&&e.reasonCode===2);assert.equal(source.current,old);assert.equal(old.data.record(0).featureId,U64);await assert.rejects(holder.bridge.execute(encodeGeoHierarchyRequest({command:37,handle:old.handle,sequence:1n,budget:{...budget,processorBytes:4096},payload:new Uint8Array(24)})));}
  finally{if(frame)await frame.dispose();if(index)await index.dispose();await old.dispose();await source.dispose();holder.dispose();}
 });
}
async function bridgeFor(name){if(name==='native')return{bridge:nativeGeoScaleBridge(budget.processorBytes),dispose(){}};const file=process.env.XYG_HIERARCHY_WASM??'../../xy-client/dist/xyg-wasm.wasm';const {instance}=await WebAssembly.instantiate(await readFile(file),{}),x=instance.exports,id=x.xyg_wasm_instance_new(budget.processorBytes);assert.ok(id);let sequence=0;async function call(request,read){assert.equal(x.xyg_wasm_arena_resize(id,request.byteLength),0);new Uint8Array(x.memory.buffer,x.xyg_wasm_arena_ptr(id)>>>0,request.byteLength).set(new Uint8Array(request));const status=x[read?'xyg_wasm_geo_scale_read':'xyg_wasm_geo_scale_execute'](id,++sequence,0,request.byteLength);if(status){const error=new Error(`WASM ${status}: `+new TextDecoder().decode(new Uint8Array(x.memory.buffer,x.xyg_wasm_last_error_ptr(id)>>>0,x.xyg_wasm_last_error_len(id))));error.nativeCode=status===3?-9:status;error.wasmStatus=status;throw error;}return new Uint8Array(x.memory.buffer,x.xyg_wasm_output_ptr(id)>>>0,x.xyg_wasm_output_len(id)).slice().buffer;}return{bridge:{execute:r=>call(r,false),read:r=>call(r,true)},dispose(){assert.equal(x.xyg_wasm_instance_dispose(id),0);}};}
for(const host of['native','wasm'])test(`${host} cancelled canonical read settles before ACK and terminal reply cannot publish`,async()=>{
 const holder=await bridgeFor(host),native=holder.bridge;let terminalEnter,terminalRelease;const terminal=new Promise(r=>terminalEnter=r),terminalGate=new Promise(r=>terminalRelease=r);let delay=false;holder.bridge={read:r=>native.read(r),async execute(r){const out=await native.execute(r);if(delay&&new DataView(r).getUint32(8,true)===6&&new DataView(out).getUint32(8,true)===19){terminalEnter();await terminalGate;}return out;}};const {source,frame:old}=await setup(holder.bridge);let enter,release;const started=new Promise(r=>enter=r),gate=new Promise(r=>release=r),controller=new AbortController(),original=source.readChunk;source.readChunk=async(t)=>{enter();await gate;t.raw.fill(0);t.encodedBytes*=2;return original(t);};const pending=GeoHierarchy.fromFrame(old,source,{...storage(new Map()),signal:controller.signal});let index;
 try{await started;controller.abort();let settled=false;pending.then(()=>settled=true,()=>settled=true);await new Promise(r=>setTimeout(r,10));assert.equal(settled,false);release();await assert.rejects(pending,/abort|cancel/i);source.readChunk=original;index=await GeoHierarchy.fromFrame(old,source,storage(new Map()));delay=true;const stop=new AbortController(),querying=index.update(query(index.info),{sequence:2n,style:style(),signal:stop.signal});await terminal;stop.abort();terminalRelease();await assert.rejects(querying,/abort|cancel/i);assert.equal(index.current,undefined);assert.equal(source.current,old);delay=false;const recovery=await index.update(query(index.info),{sequence:3n,style:style()});await recovery.dispose();}
 finally{release();await pending.catch(()=>{});if(index)await index.dispose();await old.dispose();await source.dispose();holder.dispose();}
});
function extension(command,handle,sequence=0n,payload,query){const request=canonical({command:query?5:6,handle,sequence,budget,payload,query});new DataView(request).setUint32(8,command,true);return request;}
for(const host of['native','wasm'])test(`${host} authentic selected Scene returns typed Unsupported and preserves old frame`,async()=>{const holder=await bridgeFor(host),execute=holder.bridge.execute;let builds=0;holder.bridge.execute=r=>{if(new DataView(r).getUint32(8,true)===37)builds++;return execute(r);};const {source,frame:old}=await setup(holder.bridge);let scope,selected;try{const payload=new Uint8Array(16),p=new DataView(payload.buffer);p.setBigUint64(0,777n,true);p.setBigUint64(8,U64,true);scope=ordinary(await holder.bridge.execute(extension(32,old.handle,1n,payload))).handle;const stateBytes=new Uint8Array(32),sv=new DataView(stateBytes.buffer);sv.setBigUint64(0,2n,true);stateBytes.set([0,255,0,255],8);sv.setBigUint64(16,1n,true);sv.setBigUint64(24,U64,true);const state=ordinary(await holder.bridge.execute(extension(33,scope,0n,stateBytes))).handle;const binding=new Uint8Array(8);new DataView(binding.buffer).setBigUint64(0,state,true);const q={...query(source.info),stateRevision:2n};await holder.bridge.execute(extension(35,source.handle,2n,binding,q));await driveGeoSession(holder.bridge,{handle:source.handle,sequence:2n,budget,readChunk:source.readChunk});selected=await prepareGeoSceneData(holder.bridge,{handle:source.handle,sequence:2n,budget,style:style()});attachRetainedFrame(source,selected,2n,extension(35,source.handle,2n,binding,q),style());assert.equal(new DataView(selected.data.packet).getUint32(4,true),2);await assert.rejects(GeoHierarchy.fromFrame(selected,source,storage(new Map())),e=>e instanceof GeoHierarchyUnsupportedSelected);assert.equal(builds,0);assert.equal(old.data.record(0).featureId,U64);assert.equal(isHierarchyFrame(selected),false);}finally{if(selected)await selected.dispose();await source.dispose();if(scope)await holder.bridge.execute(canonical({command:10,handle:scope}));await old.dispose();holder.dispose();}});
async function dense(bridge,multi){
 const accepted=multi?16385:32769,rows=accepted+2,vertices=accepted*(multi?2:1),xy=vertices*16,validity=(rows+7)&~7,offsetBytes=multi?((rows+1)*4+7)&~7:0,descriptor=new Uint8Array(64+xy+validity+rows*8+offsetBytes),v=new DataView(descriptor.buffer);descriptor.set([88,89,71,68]);[1,multi?4:1,4326,1,0].forEach((n,i)=>v.setUint32(4+i*4,n,true));v.setBigUint64(24,BigInt(rows),true);v.setBigUint64(32,BigInt(vertices),true);v.setBigUint64(40,multi?BigInt(rows+1):0n,true);descriptor.fill(1,64+xy,64+xy+accepted+(multi?1:0));const ids=64+xy+validity;for(let i=0;i<rows;i++)v.setBigUint64(ids+i*8,i%7?U64-BigInt(i):U64,true);if(multi)for(let i=0;i<=rows;i++)v.setUint32(ids+rows*8+i*4,Math.min(i,accepted)*2,true);
 const chunk=await bridge.read(encodeGeoChunkRequest({descriptor,rows},budget.processorBytes)),builder=ordinary(await bridge.execute(canonical({command:1}))).handle;let manifest;try{await bridge.execute(canonical({command:2,handle:builder,payload:chunk}));await bridge.execute(canonical({command:3,handle:builder,generation:U64}));manifest=await bridge.read(canonical({command:21,handle:builder}));}finally{await bridge.execute(canonical({command:10,handle:builder}));}const source=await RetainedGeoSource.create(manifest,()=>chunk,{budget,bridge}),q={...query(source.info),maxCells:1,time:{kind:0}};return{source,q,accepted,vertices,frame:await source.update(q,{sequence:1n,style:style()})};
}
for(const host of['native','wasm'])for(const multi of[false,true])test(`${host} ${multi?'MultiPoint':'Point'} reduced complete membership/full IDs/nulls after owner disposal`,async()=>{const holder=await bridgeFor(host),{source,q,accepted,vertices,frame:old}=await dense(holder.bridge,multi);let index,frame;
 try{index=await GeoHierarchy.fromFrame(old,source,storage(new Map()));frame=await index.update(q,{sequence:2n,style:style()});assert.equal(frame.data.aggregate,true);assert.equal(frame.data.length,1);assert.deepEqual(frame.data.scene,old.data.scene);assert.equal(frame.hierarchyStats.passes,2);await source.dispose();await index.dispose();await old.dispose();let cursor,total=0,page=0;do{let members=await frame.membership(0,{maxProjectedVertices:1000000n,cursor});try{const data=members.data;assert.ok(data.count<=4096n);for(let i=0;i<Number(data.count);i++){const r=data.record(i);assert.equal(r.sourceRow,BigInt(total+i));assert.equal(r.featureId,(total+i)%7?U64-BigInt(total+i):U64);}total+=Number(data.count);cursor=data.cursor?.slice();const stable=new Uint8Array(data.packet.slice(0));stable.fill(0,16,24);stable.fill(0,80,88);packets.push({host,kind:`members-${multi}-${page++}`,hash:createHash('sha256').update(stable).digest('hex')});}finally{await members.dispose();}}while(cursor);assert.equal(total,accepted);assert.equal(frame.data.identity.sourceRows,BigInt(accepted+2));packets.push({host,kind:`reduced-${multi}`,hash:createHash('sha256').update(frame.data.scene).digest('hex')});void vertices;}finally{if(frame)await frame.dispose();if(index)await index.dispose();await old.dispose();await source.dispose();holder.dispose();}});
test('two actual wasm modules with colliding Data handles cannot cross source authority',async()=>{const a=await bridgeFor('wasm'),b=await bridgeFor('wasm');let creates=0;const raw=b.bridge;b.bridge={read:r=>raw.read(r),execute:r=>{if(new DataView(r).getUint32(8,true)===37)creates++;return raw.execute(r);}};const first=await setup(a.bridge),second=await setup(b.bridge,true);let index;try{assert.equal(first.frame.handle,second.frame.handle);assert.notDeepEqual(first.source.info.digest,second.source.info.digest);first.frame._source=second.source;await assert.rejects(GeoHierarchy.fromFrame(first.frame,second.source,storage(new Map())),/another source or transport/);assert.equal(creates,0);index=await GeoHierarchy.fromFrame(second.frame,second.source,storage(new Map()));assert.equal(creates,1);}finally{if(index)await index.dispose();await first.frame.dispose();await second.frame.dispose();await first.source.dispose();await second.source.dispose();a.dispose();b.dispose();}});
for(const host of['native','wasm'])test(`${host} failed Scene and hierarchy disposal retries once after coalesced pending cleanup`,async()=>{const holder=await bridgeFor(host),native=holder.bridge;let failHandle,failed=false;holder.bridge={read:r=>native.read(r),execute:r=>{const v=new DataView(r);if(v.getUint32(8,true)===10&&v.getBigUint64(16,true)===failHandle&&!failed){failed=true;return Promise.reject(new Error('pre-Rust cleanup failure'));}return native.execute(r);}};const{source,frame:old}=await setup(holder.bridge);let index,frame;try{index=await GeoHierarchy.fromFrame(old,source,storage(new Map()));frame=await index.update(query(index.info),{sequence:2n,style:style()});failHandle=frame.handle;const one=frame.dispose(),two=frame.dispose();assert.equal(one,two);await assert.rejects(one,/cleanup failure/);assert.throws(()=>frame.data,/disposed/);await frame.dispose();await assert.rejects(native.read(canonical({command:23,handle:frame.handle})));failHandle=index.handle;failed=false;const first=index.dispose(),second=index.dispose();assert.equal(first,second);await assert.rejects(first,/cleanup failure/);await index.dispose();assert.equal(index.closed,true);assert.equal(old.data.record(0).featureId,U64);}finally{failed=true;if(frame)await frame.dispose();if(index)await index.dispose();await old.dispose();await source.dispose();holder.dispose();}});
test('native public static host accepts independently retained hierarchy frame',async()=>{
 const {geoChart,geoLayer}=await import('../src/charts.js');const holder=await bridgeFor('native'),{source,frame:old}=await setup(holder.bridge);let index,frame,host;
 try{index=await GeoHierarchy.fromFrame(old,source,storage(new Map()));const q=query(index.info);frame=await index.update(q,{sequence:2n,style:style()});const chart=geoChart(geoLayer('points',{source,layerId:U64,query:q,sequence:2n,style:style()}),{camera:q.camera});host=chart.host({frame});await host.anchorReady;assert.equal(isHierarchyFrame(host.anchor),true);await frame.dispose();await index.dispose();await source.dispose();const b=new ArrayBuffer(32),v=new DataView(b);new Uint8Array(b).set([88,89,71,72]);v.setUint32(4,1,true);v.setUint32(8,1,true);const result=await host.handle({type:'geo_host',request:'test',mount:'hierarchy'},[b]);assert.equal(result[0].error,undefined);assert.equal(host.frame.data.record(0).featureId,U64);const close=new ArrayBuffer(32),cv=new DataView(close);new Uint8Array(close).set([88,89,71,72]);cv.setUint32(4,1,true);cv.setUint32(8,4,true);cv.setBigUint64(16,host.frame.handle,true);cv.setBigUint64(24,2n,true);await host.handle({type:'geo_host',request:'close',mount:'hierarchy'},[close]);}
 finally{if(host)await host.close();if(frame)await frame.dispose();if(index)await index.dispose();await old.dispose();await source.dispose();holder.dispose();}
});
test('strict hierarchy reply parser rejects reserved bytes and native/wasm packets match',async()=>{const b=new ArrayBuffer(256),v=new DataView(b);new Uint8Array(b).set([88,89,71,90]);v.setUint32(4,1,true);v.setUint32(8,18,true);v.setBigUint64(16,1n,true);v.setBigUint64(24,U64,true);v.setBigUint64(48,1n,true);assert.equal(decodeGeoHierarchyReply(b).sequence,U64);new Uint8Array(b)[200]=1;assert.throws(()=>decodeGeoHierarchyReply(b),/reserved/);for(const kind of new Set(packets.map(p=>p.kind)))assert.equal(packets.find(p=>p.host==='native'&&p.kind===kind).hash,packets.find(p=>p.host==='wasm'&&p.kind===kind).hash);if(process.env.XYG_HIERARCHY_HOST_REPORT)await writeFile(process.env.XYG_HIERARCHY_HOST_REPORT,JSON.stringify({status:'passed',packets,claims:['actual native and packaged wasm32 thin hierarchy driver','exact Scene/Rows IDs and immutable lifetime','cancelled callback settlement/private ACK','mutation/backing budget rejection and old-frame recovery'],limitations:['no selected hierarchy','no massive host latency or browser paint claim']},null,2)+'\n');});
