/**
 * Series palette cursor cross-host parity: @curatelabs/xyg-node vs Python (#918).
 *
 * Asserts that Node's nextSeriesColor() produces the same default series colors
 * as Python's Figure.next_series_color(), for scatter, line, histogram, bar
 * (multi-series), segments, errorbar, and graph marks.
 *
 * The fixture is generated by::
 *
 *   uv run python tests/test_series_palette_cross_host.py --write
 *
 * and committed to tests/fixtures/series_palette_cross_host.json.
 */
import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

import { PROTOCOL_VERSION, abiVersion, figure } from "../src/index.js";

const fixture = JSON.parse(
  fs.readFileSync(
    new URL("../../../tests/fixtures/series_palette_cross_host.json", import.meta.url),
    "utf8",
  ),
);

/**
 * Extract the constant color string from a payload trace.
 *
 * Ribbon color is always null: Python ships ribbon paint as direct RGBA (not a
 * constant CSS string), so both sides return null and cursor behavior is
 * verified through the subsequent trace (#918).
 */
function resolveTraceColor(t) {
  if (t == null) return null;
  // Ribbon color is shipped as direct RGBA in Python — return null to match.
  if (t.kind === "ribbon") return null;
  const color = t.color;
  if (color != null && typeof color === "object" && color.mode === "constant") {
    return color.color ?? null;
  }
  const style = t.style;
  if (style != null && typeof style.color === "string") return style.color;
  return null;
}

function buildCase(name) {
  const entry = fixture.cases.find((c) => c.name === name);
  if (entry == null) throw new Error(`unknown case ${name}`);
  const palette = entry.palette ?? null;
  const baseOpts = { width: 240, height: 160, ...(palette != null ? { palette } : {}) };

  const fig = figure(baseOpts);

  if (name === "builtin_cursor_scatter_line_hist") {
    fig.scatter([0, 1], [0, 1]);
    fig.line([0, 1], [0, 1]);
    fig.histogram([1, 2, 3, 4]);
  } else if (name === "builtin_cursor_bar_2series") {
    fig.bar([0, 1, 2], [[1, 2, 3], [4, 5, 6]]);
  } else if (name === "builtin_cursor_segments_errorbar") {
    fig.segments([0, 1], [0, 1], [1, 2], [1, 2]);
    fig.errorbar([0, 1], [0.5, 1.5], { yerr: 0.1 });
  } else if (name === "custom_palette_cursor") {
    fig.scatter([0, 1], [0, 1]);
    fig.line([0, 1], [0, 1]);
    fig.histogram([1, 2, 3, 4]);
  } else if (name === "custom_palette_wrap") {
    fig.scatter([0, 1], [0, 1]);
    fig.line([0, 1], [0, 1]);
    // Suppress the RuntimeWarning for palette wrap
    const origEmit = process.emitWarning.bind(process);
    process.emitWarning = () => {};
    fig.histogram([1, 2, 3]);
    process.emitWarning = origEmit;
  } else if (name === "explicit_color_no_cursor") {
    // Explicit color= skips the cursor; the line takes slot 0.
    fig.scatter([0, 1], [0, 1], { color: "#abcdef" });
    fig.line([0, 1], [0, 1]);
  } else if (name === "graph_node_cursor_edge_neutral") {
    // Pre-graph scatter takes slot 0; graph node takes slot 1.
    // Graph edges use "#888888" by default (no cursor slot consumed).
    fig.scatter([0, 1], [0, 1]);
    fig.graph(["a", "b", "c"], [["a", "b"], ["b", "c"]]);
  } else if (name === "graph_custom_palette_node") {
    // Graph node takes slot 0 from the custom palette.
    // Graph edges use "#888888" by default (no cursor slot consumed).
    fig.graph(["a", "b", "c"], [["a", "b"], ["b", "c"]]);
  } else if (name === "heatmap_string_color") {
    fig.heatmap([[1, 2], [3, 4]], { rows: 2, cols: 2, color: "#ff00ff" });
    fig.line([0, 1], [0, 1]);
  } else if (name === "heatmap_no_color") {
    fig.heatmap([[1, 2], [3, 4]], { rows: 2, cols: 2 });
    fig.scatter([0, 1], [0, 1]);
  } else if (name === "heatmap_nonstring_color") {
    fig.scatter([0, 1], [0, 1]);
    fig.heatmap([[1, 2], [3, 4]], { rows: 2, cols: 2, color: [1.0, 0.0, 0.0] });
  } else if (name === "hexbin_cursor") {
    fig.hexbin(
      Float64Array.from({ length: 10 }, (_, i) => i),
      Float64Array.from({ length: 10 }, (_, i) => i),
    );
    fig.scatter([0, 1], [0, 1]);
  } else if (name === "ribbon_no_color") {
    const x0 = Float64Array.of(0, 1);
    const x1 = Float64Array.of(1, 2);
    const slo = Float64Array.of(0, 1);
    const shi = Float64Array.of(0.5, 1.5);
    const tlo = Float64Array.of(0, 1);
    const thi = Float64Array.of(0.5, 1.5);
    fig.ribbon(x0, x1, slo, shi, tlo, thi);
    fig.scatter([0, 1], [0, 1]);
  } else if (name === "ribbon_style_color") {
    const x0 = Float64Array.of(0, 1);
    const x1 = Float64Array.of(1, 2);
    const slo = Float64Array.of(0, 1);
    const shi = Float64Array.of(0.5, 1.5);
    const tlo = Float64Array.of(0, 1);
    const thi = Float64Array.of(0.5, 1.5);
    fig.ribbon(x0, x1, slo, shi, tlo, thi, { style: { color: "#ff1234" } });
    fig.scatter([0, 1], [0, 1]);
  } else if (name === "area_cursor") {
    fig.area([0, 1, 2], [0, 1, 0]);
    fig.scatter([0, 1], [0, 1]);
  } else if (name === "step_cursor") {
    fig.step([0, 1, 2], [0, 1, 0]);
    fig.scatter([0, 1], [0, 1]);
  } else if (name === "box_cursor") {
    fig.box([1, 2, 3, 4, 5]);
    fig.scatter([0, 1], [0, 1]);
  } else if (name === "violin_cursor") {
    fig.violin([1, 2, 3, 4, 5]);
    fig.scatter([0, 1], [0, 1]);
  } else if (name === "stem_cursor") {
    fig.stem([0, 1, 2], [1, 2, 3]);
    fig.scatter([0, 1], [0, 1]);
  } else if (name === "triangle_mesh_cursor") {
    fig.triangleMesh(
      Float64Array.of(0), Float64Array.of(0),
      Float64Array.of(1), Float64Array.of(0),
      Float64Array.of(0.5), Float64Array.of(1),
    );
    fig.scatter([0, 1], [0, 1]);
  } else if (name === "scatter_style_color_explicit") {
    fig.scatter([0, 1], [0, 1], { style: { color: "#aabbcc" } });
    fig.line([0, 1], [0, 1]);
  } else if (name === "bar_style_color_explicit") {
    fig.bar([0, 1, 2], [1, 2, 3], { style: { color: "#ff0000" } });
    fig.scatter([0, 1], [0, 1]);
  } else if (name === "bar_flat_multi_series") {
    // Flat Float64Array detected as 2 series by composeBar (finding 1).
    // Python equivalent: fig.bar([0,1,2], np.array([[1.,2.,3.],[4.,5.,6.]])).
    fig.bar([0, 1, 2], new Float64Array([1, 2, 3, 4, 5, 6]));
  } else {
    throw new Error(`unknown case ${name}`);
  }

  const { spec } = fig.buildPayload();
  return spec.traces.map((t) => ({ kind: t.kind, color: resolveTraceColor(t) }));
}

test("series-palette cross-host fixture contract", () => {
  assert.equal(fixture.schema, "xyg.series-palette-cross-host/v1");
  assert.equal(fixture.protocol, PROTOCOL_VERSION);
  assert.equal(Number(fixture.abi_version), abiVersion());
  assert.equal(fixture.cases.length, 23);
});

for (const entry of fixture.cases) {
  test(`Node series-palette cursor matches fixture for ${entry.name}`, () => {
    const traceColors = buildCase(entry.name);
    assert.equal(
      traceColors.length,
      entry.trace_colors.length,
      `trace count mismatch for ${entry.name}: Node ${traceColors.length} vs fixture ${entry.trace_colors.length}`,
    );
    for (let i = 0; i < entry.trace_colors.length; i += 1) {
      const nodeTrace = traceColors[i];
      const expected = entry.trace_colors[i];
      assert.equal(
        nodeTrace.kind,
        expected.kind,
        `${entry.name} trace[${i}] kind: Node=${nodeTrace.kind}, fixture=${expected.kind}`,
      );
      assert.equal(
        nodeTrace.color,
        expected.color,
        `${entry.name} trace[${i}] (${expected.kind}) color: Node=${nodeTrace.color}, fixture=${expected.color}`,
      );
    }
  });
}

test("default palettes warn when they wrap, with Python's messages (#918)", async () => {
  const { figure, DEFAULT_PALETTE } = await import("../src/index.js");
  const warnings = [];
  const onWarning = (warning) => warnings.push(warning.message);
  process.on("warning", onWarning);
  try {
    // The built-in palette: the ninth default series wraps.
    const builtin = figure();
    for (let i = 0; i <= DEFAULT_PALETTE.length; i += 1) builtin.scatter([0, 1], [0, 1]);
    // A custom palette: the third default series wraps.
    const custom = figure({ palette: ["#aa0000", "#00aa00"] });
    for (let i = 0; i < 3; i += 1) custom.scatter([0, 1], [0, 1]);
    await new Promise((resolve) => setImmediate(resolve));
  } finally {
    process.off("warning", onWarning);
  }
  assert.ok(warnings.some((m) => m.startsWith(`more than ${DEFAULT_PALETTE.length} series use default colors; the default palette repeats`)), warnings.join("\n"));
  assert.ok(warnings.some((m) => m.startsWith("more than 2 series use default colors; the chart palette repeats every 2")), warnings.join("\n"));
});
