"""Generated WASM aggregate limits; do not hand-edit."""
# Generated by scripts/gen_wasm_abi.py from spec/wasm/abi.json.

WASM_AGGREGATE_MAX_POINTS = 8000000
WASM_AGGREGATE_STREAM_CHUNK_POINTS = 32768
