//! Safe XYG engine: algorithms and deterministic product policy.
//!
//! This crate is `publish = false`. The public modules below are the
//! deliberate surface consumed by `xyg-core`; `font` and `simd` stay
//! crate-private. Unsafe Rust is confined to `simd.rs` (documented
//! `#[target_feature]` exception). Chart algorithms live here, not in the
//! C ABI shell.

#[cfg(feature = "raster")]
#[allow(dead_code)] // generated by scripts/gen_font.py; some metrics unused by the rasterizer
mod font;
mod simd;

pub mod autorange;
pub use autorange::{auto_domain, figure_autorange, rect_zero_baseline_flags};
#[cfg(not(target_family = "wasm"))]
pub mod chunked_columns;
pub mod css;
pub mod dashboard;
pub mod edge_route;
pub mod geo;
pub mod geo_viewport;
pub mod geom;
pub mod graph;
pub mod graph_style;
pub mod hexbin;
#[cfg(feature = "raster")]
pub mod jpeg;
pub mod kernels;
pub mod legend_fit;
pub mod lod_plan;
#[cfg(feature = "raster")]
pub mod pdf;
#[cfg(feature = "raster")]
pub mod png_encode;
pub mod projection;
#[cfg(feature = "raster")]
pub mod raster;
pub mod sankey;
pub mod scene;
mod scene_export;
#[cfg(feature = "raster")]
pub mod webp;
pub use scene_export::{scene_figure_support_reason, scene_public_export_reason};
pub mod scene_pack;
pub use scene_pack::pack_trace;
pub mod scene_legend;
pub use scene_legend::pack_legend;
pub mod scene_colorbar;
pub use scene_colorbar::pack_colorbar;
pub mod scene_annotations;
pub use scene_annotations::pack_annotations;
pub mod scene_style;
pub use scene_style::{resolve_chrome_style, resolve_mark_styles};
pub mod stats;
pub mod stream;
pub mod svg;
pub mod temporal;
pub mod temporal_controller;
pub mod temporal_graph;
#[cfg(not(target_family = "wasm"))]
pub mod tile_store;
pub mod tiles;
pub mod transition;
