//! Safe XYG engine: algorithms and deterministic product policy.
//!
//! This crate is `publish = false`. The public modules below are the
//! deliberate surface consumed by `xyg-core`; `font` and `simd` stay
//! crate-private. Unsafe Rust is confined to `simd.rs` (documented
//! `#[target_feature]` exception). Chart algorithms live here, not in the
//! C ABI shell.

#[allow(dead_code)] // generated by scripts/gen_font.py; some metrics unused by the rasterizer
mod font;
mod simd;

pub mod css;
pub mod graph;
pub mod hexbin;
pub mod kernels;
pub mod lod_plan;
pub mod raster;
pub mod sankey;
pub mod scene;
pub mod stats;
pub mod stream;
pub mod svg;
pub mod tiles;
pub mod transition;
