#!/usr/bin/env python3
"""Generate the thin browser adapter for the raw xyg-wasm export manifest."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "spec" / "wasm" / "abi.json"
RUST = ROOT / "crates" / "xyg-wasm" / "src" / "lib.rs"
OUTPUT = ROOT / "js" / "src" / "wasm_abi_generated.ts"


def render(manifest: dict[str, object]) -> str:
    abi_version = int(manifest["abi_version"])
    scene_version = int(manifest["scene_version"])
    painter_version = int(manifest["painter_version"])
    painter_header_bytes = int(manifest["painter_header_bytes"])
    painter_trace_bytes = int(manifest["painter_trace_bytes"])
    painter_tick_bytes = int(manifest["painter_tick_bytes"])
    painter_max_traces = int(manifest["painter_max_traces"])
    typed_series_version = int(manifest["typed_series_version"])
    typed_series_header_bytes = int(manifest["typed_series_header_bytes"])
    typed_series_descriptor_bytes = int(manifest["typed_series_descriptor_bytes"])
    typed_series_max_series = int(manifest["typed_series_max_series"])
    typed_series_max_records = int(manifest["typed_series_max_records"])
    typed_series_max_text_bytes = int(manifest["typed_series_max_text_bytes"])
    typed_series_max_symbol_code = int(manifest["typed_series_max_symbol_code"])
    typed_series_peak_fixed_bytes = int(manifest["typed_series_peak_fixed_bytes"])
    typed_series_peak_bytes_per_record = int(manifest["typed_series_peak_bytes_per_record"])
    typed_series_peak_bytes_per_series = int(manifest["typed_series_peak_bytes_per_series"])
    typed_series_peak_input_multiplier = int(manifest["typed_series_peak_input_multiplier"])
    max_arena_bytes = int(manifest["max_arena_bytes"])
    painter_max_legend_bytes = int(manifest["painter_max_legend_bytes"])
    statuses = manifest["statuses"]
    exports = manifest["exports"]
    if not isinstance(statuses, dict) or not isinstance(exports, list):
        raise ValueError("statuses and exports must be structured values")

    lines = [
        "// Generated by scripts/gen_wasm_abi.py from spec/wasm/abi.json.",
        "// Do not hand-edit raw WASM signatures or status numbers here.",
        "",
        f"export const XYG_WASM_ABI_VERSION = {abi_version} as const;",
        f"export const XYG_WASM_SCENE_VERSION = {scene_version} as const;",
        f"export const XYG_WASM_PAINTER_VERSION = {painter_version} as const;",
        f"export const XYG_WASM_PAINTER_HEADER_BYTES = {painter_header_bytes} as const;",
        f"export const XYG_WASM_PAINTER_TRACE_BYTES = {painter_trace_bytes} as const;",
        f"export const XYG_WASM_PAINTER_TICK_BYTES = {painter_tick_bytes} as const;",
        f"export const XYG_WASM_PAINTER_MAX_TRACES = {painter_max_traces} as const;",
        f"export const XYG_WASM_TYPED_SERIES_VERSION = {typed_series_version} as const;",
        f"export const XYG_WASM_TYPED_SERIES_HEADER_BYTES = {typed_series_header_bytes} as const;",
        f"export const XYG_WASM_TYPED_SERIES_DESCRIPTOR_BYTES = {typed_series_descriptor_bytes} as const;",
        f"export const XYG_WASM_TYPED_SERIES_MAX_SERIES = {typed_series_max_series} as const;",
        f"export const XYG_WASM_TYPED_SERIES_MAX_RECORDS = {typed_series_max_records} as const;",
        f"export const XYG_WASM_TYPED_SERIES_MAX_TEXT_BYTES = {typed_series_max_text_bytes} as const;",
        f"export const XYG_WASM_TYPED_SERIES_MAX_SYMBOL_CODE = {typed_series_max_symbol_code} as const;",
        f"export const XYG_WASM_TYPED_SERIES_PEAK_FIXED_BYTES = {typed_series_peak_fixed_bytes} as const;",
        f"export const XYG_WASM_TYPED_SERIES_PEAK_BYTES_PER_RECORD = {typed_series_peak_bytes_per_record} as const;",
        f"export const XYG_WASM_TYPED_SERIES_PEAK_BYTES_PER_SERIES = {typed_series_peak_bytes_per_series} as const;",
        f"export const XYG_WASM_TYPED_SERIES_PEAK_INPUT_MULTIPLIER = {typed_series_peak_input_multiplier} as const;",
        f"export const XYG_WASM_MAX_ARENA_BYTES = {max_arena_bytes} as const;",
        f"export const XYG_WASM_PAINTER_MAX_LEGEND_BYTES = {painter_max_legend_bytes} as const;",
        "export const XYG_WASM_STATUS = {",
    ]
    for name, value in statuses.items():
        lines.append(f"  {name}: {int(value)},")
    lines.extend(["} as const;", "", "export interface XygWasmExports {"])
    lines.append("  memory: WebAssembly.Memory;")
    for item in exports:
        if not isinstance(item, dict):
            raise ValueError("export entries must be objects")
        name = str(item["name"])
        params_spec = item.get("params")
        result_spec = item.get("result")
        if not isinstance(params_spec, list) or not all(
            isinstance(value, str) for value in params_spec
        ):
            raise ValueError(f"{name} params must be a string list")
        if not isinstance(result_spec, str):
            raise ValueError(f"{name} result must be a string")
        arity = len(params_spec)
        params = ", ".join(f"arg{index}: number" for index in range(arity))
        lines.append(f"  {name}({params}): number;")
    lines.extend(
        [
            "}",
            "",
            "export function bindXygWasmExports(instance: WebAssembly.Instance): XygWasmExports {",
            "  const raw = instance.exports as Record<string, unknown>;",
            "  if (!(raw.memory instanceof WebAssembly.Memory)) {",
            '    throw new Error("XYG WASM export memory is missing");',
            "  }",
        ]
    )
    for item in exports:
        name = str(item["name"])
        arity = len(item["params"])
        lines.extend(
            [
                f'  if (typeof raw.{name} !== "function" || (raw.{name} as Function).length !== {arity}) {{',
                f'    throw new Error("XYG WASM export {name} has an incompatible signature");',
                "  }",
            ]
        )
    lines.extend(
        [
            "  const bound = raw as unknown as XygWasmExports;",
            "  if (bound.xyg_wasm_abi_version() !== XYG_WASM_ABI_VERSION) {",
            '    throw new Error("XYG WASM ABI version is incompatible");',
            "  }",
            "  if (bound.xyg_wasm_scene_version() !== XYG_WASM_SCENE_VERSION) {",
            '    throw new Error("XYG canonical scene version is incompatible");',
            "  }",
            "  return bound;",
            "}",
            "",
            "export function readXygWasmError(exports: XygWasmExports, handle: number): string {",
            "  const ptr = exports.xyg_wasm_last_error_ptr(handle) >>> 0;",
            "  const len = exports.xyg_wasm_last_error_len(handle) >>> 0;",
            '  if (!ptr || !len) return "XYG WASM operation failed";',
            "  const end = ptr + len;",
            "  if (!Number.isSafeInteger(end) || end > exports.memory.buffer.byteLength) {",
            '    return "XYG WASM returned an invalid error range";',
            "  }",
            "  return new TextDecoder().decode(new Uint8Array(exports.memory.buffer, ptr, len));",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def verify_rust(manifest: dict[str, object]) -> None:
    source = RUST.read_text(encoding="utf-8")
    constants = {
        "WASM_ABI_VERSION": int(manifest["abi_version"]),
        "SCENE_VERSION": int(manifest["scene_version"]),
    }
    abi_match = re.search(r"pub const WASM_ABI_VERSION: u32 = (\d+);", source)
    if not abi_match or int(abi_match.group(1)) != constants["WASM_ABI_VERSION"]:
        raise SystemExit("xyg-wasm WASM_ABI_VERSION differs from spec/wasm/abi.json")
    engine = (ROOT / "crates" / "xyg-engine" / "src" / "scene.rs").read_text(encoding="utf-8")
    scene_match = re.search(r"pub const SCENE_VERSION: u32 = (\d+);", engine)
    if not scene_match or int(scene_match.group(1)) != constants["SCENE_VERSION"]:
        raise SystemExit("xyg-engine SCENE_VERSION differs from spec/wasm/abi.json")
    painter_match = re.search(r"pub const BROWSER_PAINTER_VERSION: u32 = (\d+);", engine)
    if not painter_match or int(painter_match.group(1)) != int(manifest["painter_version"]):
        raise SystemExit("xyg-engine BROWSER_PAINTER_VERSION differs from spec/wasm/abi.json")
    for rust_name, manifest_name in (
        ("BROWSER_PAINTER_HEADER_BYTES", "painter_header_bytes"),
        ("BROWSER_PAINTER_TRACE_BYTES", "painter_trace_bytes"),
        ("BROWSER_PAINTER_TICK_BYTES", "painter_tick_bytes"),
        ("MAX_BROWSER_PAINTER_TRACES", "painter_max_traces"),
        ("BROWSER_PAINTER_MAX_LEGEND_BYTES", "painter_max_legend_bytes"),
    ):
        match = re.search(rf"pub const {rust_name}: usize = (\d+);", engine)
        if not match or int(match.group(1)) != int(manifest[manifest_name]):
            raise SystemExit(f"xyg-engine {rust_name} differs from spec/wasm/abi.json")
    compile_source = (ROOT / "crates" / "xyg-wasm" / "src" / "compile.rs").read_text(
        encoding="utf-8"
    )
    for rust_name, manifest_name in (
        ("SERIES_VERSION", "typed_series_version"),
        ("COMPILE_HEADER_BYTES", "typed_series_header_bytes"),
        ("SERIES_DESCRIPTOR_BYTES", "typed_series_descriptor_bytes"),
        ("MAX_SERIES", "typed_series_max_series"),
        ("MAX_RECORDS", "typed_series_max_records"),
        ("MAX_TEXT_BYTES", "typed_series_max_text_bytes"),
        ("MAX_SYMBOL_CODE", "typed_series_max_symbol_code"),
        ("SERIES_PEAK_FIXED_BYTES", "typed_series_peak_fixed_bytes"),
        ("SERIES_PEAK_BYTES_PER_RECORD", "typed_series_peak_bytes_per_record"),
        ("SERIES_PEAK_BYTES_PER_SERIES", "typed_series_peak_bytes_per_series"),
        ("SERIES_PEAK_INPUT_MULTIPLIER", "typed_series_peak_input_multiplier"),
    ):
        match = re.search(rf"pub const {rust_name}: (?:u32|usize) = ([0-9_]+);", compile_source)
        if not match or int(match.group(1).replace("_", "")) != int(manifest[manifest_name]):
            raise SystemExit(f"xyg-wasm {rust_name} differs from spec/wasm/abi.json")
    arena_match = re.search(r"pub const MAX_ARENA_BYTES: usize = ([0-9_]+);", source)
    if not arena_match or int(arena_match.group(1).replace("_", "")) != int(
        manifest["max_arena_bytes"]
    ):
        raise SystemExit("xyg-wasm MAX_ARENA_BYTES differs from spec/wasm/abi.json")
    for name, value in manifest["statuses"].items():
        match = re.search(rf"pub const STATUS_{re.escape(str(name))}: i32 = (\d+);", source)
        if not match or int(match.group(1)) != int(value):
            raise SystemExit(f"xyg-wasm STATUS_{name} differs from spec/wasm/abi.json")
    for item in manifest["exports"]:
        name = str(item["name"])
        signature = re.search(
            rf'pub extern "C" fn {re.escape(name)}\s*\((.*?)\)\s*->\s*([A-Za-z0-9_:]+)\s*\{{',
            source,
            re.DOTALL,
        )
        if not signature:
            raise SystemExit(f"manifest export missing from xyg-wasm: {name}")
        params = []
        for parameter in signature.group(1).split(","):
            parameter = parameter.strip()
            if not parameter:
                continue
            if ":" not in parameter:
                raise SystemExit(f"cannot parse Rust parameter for {name}: {parameter}")
            params.append(parameter.split(":", 1)[1].strip())
        expected_params = [str(value) for value in item["params"]]
        expected_result = str(item["result"])
        if params != expected_params or signature.group(2) != expected_result:
            raise SystemExit(
                f"xyg-wasm signature differs for {name}: "
                f"Rust ({params}) -> {signature.group(2)}, "
                f"manifest ({expected_params}) -> {expected_result}"
            )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if manifest.get("schema_version") != 1:
        raise SystemExit("unsupported WASM ABI manifest schema")
    verify_rust(manifest)
    expected = render(manifest)
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            raise SystemExit(f"generated WASM adapter is stale: run {Path(__file__).name}")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
