#!/usr/bin/env python3
"""Generate the thin browser adapter for the raw xyg-wasm export manifest."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "spec" / "wasm" / "abi.json"
RUST = ROOT / "crates" / "xyg-wasm" / "src" / "lib.rs"
OUTPUT = ROOT / "js" / "src" / "wasm_abi_generated.ts"


def render(manifest: dict[str, object]) -> str:
    abi_version = int(manifest["abi_version"])
    scene_version = int(manifest["scene_version"])
    statuses = manifest["statuses"]
    exports = manifest["exports"]
    if not isinstance(statuses, dict) or not isinstance(exports, list):
        raise ValueError("statuses and exports must be structured values")

    lines = [
        "// Generated by scripts/gen_wasm_abi.py from spec/wasm/abi.json.",
        "// Do not hand-edit raw WASM signatures or status numbers here.",
        "",
        f"export const XYG_WASM_ABI_VERSION = {abi_version} as const;",
        f"export const XYG_WASM_SCENE_VERSION = {scene_version} as const;",
        "export const XYG_WASM_STATUS = {",
    ]
    for name, value in statuses.items():
        lines.append(f"  {name}: {int(value)},")
    lines.extend(["} as const;", "", "export interface XygWasmExports {"])
    lines.append("  memory: WebAssembly.Memory;")
    for item in exports:
        if not isinstance(item, dict):
            raise ValueError("export entries must be objects")
        name = str(item["name"])
        arity = int(item["arity"])
        params = ", ".join(f"arg{index}: number" for index in range(arity))
        lines.append(f"  {name}({params}): number;")
    lines.extend(
        [
            "}",
            "",
            "export function bindXygWasmExports(instance: WebAssembly.Instance): XygWasmExports {",
            "  const raw = instance.exports as Record<string, unknown>;",
            "  if (!(raw.memory instanceof WebAssembly.Memory)) {",
            '    throw new Error("XYG WASM export memory is missing");',
            "  }",
        ]
    )
    for item in exports:
        name = str(item["name"])
        arity = int(item["arity"])
        lines.extend(
            [
                f'  if (typeof raw.{name} !== "function" || (raw.{name} as Function).length !== {arity}) {{',
                f'    throw new Error("XYG WASM export {name} has an incompatible signature");',
                "  }",
            ]
        )
    lines.extend(
        [
            "  const bound = raw as unknown as XygWasmExports;",
            "  if (bound.xyg_wasm_abi_version() !== XYG_WASM_ABI_VERSION) {",
            '    throw new Error("XYG WASM ABI version is incompatible");',
            "  }",
            "  if (bound.xyg_wasm_scene_version() !== XYG_WASM_SCENE_VERSION) {",
            '    throw new Error("XYG canonical scene version is incompatible");',
            "  }",
            "  return bound;",
            "}",
            "",
            "export function readXygWasmError(exports: XygWasmExports, handle: number): string {",
            "  const ptr = exports.xyg_wasm_last_error_ptr(handle);",
            "  const len = exports.xyg_wasm_last_error_len(handle);",
            '  if (!ptr || !len) return "XYG WASM operation failed";',
            "  const end = ptr + len;",
            "  if (!Number.isSafeInteger(end) || end > exports.memory.buffer.byteLength) {",
            '    return "XYG WASM returned an invalid error range";',
            "  }",
            "  return new TextDecoder().decode(new Uint8Array(exports.memory.buffer, ptr, len));",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def verify_rust(manifest: dict[str, object]) -> None:
    source = RUST.read_text(encoding="utf-8")
    constants = {
        "WASM_ABI_VERSION": int(manifest["abi_version"]),
        "SCENE_VERSION": int(manifest["scene_version"]),
    }
    abi_match = re.search(r"pub const WASM_ABI_VERSION: u32 = (\d+);", source)
    if not abi_match or int(abi_match.group(1)) != constants["WASM_ABI_VERSION"]:
        raise SystemExit("xyg-wasm WASM_ABI_VERSION differs from spec/wasm/abi.json")
    engine = (ROOT / "crates" / "xyg-engine" / "src" / "scene.rs").read_text(encoding="utf-8")
    scene_match = re.search(r"pub const SCENE_VERSION: u32 = (\d+);", engine)
    if not scene_match or int(scene_match.group(1)) != constants["SCENE_VERSION"]:
        raise SystemExit("xyg-engine SCENE_VERSION differs from spec/wasm/abi.json")
    for name, value in manifest["statuses"].items():
        match = re.search(rf"pub const STATUS_{re.escape(str(name))}: i32 = (\d+);", source)
        if not match or int(match.group(1)) != int(value):
            raise SystemExit(f"xyg-wasm STATUS_{name} differs from spec/wasm/abi.json")
    for item in manifest["exports"]:
        name = str(item["name"])
        if not re.search(rf'pub extern "C" fn {re.escape(name)}\s*\(', source):
            raise SystemExit(f"manifest export missing from xyg-wasm: {name}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if manifest.get("schema_version") != 1:
        raise SystemExit("unsupported WASM ABI manifest schema")
    verify_rust(manifest)
    expected = render(manifest)
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            raise SystemExit(f"generated WASM adapter is stale: run {Path(__file__).name}")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
