#!/usr/bin/env node
// Raw typed extension proof. Geometry, selection and count policy remain in Rust.
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {gzipSync} from 'node:zlib';
import {encodeGeoScaleRequest as encode,decodeGeoScaleReply as decode,encodeGeoChunkRequest,encodeGeoScaleStyle,driveGeoSession,prepareGeoSceneData,parseGeoMembershipData,nativeGeoScaleBridge} from '../packages/xy-node/src/geoscale.js';
const budget={processorBytes:128<<20,maxRowsExamined:1000000n,maxReadBytes:128n<<20n,maxChunks:65536,pageRows:4096};
const MAX=(1n<<64n)-1n,MIN=-(1n<<63n),MAX_TIME=(1n<<63n)-1n;
const style=encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0});
function request(command,handle=0n,sequence=0n,payload,query){const b=encode({command:query?5:6,handle,sequence,budget,payload,query});new DataView(b).setUint32(8,command,true);return b;}
function reply(b){assert.equal(b.byteLength,256);const v=new DataView(b);assert.equal(v.getUint32(0,true),0x5a475958);return {code:v.getUint32(8,true),handle:v.getBigUint64(16,true),sequence:v.getBigUint64(24,true),length:v.getBigUint64(32,true),ticket:new Uint8Array(b,64,128).slice(),view:v};}
function descriptor(multi){const vertices=multi?6:3,offsetCount=multi?5:0,out=new Uint8Array(64+vertices*16+8+32+(multi?24:0)),v=new DataView(out.buffer);out.set([88,89,71,68]);[1,multi?4:1,4326,1,0].forEach((n,i)=>v.setUint32(4+i*4,n,true));v.setBigUint64(24,4n,true);v.setBigUint64(32,BigInt(vertices),true);v.setBigUint64(40,BigInt(offsetCount),true);let at=64;for(let row=0;row<3;row++)for(let vertex=0;vertex<(multi?2:1);vertex++){v.setFloat64(at,(row-1)*0.0001+vertex*1e-7,true);v.setFloat64(at+8,0,true);at+=16;}out.set([1,1,1,0],at);at+=8;[MAX,9007199254740993n,MAX,1n<<63n].forEach((n,i)=>v.setBigUint64(at+i*8,n,true));at+=32;if(multi)[0,2,4,6,6].forEach((n,i)=>v.setUint32(at+i*4,n,true));return out;}
const wasmPath=process.env.XYG_HIERARCHY_WASM??'packages/xy-client/dist/xyg-wasm.wasm',artifact=await readFile(wasmPath);
const {instance}=await WebAssembly.instantiate(artifact,{}),x=instance.exports,wasmInstance=x.xyg_wasm_instance_new(budget.processorBytes);assert.ok(wasmInstance);let wireSeq=0;
async function call(b,read){assert.equal(x.xyg_wasm_arena_resize(wasmInstance,b.byteLength),0);new Uint8Array(x.memory.buffer,x.xyg_wasm_arena_ptr(wasmInstance)>>>0,b.byteLength).set(new Uint8Array(b));const status=x[read?'xyg_wasm_geo_scale_read':'xyg_wasm_geo_scale_execute'](wasmInstance,++wireSeq,0,b.byteLength);if(status)throw Error(`WASM status${status}:`+new TextDecoder().decode(new Uint8Array(x.memory.buffer,x.xyg_wasm_last_error_ptr(wasmInstance)>>>0,x.xyg_wasm_last_error_len(wasmInstance))));return new Uint8Array(x.memory.buffer,x.xyg_wasm_output_ptr(wasmInstance)>>>0,x.xyg_wasm_output_len(wasmInstance)).slice().buffer;}
const wasm={execute:b=>call(b,false),read:b=>call(b,true)};
function stable(b){const out=new Uint8Array(b).slice();out.fill(0,16,24);return out;}
async function run(bridge,multi){
 const chunk=await bridge.read(encodeGeoChunkRequest({descriptor:descriptor(multi),rows:4,intervals:{starts:BigInt64Array.of(MIN,0n,10n,0n),ends:BigInt64Array.of(0n,10n,0n,0n),startValidity:Uint8Array.of(0,1,1,0),endValidity:Uint8Array.of(1,1,0,0)}},budget.processorBytes));
 const builder=decode(await bridge.execute(encode({command:1}))).handle,owners=new Map(),storage=new Map(),outputs=[];const track=(h,s=0n)=>{owners.set(h,s);return h;};track(builder);const close=async h=>{await bridge.execute(request(10,h,owners.get(h)??0n));owners.delete(h);};
 const buildPayload=new Uint8Array(24),bp=new DataView(buildPayload.buffer);bp.setUint32(0,1024,true);bp.setBigUint64(8,1000000n,true);bp.setBigUint64(16,64n<<20n,true);
 const createBuild=async frame=>track(reply(await bridge.execute(request(37,frame,1n,buildPayload))).handle,1n);
 async function drive(h,seq,done,corrupt=false){for(;;){const s=reply(await bridge.execute(request(6,h,seq)));if(s.code===done)return s;if(![1,7].includes(s.code))throw Error(`unexpected hierarchy${s.code}`);const t=s.ticket,tv=new DataView(t.buffer),kind=tv.getUint32(32,true),length=Number(tv.getBigUint64(48,true)),key=`${tv.getBigUint64(8,true)}:${tv.getBigUint64(40,true)}`;assert.ok(length<=16<<20);let held,p;
  try{if(kind===3){held=await bridge.read(request(40,h,seq,t));assert.equal(held.byteLength,length);storage.set(key,new Uint8Array(held).slice());}else{held=kind===1?chunk:storage.get(key);assert.ok(held);let bytes=held instanceof ArrayBuffer?new Uint8Array(held):held;assert.equal(bytes.length,length);if(corrupt&&kind!==1){bytes=bytes.slice();bytes[bytes.length-1]^=1;p=new Uint8Array(128+length);p.set(t);p.set(bytes,128);await assert.rejects(bridge.execute(request(7,h,seq,p)));return {code:'corrupt'};}p=new Uint8Array(128+length);p.set(t);p.set(bytes,128);await bridge.execute(request(7,h,seq,p));}}
  finally{held=undefined;p=undefined;await bridge.execute(request(kind===3?41:8,h,seq,t));}
 }}
 try{
 await bridge.execute(encode({command:2,handle:builder,payload:new Uint8Array(chunk)}));await bridge.execute(encode({command:3,handle:builder,generation:MAX}));const manifest=await bridge.read(encode({command:21,handle:builder}));const source=track(decode(await bridge.execute(encode({command:4,payload:new Uint8Array(manifest),budget}))).handle),readChunk=async()=>chunk,info=(await driveGeoSession(bridge,{handle:source,sequence:0n,budget,readChunk})).source;
 const base={camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:8,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:32768,previousDirect:true,sourceDigest:info.digest,generation:MAX,layerId:MAX,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:0},maxProjectedVertices:1000000n};
 await bridge.execute(encode({command:5,handle:source,sequence:1n,budget,query:base}));await driveGeoSession(bridge,{handle:source,sequence:1n,budget,readChunk});const initial=await prepareGeoSceneData(bridge,{handle:source,sequence:1n,budget,style});track(initial.handle);
 // Cancelled read and write loans settle only with the exact private ticket.
 let cancel=await createBuild(initial.handle),s=reply(await bridge.execute(request(6,cancel,1n)));await bridge.execute(request(9,cancel,1n));assert.equal(reply(await bridge.execute(request(10,cancel,1n))).code,2);let forged=s.ticket.slice();forged[8]^=1;await assert.rejects(bridge.execute(request(8,cancel,1n,forged)));await bridge.execute(request(8,cancel,1n,s.ticket));await close(cancel);
 cancel=await createBuild(initial.handle);s=reply(await bridge.execute(request(6,cancel,1n)));let p=new Uint8Array(128+chunk.byteLength);p.set(s.ticket);p.set(new Uint8Array(chunk),128);await bridge.execute(request(7,cancel,1n,p));p=undefined;await bridge.execute(request(8,cancel,1n,s.ticket));s=reply(await bridge.execute(request(6,cancel,1n)));assert.equal(s.code,7);await bridge.read(request(40,cancel,1n,s.ticket));await bridge.read(request(40,cancel,1n,s.ticket));await assert.rejects(bridge.read(request(40,cancel,1n,s.ticket)));await bridge.execute(request(9,cancel,1n));assert.equal(reply(await bridge.execute(request(10,cancel,1n))).code,2);forged=s.ticket.slice();forged[16]^=1;await assert.rejects(bridge.execute(request(41,cancel,1n,forged)));await bridge.execute(request(41,cancel,1n,s.ticket));await close(cancel);
 const malformed=buildPayload.slice();malformed[4]=1;await assert.rejects(bridge.execute(request(37,initial.handle,1n,malformed)));const low=request(37,initial.handle,1n,buildPayload);new DataView(low).setBigUint64(32,4096n,true);await assert.rejects(bridge.execute(low));
 const index=await createBuild(initial.handle);const ready=await drive(index,1n,18);assert.ok(ready.view.getBigUint64(48,true)>0n);await close(initial.handle);
 const times=[{kind:0},{kind:1,instant:MIN},{kind:1,instant:0n},{kind:1,instant:10n},{kind:2,start:0n,end:10n},{kind:2,start:MIN,end:0n},{kind:1,instant:MAX_TIME},{kind:2,start:10n,end:MAX_TIME}];let lastQuery,lastFrame;
 for(let i=0;i<times.length;i++){const seq=BigInt(i+2),q={...base,time:times[i],camera:{...base.camera,crs:i%2?3857:4326,pitch:i%2?60:0},cameraRevision:seq,timeRevision:seq,layerRevision:seq,styleRevision:seq,stateRevision:seq};lastQuery=q;await bridge.execute(encode({command:5,handle:source,sequence:seq,budget,query:q}));await driveGeoSession(bridge,{handle:source,sequence:seq,budget,readChunk});const reference=await prepareGeoSceneData(bridge,{handle:source,sequence:seq,budget,style});track(reference.handle);
 const h=track(reply(await bridge.execute(request(38,index,seq,undefined,q))).handle,seq),complete=await drive(h,seq,19);assert.ok(complete.view.getBigUint64(184,true)>0n);const receipt=reply(await bridge.execute(request(39,h,seq,style))),d=track(receipt.handle),bytes=await bridge.read(request(23,d)),dv=new DataView(bytes);assert.equal(bytes.byteLength,Number(receipt.length));assert.equal(dv.getBigUint64(48,true),BigInt((i===0?3:1)*(multi?2:1)));const referenceBytes=reference.data.packet;const n=Number(dv.getBigUint64(32,true));assert.deepEqual(new Uint8Array(bytes,256,n),new Uint8Array(referenceBytes,256,Number(new DataView(referenceBytes).getBigUint64(32,true))));outputs.push(stable(bytes));await close(reference.handle);await close(h);if(lastFrame)await close(lastFrame);lastFrame=d;
 }
 // Paged rows and retain keep exact authority after source and hierarchy disposal.
 const rows=track(reply(await bridge.execute(request(15,lastFrame,9n))).handle);await driveGeoSession(bridge,{handle:rows,sequence:9n,budget,readChunk});const rowData=track(reply(await bridge.execute(request(16,rows,9n))).handle),rowBytes=await bridge.read(request(23,rowData));outputs.push(stable(rowBytes));await close(rows);await close(rowData);
 const retained=track(reply(await bridge.execute(request(26,lastFrame,9n))).handle);const retainedBytes=await bridge.read(request(23,retained));assert.deepEqual(stable(retainedBytes),outputs[7]);
 // Corrupt authenticated page and source/revision failure preserve old SceneData.
 const q10={...lastQuery,cameraRevision:10n,timeRevision:10n,layerRevision:10n,styleRevision:10n,stateRevision:10n};let bad=track(reply(await bridge.execute(request(38,index,10n,undefined,q10))).handle,10n);assert.equal((await drive(bad,10n,19,true)).code,'corrupt');await close(bad);await assert.rejects(bridge.execute(request(38,index,10n,undefined,q10)));const changed={...q10,camera:{...q10.camera,centerX:1}};await assert.rejects(bridge.execute(request(38,index,11n,undefined,changed)));
 const work=request(38,index,11n,undefined,{...q10,cameraRevision:11n,timeRevision:11n,layerRevision:11n,styleRevision:11n,stateRevision:11n,time:{kind:0}});new DataView(work).setBigUint64(40,1n,true);bad=track(reply(await bridge.execute(work)).handle,11n);const fallback=await drive(bad,11n,10);assert.equal(fallback.view.getUint32(48,true),2);await assert.rejects(bridge.execute(request(39,bad,11n,style)));await close(bad);
 // Selected canonical source builds a scoped root; query routing is proved separately.
 const scopePayload=new Uint8Array(16),sp=new DataView(scopePayload.buffer);sp.setBigUint64(0,777n,true);sp.setBigUint64(8,MAX,true);const scope=track(reply(await bridge.execute(request(32,lastFrame,9n,scopePayload))).handle);const selectedPayload=new Uint8Array(32),sv=new DataView(selectedPayload.buffer);sv.setBigUint64(0,10n,true);selectedPayload.set([0,255,0,255],8);sv.setBigUint64(16,1n,true);sv.setBigUint64(24,MAX,true);const state=reply(await bridge.execute(request(33,scope,0n,selectedPayload))).handle;const stateBytes=new Uint8Array(8);new DataView(stateBytes.buffer).setBigUint64(0,state,true);await bridge.execute(request(35,source,10n,stateBytes,{...lastQuery,stateRevision:10n}));await driveGeoSession(bridge,{handle:source,sequence:10n,budget,readChunk});const selected=track(reply(await bridge.execute(request(11,source,10n,style))).handle);const selectedBytes=await bridge.read(request(23,selected));assert.equal(new DataView(selectedBytes).getUint32(4,true),2);const selectedIndex=track(reply(await bridge.execute(request(37,selected,10n,buildPayload))).handle,10n);assert.equal((await drive(selectedIndex,10n,18)).code,18);await close(source);await close(selected);await close(selectedIndex);await close(scope);
 await close(index);assert.deepEqual(stable(await bridge.read(request(23,lastFrame))),outputs[7]);await close(lastFrame);assert.deepEqual(stable(await bridge.read(request(23,retained))),outputs[7]);await assert.rejects(bridge.read(request(23,retained)));await close(retained);return outputs;
 }catch(error){console.error("primary hierarchy failure",error);throw error;}finally{for(const[h,s]of [...owners].reverse()){await bridge.execute(request(10,h,s));owners.delete(h);}}
}
async function reducedMembers(bridge,multi){
 const rows=multi?16385:32769,vertices=rows*(multi?2:1),xyBytes=vertices*16,validBytes=(rows+7)&~7,offsetBytes=multi?((rows+1)*4+7)&~7:0,descriptor=new Uint8Array(64+xyBytes+validBytes+rows*8+offsetBytes),v=new DataView(descriptor.buffer);descriptor.set([88,89,71,68]);[1,multi?4:1,4326,1,0].forEach((n,i)=>v.setUint32(4+i*4,n,true));v.setBigUint64(24,BigInt(rows),true);v.setBigUint64(32,BigInt(vertices),true);v.setBigUint64(40,multi?BigInt(rows+1):0n,true);for(let i=0;i<vertices;i++)v.setFloat64(64+i*16,(i%100)*1e-7,true);descriptor.fill(1,64+xyBytes,64+xyBytes+rows);const ids=64+xyBytes+validBytes;for(let i=0;i<rows;i++)v.setBigUint64(ids+i*8,i%7?MAX-BigInt(i):MAX,true);if(multi)for(let i=0;i<=rows;i++)v.setUint32(ids+rows*8+i*4,i*2,true);
 const chunk=await bridge.read(encodeGeoChunkRequest({descriptor,rows},budget.processorBytes)),owners=new Map(),store=new Map(),outputs=[];const track=(h,s=0n)=>{owners.set(h,s);return h;},close=async h=>{await bridge.execute(request(10,h,owners.get(h)??0n));owners.delete(h);};
 try{
 const builder=track(decode(await bridge.execute(encode({command:1}))).handle);await bridge.execute(encode({command:2,handle:builder,payload:new Uint8Array(chunk)}));await bridge.execute(encode({command:3,handle:builder,generation:MAX}));const manifest=await bridge.read(encode({command:21,handle:builder})),source=track(decode(await bridge.execute(encode({command:4,payload:new Uint8Array(manifest),budget}))).handle),readChunk=async()=>chunk,info=(await driveGeoSession(bridge,{handle:source,sequence:0n,budget,readChunk})).source;
 const q={camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:8,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:1,previousDirect:true,sourceDigest:info.digest,generation:MAX,layerId:MAX,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:0},maxProjectedVertices:1000000n};await bridge.execute(encode({command:5,handle:source,sequence:1n,budget,query:q}));await driveGeoSession(bridge,{handle:source,sequence:1n,budget,readChunk});const frame=await prepareGeoSceneData(bridge,{handle:source,sequence:1n,budget,style});track(frame.handle);assert.equal(frame.data.aggregate,true);
 const p=new Uint8Array(24),pv=new DataView(p.buffer);pv.setUint32(0,1024,true);pv.setBigUint64(8,1000000n,true);pv.setBigUint64(16,64n<<20n,true);const index=track(reply(await bridge.execute(request(37,frame.handle,1n,p))).handle,1n);
 async function drive(h,seq,done){for(;;){const s=reply(await bridge.execute(request(6,h,seq)));if(s.code===done)return s;assert.ok([1,7].includes(s.code));const t=s.ticket,tv=new DataView(t.buffer),key=`${tv.getBigUint64(8,true)}:${tv.getBigUint64(40,true)}`,kind=tv.getUint32(32,true);let held,payload;try{if(kind===3){held=await bridge.read(request(40,h,seq,t));store.set(key,new Uint8Array(held).slice());}else{held=kind===1?chunk:store.get(key);const bytes=held instanceof ArrayBuffer?new Uint8Array(held):held;payload=new Uint8Array(128+bytes.length);payload.set(t);payload.set(bytes,128);await bridge.execute(request(7,h,seq,payload));}}finally{held=undefined;payload=undefined;await bridge.execute(request(kind===3?41:8,h,seq,t));}}}
 await drive(index,1n,18);const query={...q,cameraRevision:2n,timeRevision:2n,layerRevision:2n,styleRevision:2n,stateRevision:2n},session=track(reply(await bridge.execute(request(38,index,2n,undefined,query))).handle,2n);const complete=await drive(session,2n,19);assert.equal(complete.view.getUint32(192,true),2);const data=track(reply(await bridge.execute(request(39,session,2n,style))).handle),packet=await bridge.read(request(23,data)),dv=new DataView(packet);assert.equal(dv.getUint32(8,true),1);assert.equal(dv.getBigUint64(48,true),BigInt(vertices));const sceneLength=Number(dv.getBigUint64(32,true));assert.deepEqual(new Uint8Array(packet,256,sceneLength),frame.data.scene);outputs.push(stable(packet));await close(frame.handle);await close(source);await close(index);await close(session);
 let cursor,total=0;do{let payload=new Uint8Array(16+(cursor?208:0)),p=new DataView(payload.buffer);p.setUint32(4,cursor?1:0,true);p.setBigUint64(8,1000000n,true);if(cursor)payload.set(cursor,16);const members=track(reply(await bridge.execute(request(12,data,2n,payload))).handle);await driveGeoSession(bridge,{handle:members,sequence:2n,budget,readChunk});const pageData=track(reply(await bridge.execute(request(13,members,2n))).handle),bytes=await bridge.read(request(23,pageData)),page=parseGeoMembershipData(bytes);for(let i=0;i<page.length;i++){const row=page.record(i);assert.equal(row.sourceRow,BigInt(total+i));assert.equal(row.featureId,(total+i)%7?MAX-BigInt(total+i):MAX);}total+=page.length;cursor=page.cursor?.slice();const normalized=stable(bytes);normalized.fill(0,80,88);outputs.push(normalized);await close(members);await close(pageData);}while(cursor);assert.equal(total,rows);await close(data);await close(builder);return outputs;
 }finally{for(const[h,s]of [...owners].reverse())await bridge.execute(request(10,h,s));}
}

try{const results=[];for(const multi of[false,true]){const native=await run(nativeGeoScaleBridge(budget.processorBytes),multi),browser=await run(wasm,multi);assert.deepEqual(native,browser);results.push(...native.map((b,i)=>({geometry:multi?'MultiPoint':'Point',case:i,bytes:b.length,sha256:createHash('sha256').update(b).digest('hex')})));}for(const multi of[false,true]){const native=await reducedMembers(nativeGeoScaleBridge(budget.processorBytes),multi),browser=await reducedMembers(wasm,multi);assert.deepEqual(native,browser);results.push(...native.map((b,i)=>({geometry:multi?'MultiPoint':'Point',case:`reduced-members-${i}`,bytes:b.length,sha256:createHash('sha256').update(b).digest('hex')})));}const report={status:'passed',nativeAbi:JSON.parse(await readFile('spec/abi/xyg-abi.json','utf8')).abi_version,wasmAbi:x.xyg_wasm_abi_version(),recordedAt:new Date().toISOString(),node:process.version,platform:process.platform,architecture:process.arch,wasmSha256:createHash('sha256').update(artifact).digest('hex'),wasmBytes:artifact.length,wasmGzipBytes:gzipSync(artifact).length,nativeSha256:createHash('sha256').update(await readFile(process.env.XYG_NATIVE_LIB??'target/release/libxyg_core.dylib')).digest('hex'),scriptSha256:createHash('sha256').update(await readFile(new URL(import.meta.url))).digest('hex'),cases:results,claims:['native/actual wasm32 exact Scene and typed IDs/time','canonical source Scene oracle','nullable signed-i64 extrema/half-open intervals','MultiPoint/null geometry/full-u64 duplicate identity','authenticated external pages/namespace','retired cancel read/write exact ACK/copy cap','malformed/local budget reject','immutable rows/retain after owner disposal','two-pass reduced Scene/source oracle and complete exact paged membership after owner disposal','corrupt/stale/work fallback preserves oldData','selected SceneData scoped full-source build admitted'],limitations:['no browser paint or host driver','selected query42–44 parity is a separate conformance fixture','no massive latency/1B claim']};if(process.env.XYG_HIERARCHY_REPORT)await writeFile(process.env.XYG_HIERARCHY_REPORT,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));}finally{assert.equal(x.xyg_wasm_instance_dispose(wasmInstance),0);}
