#!/usr/bin/env node
// Raw test-only selected publication framing. Geometry, state, admission and LOD stay Rust-owned.
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {gzipSync} from 'node:zlib';
import {encodeGeoScaleRequest as encode,encodeGeoChunkRequest,encodeGeoScaleStyle,decodeGeoScaleReply as decode,driveGeoSession,driveGeoIndexSession,parseGeoSceneData,parseGeoRowsData,nativeGeoScaleBridge} from '../packages/xy-node/src/geoscale.js';
const MAX=0xffffffffffffffffn,MIN=-0x8000000000000000n;
const budget={processorBytes:128<<20,maxRowsExamined:1000000n,maxReadBytes:128n<<20n,maxChunks:65536,pageRows:4096};
const legacyOnly=process.env.XYG_SELECTED_PUBLICATION_LEGACY_ONLY==='1';
const style=encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0});
function raw(command,handle=0n,sequence=0n,payload,query,nonce=0n,limits=budget){if(ArrayBuffer.isView(payload))payload=new Uint8Array(payload.buffer,payload.byteOffset,payload.byteLength);const b=encode({command:query?5:6,handle,sequence,payload,query,budget:limits});const v=new DataView(b);v.setUint32(8,command,true);v.setBigUint64(240,nonce,true);return b;}
function fixed(packet){assert.equal(packet.byteLength,256);const v=new DataView(packet);assert.equal(v.getUint32(0,true),0x5a475958);assert.equal(v.getUint32(4,true),1);assert.equal(v.getUint32(12,true),0);return {code:v.getUint32(8,true),handle:v.getBigUint64(16,true),sequence:v.getBigUint64(24,true)};}
function ack(request,target,action=0){const v=new DataView(request),p=new Uint8Array(16),pv=new DataView(p.buffer);pv.setUint32(0,v.getUint32(8,true),true);pv.setUint32(4,action,true);pv.setBigUint64(8,target,true);return raw(47,v.getBigUint64(16,true),v.getBigUint64(24,true),p,undefined,v.getBigUint64(240,true));}
async function confirm(bridge,b,h,retired=false){const r=await bridge.execute(ack(b,h));assert.equal(fixed(r).code,retired?22:0);assert.equal(fixed(r).handle,retired?0n:h);assert.deepEqual(await bridge.execute(ack(b,h)),r);return r;}
async function close(bridge,h){const r=fixed(await bridge.execute(raw(10,h)));assert.equal(r.code,0);}
function normalized(packet,owner,sequence,rows=false){const v=new DataView(packet);assert.equal(v.getBigUint64(16,true),owner);assert.equal(v.getBigUint64(24,true),sequence);if(rows)assert.equal(v.getBigUint64(80,true),owner);const b=Buffer.from(packet.slice(0));b.fill(0,16,24);return b;}
function literalScene(data,vertices){
 assert.equal(data.visibleVertices,BigInt(vertices-2));
 if(data.aggregate){assert.equal(data.length,1);assert.equal(data.record(0).count,BigInt(vertices-2));assert.equal(data.selection.cell(0),BigInt(vertices-2));}
 else{assert.deepEqual(Array.from({length:data.length},(_,i)=>data.record(i)),[{featureId:MAX,sourceRow:0n,chunkIndex:0,chunkRow:0,vertex:0},{featureId:MAX,sourceRow:0n,chunkIndex:0,chunkRow:0,vertex:1}]);}
}
async function fixture(bridge,vertices,namespace=MAX){
 const validity=64+16*vertices,ids=(validity+4+7)&~7,offset=ids+32,d=new Uint8Array(offset+24),v=new DataView(d.buffer);d.set([88,89,71,68]);[1,4,4326,1,0].forEach((n,i)=>v.setUint32(4+4*i,n,true));[4n,BigInt(vertices),5n,0n,0n].forEach((n,i)=>v.setBigUint64(24+8*i,n,true));v.setFloat64(64+16*(vertices-2),1,true);v.setFloat64(64+16*(vertices-2)+8,1,true);v.setFloat64(64+16*(vertices-1),179,true);d.set([1,1,0,1],validity);[MAX,MAX,1n<<63n,9007199254740993n].forEach((n,i)=>v.setBigUint64(ids+8*i,n,true));[0,vertices-2,vertices-1,vertices-1,vertices].forEach((n,i)=>v.setUint32(offset+4*i,n,true));
 const chunk=await bridge.read(encodeGeoChunkRequest({descriptor:d,rows:4,intervals:{starts:new BigInt64Array([MIN,0n,MIN,MIN]),ends:new BigInt64Array([0n,0n,0n,0n]),startValidity:Uint8Array.of(1,1,0,1),endValidity:Uint8Array.of(1,0,0,1)}},budget.processorBytes));
 const builder=decode(await bridge.execute(raw(1))).handle;await bridge.execute(raw(2,builder,0n,chunk));const finish=encode({command:3,handle:builder,generation:MAX});await bridge.execute(finish);const manifest=await bridge.read(raw(21,builder));await close(bridge,builder);
 const source=decode(await bridge.execute(raw(4,0n,0n,manifest))).handle,readChunk=async()=>chunk;
 const info=(await driveGeoSession(bridge,{handle:source,sequence:0n,budget,readChunk})).source;
 const query={camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:2,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:1,previousDirect:true,sourceDigest:info.digest,generation:info.generation,layerId:MAX,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:1,instant:MIN},maxProjectedVertices:1000000n};
 await bridge.execute(raw(5,source,1n,undefined,query));await driveGeoSession(bridge,{handle:source,sequence:1n,budget,readChunk});const seed=fixed(await bridge.execute(raw(11,source,1n,style))).handle;
 const sp=new Uint8Array(16),sv=new DataView(sp.buffer);sv.setBigUint64(0,namespace,true);sv.setBigUint64(8,MAX,true);const scope=fixed(await bridge.execute(raw(32,seed,1n,sp))).handle;
 const publish=async()=>{const p=new Uint8Array(40),v=new DataView(p.buffer);v.setBigUint64(0,2n,true);p.set([0,255,0,255],8);v.setBigUint64(16,2n,true);v.setBigUint64(24,MAX,true);v.setBigUint64(32,MAX,true);return fixed(await bridge.execute(raw(33,scope,0n,p))).handle;};
 return {source,seed,scope,query:{...query,stateRevision:2n},readChunk,chunk,publish};
}
async function profile(bridge,vertices,journaled){
 const f=await fixture(bridge,vertices),nonce=journaled?1n:0n,packets=[],receipts=[];let canonical,index,indexed,rows,rowData;
 const state=await f.publish(),p=new BigUint64Array([state]),b=raw(35,f.source,2n,p,f.query,nonce),original=await bridge.execute(b);assert.equal(fixed(original).handle,f.source);
 if(journaled){assert.deepEqual(await bridge.execute(b),original);const changed=b.slice(0);new DataView(changed).setBigUint64(256,state+1n,true);await assert.rejects(bridge.execute(changed));await confirm(bridge,b,f.source);receipts.push({b,h:f.source});}
 await driveGeoSession(bridge,{handle:f.source,sequence:2n,budget,readChunk:f.readChunk});if(journaled)assert.deepEqual(await bridge.execute(b),original);
 const cr=await bridge.execute(raw(11,f.source,2n,style));canonical=fixed(cr).handle;assert.equal(new DataView(cr).getBigUint64(40,true),f.source);const packet=await bridge.read(raw(23,canonical)),data=parseGeoSceneData(packet);literalScene(data,vertices);assert.equal(data.selection.idCount,1);assert.equal(data.selection.id(0),MAX);assert.equal(data.selection.visibleVertices,BigInt(vertices-2));assert.equal(data.selection.cellCount,vertices>32768?1:0);assert.equal(data.identity.time.instant,MIN);packets.push(normalized(packet,f.source,2n));
 const bp=new Uint8Array(16),bv=new DataView(bp.buffer);bv.setUint32(0,2,true);bv.setBigUint64(8,1000000n,true);index=fixed(await bridge.execute(raw(17,canonical,2n,bp))).handle;const pages=new Map(),storage={readChunk:f.readChunk,readPage:async t=>pages.get(t.page),writePage:async(t,bytes)=>pages.set(t.page,bytes.slice())};await driveGeoIndexSession(bridge,{handle:index,sequence:2n,budget,...storage});
 const selectedState=await f.publish(),q=raw(36,index,3n,new BigUint64Array([selectedState]),f.query,nonce),qr=await bridge.execute(q);indexed=fixed(qr).handle;assert.equal(indexed,selectedState);
 if(journaled){assert.deepEqual(await bridge.execute(q),qr);await confirm(bridge,q,indexed);receipts.push({b:q,h:indexed});}
 await driveGeoIndexSession(bridge,{handle:indexed,sequence:3n,budget,readPage:storage.readPage});const publication=raw(19,indexed,3n,style,undefined,nonce),pr=await bridge.execute(publication);assert.equal(fixed(pr).handle,indexed);assert.equal(new DataView(pr).getBigUint64(40,true),indexed);if(journaled){assert.deepEqual(await bridge.execute(publication),pr);const changed=publication.slice(0);new Uint8Array(changed)[256]^=1;await assert.rejects(bridge.execute(changed));await confirm(bridge,publication,indexed);const wrong=ack(publication,indexed);new DataView(wrong).setBigUint64(24,4n,true);await assert.rejects(bridge.execute(wrong));}const ip=await bridge.read(raw(23,indexed)),id=parseGeoSceneData(ip);literalScene(id,vertices);assert.equal(id.selection.visibleVertices,BigInt(vertices-2));assert.equal(id.selection.id(0),MAX);packets.push(normalized(ip,indexed,3n));
 if(journaled){assert.equal(fixed(await bridge.execute(q)).code,22);await confirm(bridge,q,indexed,true);await bridge.execute(ack(q,indexed,2));}
 await close(bridge,index);index=undefined;await close(bridge,f.source);if(journaled){assert.equal(fixed(await bridge.execute(b)).code,22);await confirm(bridge,b,f.source,true);await bridge.execute(ack(b,f.source,2));}
 rows=fixed(await bridge.execute(raw(15,indexed,3n))).handle;await driveGeoSession(bridge,{handle:rows,sequence:3n,budget,readChunk:f.readChunk});rowData=fixed(await bridge.execute(raw(16,rows,3n))).handle;const rp=await bridge.read(raw(23,rowData)),rd=parseGeoRowsData(rp);assert.equal(rd.length,4);assert.deepEqual(Array.from({length:4},(_,i)=>[rd.record(i).featureId,rd.record(i).sourceRow,rd.record(i).selected,rd.record(i).geometryNull,rd.record(i).timeEligible]),[[MAX,0n,true,false,true],[MAX,1n,true,false,false],[1n<<63n,2n,false,true,true],[9007199254740993n,3n,false,false,true]]);packets.push(normalized(rp,rows,3n,true));
 await close(bridge,rows);await close(bridge,rowData);await close(bridge,canonical);await close(bridge,indexed);if(journaled){assert.equal(fixed(await bridge.execute(publication)).code,22);await confirm(bridge,publication,indexed,true);await bridge.execute(ack(publication,indexed,2));await bridge.execute(ack(publication,indexed,1));}await close(bridge,f.seed);for(const {b,h} of receipts)await bridge.execute(ack(b,h,1));await close(bridge,f.scope);return packets;
}
async function lifetimeControls(bridge){
 const f=await fixture(bridge,4),st=await f.publish(),b=raw(35,f.source,2n,new BigUint64Array([st]),f.query,1n),out=await bridge.execute(b);const ticket=await bridge.execute(raw(6,f.source,2n));assert.equal(fixed(ticket).code,1);await bridge.execute(raw(9,f.source,2n));assert.equal(fixed(await bridge.execute(b)).code,22);await confirm(bridge,b,0n,true);await bridge.execute(ack(b,0n,2));assert.equal(fixed(await bridge.execute(raw(8,f.source,0n,new Uint8Array(ticket,64,96)))).code,0);assert.equal(fixed(await bridge.execute(raw(6,f.source,2n))).code,5);await close(bridge,f.source);await bridge.execute(ack(b,0n,1));await close(bridge,f.seed);await close(bridge,f.scope);assert.equal(fixed(out).sequence,2n);
}
async function indexedLifetimeControls(bridge){
 const f=await fixture(bridge,40002),bp=new Uint8Array(16),bv=new DataView(bp.buffer);bv.setUint32(0,2,true);bv.setBigUint64(8,1000000n,true);const index=fixed(await bridge.execute(raw(17,f.seed,1n,bp))).handle,pages=new Map(),storage={readChunk:f.readChunk,readPage:async t=>pages.get(t.page),writePage:async(t,b)=>pages.set(t.page,b.slice())};await driveGeoIndexSession(bridge,{handle:index,sequence:1n,budget,...storage});let last;
 for(let mode=0;mode<3;mode++){
  const seq=BigInt(mode+2),st=await f.publish(),b=raw(36,index,seq,new BigUint64Array([st]),f.query,seq);
  if(mode===0){const fallback=raw(36,index,seq,new BigUint64Array([st]),f.query,seq,{...budget,maxChunks:1}),r=await bridge.execute(fallback);assert.equal(fixed(r).code,10);assert.equal(new DataView(r).getUint32(48,true),2);assert.deepEqual(await bridge.execute(fallback),r);await assert.rejects(bridge.execute(ack(fallback,st)));}
  const accepted=await bridge.execute(b);assert.equal(fixed(accepted).handle,st);assert.deepEqual(await bridge.execute(b),accepted);await confirm(bridge,b,st);
  const wrong=ack(b,st);new DataView(wrong).setBigUint64(24,seq+1n,true);await assert.rejects(bridge.execute(wrong));
  if(mode===1){await driveGeoIndexSession(bridge,{handle:st,sequence:seq,budget,readPage:storage.readPage});assert.deepEqual(await bridge.execute(b),accepted);await bridge.execute(raw(9,st,seq));await confirm(bridge,b,st,true);await bridge.execute(ack(b,st,2));await close(bridge,st);}
  else{const t=await bridge.execute(raw(6,st,seq));assert.equal(fixed(t).code,1);const cancelled=await bridge.execute(raw(mode===2?10:9,st,mode===2?0n:seq));assert.equal(fixed(cancelled).code,mode===2?2:0);assert.equal(fixed(await bridge.execute(b)).code,22);await confirm(bridge,b,st,true);await bridge.execute(ack(b,st,2));await bridge.execute(raw(8,st,0n,new Uint8Array(t,64,96)));await close(bridge,st);}
  last={b,st};
 }
 await close(bridge,index);await bridge.execute(ack(last.b,last.st,1));await close(bridge,f.source);await close(bridge,f.seed);await close(bridge,f.scope);
}
async function fiveIndexedPublications(bridge){
 const views=[];
 for(let i=0;i<5;i++){
  const f=await fixture(bridge,4,BigInt(100+i)),bp=new Uint8Array(16);new DataView(bp.buffer).setUint32(0,2,true);new DataView(bp.buffer).setBigUint64(8,1000000n,true);
  await close(bridge,f.source);const index=fixed(await bridge.execute(raw(17,f.seed,1n,bp))).handle,pages=new Map();
  await driveGeoIndexSession(bridge,{handle:index,sequence:1n,budget,readChunk:f.readChunk,readPage:async t=>pages.get(t.page),writePage:async(t,b)=>pages.set(t.page,b.slice())});views.push({f,index,pages});
 }
 for(const v of views){
  const {f,index,pages}=v,st=await f.publish();await assert.rejects(bridge.execute(raw(1)));
  const m=raw(36,index,2n,new BigUint64Array([st]),f.query,1n);await bridge.execute(m);await confirm(bridge,m,st);await driveGeoIndexSession(bridge,{handle:st,sequence:2n,budget,readPage:async t=>pages.get(t.page)});
  const p=raw(19,st,2n,style,undefined,1n),failed=p.slice(0);new DataView(failed).setBigUint64(32,8192n,true);await assert.rejects(bridge.execute(failed));
  const out=await bridge.execute(p);assert.equal(fixed(out).handle,st);assert.deepEqual(await bridge.execute(p),out);await confirm(bridge,p,st);await confirm(bridge,m,st,true);await bridge.execute(ack(m,st,2));await close(bridge,f.seed);f.seed=st;v.m=m;v.p=p;
 }
 for(const {f,index,m,p} of views){await close(bridge,index);await bridge.execute(ack(m,f.seed,1));await close(bridge,f.seed);await confirm(bridge,p,f.seed,true);await bridge.execute(ack(p,f.seed,2));await bridge.execute(ack(p,f.seed,1));await close(bridge,f.scope);}
}
const wasmPath=process.env.XYG_SELECTED_PUBLICATION_WASM??'packages/xy-client/dist/xyg-wasm.wasm',wasmBytes=await readFile(wasmPath),{instance}=await WebAssembly.instantiate(wasmBytes,{}),x=instance.exports,instanceId=x.xyg_wasm_instance_new(budget.processorBytes);assert.ok(instanceId);assert.equal(x.xyg_wasm_abi_version(),33);let transportSequence=0;
async function wasmCall(b,read){assert.equal(x.xyg_wasm_arena_resize(instanceId,b.byteLength),0);new Uint8Array(x.memory.buffer,x.xyg_wasm_arena_ptr(instanceId)>>>0,b.byteLength).set(new Uint8Array(b));const status=x[read?'xyg_wasm_geo_scale_read':'xyg_wasm_geo_scale_execute'](instanceId,++transportSequence,0,b.byteLength);if(status)throw new Error(`WASM:${status}`);return new Uint8Array(x.memory.buffer,x.xyg_wasm_output_ptr(instanceId)>>>0,x.xyg_wasm_output_len(instanceId)).slice().buffer;}
try{
 const wasm={execute:b=>wasmCall(b,false),read:b=>wasmCall(b,true)},native=nativeGeoScaleBridge(budget.processorBytes),packets=[],legacy=[];
 for(const opted of legacyOnly?[false]:[false,true])for(const vertices of [4,40002]){const a=await profile(native,vertices,opted),b=await profile(wasm,vertices,opted);assert.deepEqual(a,b);for(let i=0;i<a.length;i++){const entry={opted,vertices,kind:['canonicalScene','indexedScene','indexedRows'][i],bytes:a[i].length,sha256:createHash('sha256').update(a[i]).digest('hex'),base64:a[i].toString('base64')};packets.push(entry);if(!opted)legacy.push(entry);}}
 if(!legacyOnly){for(const bridge of [native,wasm]){await lifetimeControls(bridge);await indexedLifetimeControls(bridge);await fiveIndexedPublications(bridge);}}
 if(process.env.XYG_SELECTED_PUBLICATION_BASELINE){const old=JSON.parse(await readFile(process.env.XYG_SELECTED_PUBLICATION_BASELINE,'utf8'));assert.deepEqual(legacy,old.legacyPackets);}
 const report={legacyOnly,packets,legacyPackets:legacy,normalization:'Only packet owner16..24 after exact issuer/sequence validation; Rows owner80..88 remains unchanged and is validated against the requested RowsSession',artifact:{nativePath:process.env.XYG_NATIVE_LIB,nativeSha256:createHash('sha256').update(await readFile(process.env.XYG_NATIVE_LIB)).digest('hex'),wasmPath,wasmSha256:createHash('sha256').update(wasmBytes).digest('hex'),rawBytes:wasmBytes.length,gzip6Mtime0Bytes:gzipSync(wasmBytes,{level:6,mtime:0}).length},controls:['Exact successful35/36 replay after State consumption','Changed whole-wire consumedState rejects','Repeated Confirm ACK does not reallocate','35 completion and retired zero-target confirmation','36 retired Query versus19 independently live Data phase','Exact304B19 replay survives Query-kind replacement','Style mutation at same19nonce rejects','Lost19 original receipt replay and lost10 direct47 retirement, no Data resurrection','Read cancellation and exact ACK','Source/index disposal before original rows','Literal duplicate-u64/null/offscreen/i64MIN row goldens','Nonce0 baseline full packets','36 fallback and cancel before/after completion/disposal-start','Forged47 operation sequence rejects','Five indexed views publish19 at16handles, failed publication budget preserves Query'],limitations:['Engine opt-in only; selected typed owners remain nonce0','Public19 adoption and hierarchy44 recovery remain separate','No massive latency claim']};
 if(process.env.XYG_SELECTED_PUBLICATION_REPORT)await writeFile(process.env.XYG_SELECTED_PUBLICATION_REPORT,JSON.stringify(report,null,2)+'\n');console.log(`selected publication recovery: ${packets.length} full native/WASM packets, literal row/temporal goldens and ${legacyOnly?'legacy baseline':'exact mutation lifecycle controls'} PASS`);
}finally{assert.equal(x.xyg_wasm_instance_dispose(instanceId),0);}
