#!/usr/bin/env node
// Actual native/WASM protocol proof; raw extension framing is test-only.
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {encodeGeoScaleRequest as encode,decodeGeoScaleReply as decode,encodeGeoChunkRequest,encodeGeoScaleStyle,driveGeoSession,prepareGeoSceneData,nativeGeoScaleBridge} from '../packages/xy-node/src/geoscale.js';
const budget={processorBytes:128<<20,maxRowsExamined:1000000n,maxReadBytes:128n<<20n,maxChunks:65536,pageRows:4096};
const MAX=0xffffffffffffffffn,MIN=-(1n<<63n),MAX_TIME=(1n<<63n)-1n;
function request(command,handle=0n,sequence=0n,payload,query){
 const b=encode({command:query?5:6,handle,sequence,budget,payload,query});new DataView(b).setUint32(8,command,true);return b;
}
function reply(b){assert.equal(b.byteLength,256);const v=new DataView(b);assert.equal(v.getUint32(0,true),0x5a475958);return {code:v.getUint32(8,true),handle:v.getBigUint64(16,true),sequence:v.getBigUint64(24,true),length:v.getBigUint64(32,true),ticket:new Uint8Array(b,64,128).slice()};}
const {instance}=await WebAssembly.instantiate(await readFile(process.env.XYG_GEO_OVERVIEW_WASM??'packages/xy-client/dist/xyg-wasm.wasm'),{});
const x=instance.exports,wasmInstance=x.xyg_wasm_instance_new(budget.processorBytes);assert.ok(wasmInstance);let wireSeq=0;
async function call(b,read){assert.equal(x.xyg_wasm_arena_resize(wasmInstance,b.byteLength),0);new Uint8Array(x.memory.buffer,x.xyg_wasm_arena_ptr(wasmInstance)>>>0,b.byteLength).set(new Uint8Array(b));const status=x[read?'xyg_wasm_geo_scale_read':'xyg_wasm_geo_scale_execute'](wasmInstance,++wireSeq,0,b.byteLength);if(status)throw Error(`WASM status ${status}: `+new TextDecoder().decode(new Uint8Array(x.memory.buffer,x.xyg_wasm_last_error_ptr(wasmInstance)>>>0,x.xyg_wasm_last_error_len(wasmInstance))));return new Uint8Array(x.memory.buffer,x.xyg_wasm_output_ptr(wasmInstance)>>>0,x.xyg_wasm_output_len(wasmInstance)).slice().buffer;}
const wasm={execute:b=>call(b,false),read:b=>call(b,true)};
async function run(bridge){
 const descriptor=new Uint8Array(144),v=new DataView(descriptor.buffer);descriptor.set([88,89,71,68]);[1,1,4326,1,0].forEach((n,i)=>v.setUint32(4+4*i,n,true));v.setBigUint64(24,3n,true);v.setBigUint64(32,3n,true);[-90,0,0,0,90,0].forEach((n,i)=>v.setFloat64(64+i*8,n,true));descriptor.set([1,1,1],112);[MAX,9007199254740993n,7n].forEach((n,i)=>v.setBigUint64(120+8*i,n,true));
 const chunk=await bridge.read(encodeGeoChunkRequest({descriptor,rows:3,intervals:{starts:BigInt64Array.of(MIN,0n,10n),ends:BigInt64Array.of(0n,10n,0n),startValidity:Uint8Array.of(0,1,1),endValidity:Uint8Array.of(1,1,0)}},budget.processorBytes));
 const builder=decode(await bridge.execute(encode({command:1}))).handle;let source,frame,index;const dataOwners=[],queries=[],storage=new Map();
 const close=(handle,seq=0n)=>bridge.execute(request(10,handle,seq));
 try{
  await bridge.execute(encode({command:2,handle:builder,payload:new Uint8Array(chunk)}));await bridge.execute(encode({command:3,handle:builder,generation:MAX}));const manifest=await bridge.read(encode({command:21,handle:builder}));source=decode(await bridge.execute(encode({command:4,payload:new Uint8Array(manifest),budget}))).handle;
  const readChunk=async()=>chunk,info=(await driveGeoSession(bridge,{handle:source,sequence:0n,budget,readChunk})).source;
  const query={camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:0,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:1,previousDirect:true,sourceDigest:info.digest,generation:MAX,layerId:MAX,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:0},maxProjectedVertices:1000000n};
  await bridge.execute(encode({command:5,handle:source,sequence:1n,budget,query}));await driveGeoSession(bridge,{handle:source,sequence:1n,budget,readChunk});frame=await prepareGeoSceneData(bridge,{handle:source,sequence:1n,budget,style:encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0})});
  const ceiling=new Uint8Array(8);new DataView(ceiling.buffer).setBigUint64(0,1000000n,true);index=reply(await bridge.execute(request(27,frame.handle,1n,ceiling))).handle;await frame.dispose();frame=undefined;await close(source);source=undefined;
  async function drive(handle,seq,done){for(;;){const s=reply(await bridge.execute(request(6,handle,seq)));if(s.code===done)return;if(![1,7].includes(s.code))throw Error(`unexpected overview state ${s.code}`);const t=s.ticket,tv=new DataView(t.buffer),kind=tv.getUint32(32,true),length=Number(tv.getBigUint64(48,true)),key=`${tv.getBigUint64(8,true)}:${tv.getBigUint64(40,true)}`;assert.ok(length<=16*1024*1024);let borrowed,payload;
   try{if(kind===3){borrowed=await bridge.read(request(30,handle,seq,t));assert.equal(borrowed.byteLength,length);storage.set(key,new Uint8Array(borrowed).slice());}else{borrowed=kind===1?chunk:storage.get(key);assert.ok(borrowed);const bytes=borrowed instanceof ArrayBuffer?new Uint8Array(borrowed):borrowed;assert.equal(bytes.length,length);payload=new Uint8Array(128+length);payload.set(t);payload.set(bytes,128);await bridge.execute(request(7,handle,seq,payload));}}
   finally{borrowed=undefined;payload=undefined;await bridge.execute(request(kind===3?31:8,handle,seq,t));}
  }}
  await drive(index,1n,13);const outputs=[];
  const times=[{kind:0},{kind:1,instant:MIN},{kind:1,instant:0n},{kind:1,instant:10n},{kind:2,start:0n,end:10n},{kind:2,start:MIN,end:0n},{kind:1,instant:MAX_TIME},{kind:2,start:10n,end:MAX_TIME}];
  for(let i=0;i<times.length;i++){const seq=BigInt(i+2),q={...query,time:times[i],maxCells:0,previousDirect:false,maxProjectedVertices:0n,camera:{...query.camera,crs:i%2?3857:4326,pitch:i%2?60:0}};const h=reply(await bridge.execute(request(28,index,seq,undefined,q))).handle;queries.push([h,seq]);await drive(h,seq,14);const receipt=reply(await bridge.execute(request(29,h,seq)));assert.equal(receipt.code,16);dataOwners.push([receipt.handle,seq]);const bytes=await bridge.read(request(23,receipt.handle,seq)),dv=new DataView(bytes);assert.equal(bytes.byteLength,Number(receipt.length));assert.equal(dv.getUint32(0,true),0x564f5958);assert.equal(dv.getUint32(8,true),3);assert.equal(dv.getBigUint64(56,true),MAX);assert.equal(dv.getBigUint64(80,true),MAX);let total=0n;for(let cell=0;cell<256;cell++)total+=dv.getBigUint64(256+cell*8,true);assert.equal(total,i===0?3n:1n);assert.ok(Buffer.from(bytes).includes(Buffer.from('spatial refinement pending')));const stable=new Uint8Array(bytes.slice(0));stable.fill(0,16,24);outputs.push(stable);await close(h,seq);queries.pop();}
  await close(index,1n);index=undefined;
  for(const [h,seq] of dataOwners){const b=await bridge.read(request(23,h,seq));assert.equal(new DataView(b).getUint32(8,true),3);await assert.rejects(bridge.read(request(23,h,seq)));await assert.rejects(bridge.execute(request(14,h,seq,new Uint8Array(80))));}
  return outputs;
 }finally{for(const [h] of dataOwners)await close(h);for(const [h,s] of queries)await close(h,s);if(index!==undefined)await close(index,1n);if(frame)await frame.dispose();if(source!==undefined)await close(source);await close(builder);}
}
try{const native=await run(nativeGeoScaleBridge(budget.processorBytes)),browser=await run(wasm);assert.deepEqual(native,browser);if(process.env.XYG_GEO_OVERVIEW_REPORT){const artifact=await readFile(process.env.XYG_GEO_OVERVIEW_WASM??'packages/xy-client/dist/xyg-wasm.wasm');await writeFile(process.env.XYG_GEO_OVERVIEW_REPORT,JSON.stringify({recordedAt:new Date().toISOString(),node:process.version,platform:process.platform,architecture:process.arch,abi:{native:383,wasm:33},artifactSha256:createHash('sha256').update(artifact).digest('hex'),scriptSha256:createHash('sha256').update(await readFile(new URL(import.meta.url))).digest('hex'),cases:native.map((b,i)=>({case:i,expectedVertices:i===0?'3':'1',countsSha256:createHash('sha256').update(b.subarray(256,2304)).digest('hex'),sceneSha256:createHash('sha256').update(b.subarray(2304)).digest('hex'),bytes:b.length})),claims:['byte-identical native/WASM counts and Scene','typed nonfinal data-domain tier','full source/layer u64','nullable i64 MIN/MAX and half-open window','exact owning read/write ACKs','old Data after source/index/query disposal','eight-Data admission','two-copy quota','source-pick rejection'],limitations:['not overview browser paint','not massive data latency']},null,2)+'\n');}console.log('overview native/WASM: exact 256-cell temporal counts, nullable i64 extrema, half-open instant/window, full-u64 source/layer, projected Scene/pitch/cross-CRS parity, authenticated external read/write ACKs, typed nonfinal label, old data after source/index/query disposal, two-copy quotas and source-pick rejection PASS');}finally{assert.equal(x.xyg_wasm_instance_dispose(wasmInstance),0);}
