#!/usr/bin/env node
// Actual native/WASM protocol proof; raw extension framing is test-only.
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {encodeGeoScaleRequest as encode,decodeGeoScaleReply as decode,encodeGeoChunkRequest,encodeGeoScaleStyle,driveGeoSession,prepareGeoSceneData,nativeGeoScaleBridge} from '../packages/xy-node/src/geoscale.js';
import {encodeGeoOverviewRequest,decodeGeoOverviewReply,parseGeoOverviewData,driveGeoOverview,prepareGeoOverviewData} from '../packages/xy-node/src/geo-overview.js';
const budget={processorBytes:128<<20,maxRowsExamined:1000000n,maxReadBytes:128n<<20n,maxChunks:65536,pageRows:4096};
const MAX=0xffffffffffffffffn,MIN=-(1n<<63n),MAX_TIME=(1n<<63n)-1n;
function request(command,handle=0n,sequence=0n,payload,query){
 if([6,7,8,9,10,23,27,28,29,30,31].includes(command))return encodeGeoOverviewRequest({command,handle,sequence,budget,payload,query});
 const b=encode({command:query?5:6,handle,sequence,budget,payload,query});new DataView(b).setUint32(8,command,true);return b;
}
function reply(b){assert.equal(b.byteLength,256);const v=new DataView(b);assert.equal(v.getUint32(0,true),0x5a475958);return {code:v.getUint32(8,true),handle:v.getBigUint64(16,true),sequence:v.getBigUint64(24,true),length:v.getBigUint64(32,true),ticket:new Uint8Array(b,64,128).slice()};}
const {instance}=await WebAssembly.instantiate(await readFile(process.env.XYG_GEO_OVERVIEW_WASM??'packages/xy-client/dist/xyg-wasm.wasm'),{});
const x=instance.exports,wasmInstance=x.xyg_wasm_instance_new(budget.processorBytes);assert.ok(wasmInstance);let wireSeq=0;
async function call(b,read){assert.equal(x.xyg_wasm_arena_resize(wasmInstance,b.byteLength),0);new Uint8Array(x.memory.buffer,x.xyg_wasm_arena_ptr(wasmInstance)>>>0,b.byteLength).set(new Uint8Array(b));const status=x[read?'xyg_wasm_geo_scale_read':'xyg_wasm_geo_scale_execute'](wasmInstance,++wireSeq,0,b.byteLength);if(status)throw Error(`WASM status ${status}: `+new TextDecoder().decode(new Uint8Array(x.memory.buffer,x.xyg_wasm_last_error_ptr(wasmInstance)>>>0,x.xyg_wasm_last_error_len(wasmInstance))));return new Uint8Array(x.memory.buffer,x.xyg_wasm_output_ptr(wasmInstance)>>>0,x.xyg_wasm_output_len(wasmInstance)).slice().buffer;}
const wasm={execute:b=>call(b,false),read:b=>call(b,true)};
async function run(bridge){
 const descriptor=new Uint8Array(144),v=new DataView(descriptor.buffer);descriptor.set([88,89,71,68]);[1,1,4326,1,0].forEach((n,i)=>v.setUint32(4+4*i,n,true));v.setBigUint64(24,3n,true);v.setBigUint64(32,3n,true);[-90,0,0,0,90,0].forEach((n,i)=>v.setFloat64(64+i*8,n,true));descriptor.set([1,1,1],112);[MAX,9007199254740993n,7n].forEach((n,i)=>v.setBigUint64(120+8*i,n,true));
 const chunk=await bridge.read(encodeGeoChunkRequest({descriptor,rows:3,intervals:{starts:BigInt64Array.of(MIN,0n,10n),ends:BigInt64Array.of(0n,10n,0n),startValidity:Uint8Array.of(0,1,1),endValidity:Uint8Array.of(1,1,0)}},budget.processorBytes));
 const builder=decode(await bridge.execute(encode({command:1}))).handle;let source,frame,index;const dataOwners=[],ownedData=[],queries=[],storage=new Map();
 const close=(handle,seq=0n)=>bridge.execute(request(10,handle,seq));
 try{
  await bridge.execute(encode({command:2,handle:builder,payload:new Uint8Array(chunk)}));await bridge.execute(encode({command:3,handle:builder,generation:MAX}));const manifest=await bridge.read(encode({command:21,handle:builder}));source=decode(await bridge.execute(encode({command:4,payload:new Uint8Array(manifest),budget}))).handle;
  const readChunk=async()=>chunk,info=(await driveGeoSession(bridge,{handle:source,sequence:0n,budget,readChunk})).source;
  const query={camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:0,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:1,previousDirect:true,sourceDigest:info.digest,generation:MAX,layerId:MAX,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:0},maxProjectedVertices:1000000n};
  await bridge.execute(encode({command:5,handle:source,sequence:1n,budget,query}));await driveGeoSession(bridge,{handle:source,sequence:1n,budget,readChunk});frame=await prepareGeoSceneData(bridge,{handle:source,sequence:1n,budget,style:encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0})});
  const ceiling=new Uint8Array(8);new DataView(ceiling.buffer).setBigUint64(0,1000000n,true);index=reply(await bridge.execute(request(27,frame.handle,1n,ceiling))).handle;await frame.dispose();frame=undefined;await close(source);source=undefined;
  async function drive(handle,seq,done){const result=await driveGeoOverview(bridge,{handle,sequence:seq,budget,
   async readChunk(ticket){ticket.raw.fill(0);ticket.encodedBytes=1;ticket.kind=99;return chunk;},
   async readPage(ticket){const key=`${ticket.namespace}:${ticket.page}`,bytes=storage.get(key);assert.ok(bytes);ticket.raw.fill(0);ticket.encodedBytes=1;ticket.namespace=0n;return bytes.slice();},
   async writePage(ticket,bytes){const key=`${ticket.namespace}:${ticket.page}`;storage.set(key,bytes.slice());ticket.raw.fill(0);ticket.encodedBytes=1;ticket.namespace=0n;}});assert.equal(result.code,done);}
  await drive(index,1n,13);const outputs=[];
  const times=[{kind:0},{kind:1,instant:MIN},{kind:1,instant:0n},{kind:1,instant:10n},{kind:2,start:0n,end:10n},{kind:2,start:MIN,end:0n},{kind:1,instant:MAX_TIME},{kind:2,start:10n,end:MAX_TIME}];
  for(let i=0;i<times.length;i++){const seq=BigInt(i+2),q={...query,time:times[i],maxCells:0,previousDirect:false,maxProjectedVertices:0n,camera:{...query.camera,crs:i%2?3857:4326,pitch:i%2?60:0}};const h=reply(await bridge.execute(request(28,index,seq,undefined,q))).handle;queries.push([h,seq]);await drive(h,seq,14);let failDisposal=i===0;const ownerBridge={read:bridge.read,async execute(b){if(new DataView(b).getUint32(8,true)===10&&failDisposal){failDisposal=false;throw Error('transient overview disposal rejection');}return bridge.execute(b);}};const owned=await prepareGeoOverviewData(ownerBridge,{handle:h,sequence:seq,budget});ownedData.push(owned);dataOwners.push([owned.handle,seq]);const bytes=owned.data.packet,dv=new DataView(bytes);assert.equal(dv.getUint32(0,true),0x564f5958);assert.equal(dv.getUint32(8,true),3);assert.equal(dv.getBigUint64(56,true),MAX);assert.equal(dv.getBigUint64(80,true),MAX);const typed=parseGeoOverviewData(bytes);assert.equal(typed.final,false);assert.equal(typed.temporalExact,true);assert.equal(typed.dataSpace,true);assert.equal(typed.identity.layerId,MAX);assert.throws(()=>typed.count(256));let total=0n;for(let cell=0;cell<256;cell++)total+=typed.count(cell);assert.equal(total,i===0?3n:1n);assert.ok(Buffer.from(bytes).includes(Buffer.from('spatial refinement pending')));for(const [at,value] of [[0,0],[4,2],[8,7],[12,32],[40,0],[104,1],[224,3],[2308,99]]){const bad=bytes.slice(0);new DataView(bad).setUint32(at,value,true);assert.throws(()=>parseGeoOverviewData(bad));}assert.throws(()=>parseGeoOverviewData(bytes.slice(0,-1)));const stable=new Uint8Array(bytes.slice(0));stable.fill(0,16,24);outputs.push(stable);await close(h,seq);queries.pop();}

  // A cancelled callback retains its exact loan until it settles and ACKs.
  const abortQuery={...query,time:{kind:1,instant:0n},maxCells:0,previousDirect:false,maxProjectedVertices:0n};
  const abortHandle=reply(await bridge.execute(request(28,index,100n,undefined,abortQuery))).handle;
  const abort=new AbortController();let settle,enter,settled=false,acked=false;
  const entered=new Promise(r=>enter=r),gate=new Promise(r=>settle=r);
  const guarded={read:bridge.read,async execute(b){const command=new DataView(b).getUint32(8,true);if(command===8){assert.ok(settled,'ACK preceded callback settlement');acked=true;}return bridge.execute(b);}};
  const cancelled=driveGeoOverview(guarded,{handle:abortHandle,sequence:100n,budget,signal:abort.signal,readChunk:async()=>{throw Error('prefix must not reread source');},writePage:async()=>{throw Error('query must not write');},async readPage(ticket){const bytes=storage.get(`${ticket.namespace}:${ticket.page}`);assert.ok(bytes);enter();await gate;settled=true;return bytes.slice();}});
  const rejection=assert.rejects(cancelled,/aborted/);await entered;abort.abort();
  assert.equal(decodeGeoOverviewReply(await bridge.execute(request(10,abortHandle,100n))).code,2);assert.equal(acked,false);settle();await rejection;assert.ok(acked);await close(abortHandle,100n);
  // Abort while a real terminal reply is held by the bridge must not publish success.
  const terminalHandle=reply(await bridge.execute(request(28,index,101n,undefined,abortQuery))).handle;
  await drive(terminalHandle,101n,14);
  const terminalAbort=new AbortController();let terminalEnter,terminalSettle;
  const terminalEntered=new Promise(r=>terminalEnter=r),terminalGate=new Promise(r=>terminalSettle=r);
  const delayedTerminal={read:bridge.read,async execute(b){const response=await bridge.execute(b);if(new DataView(b).getUint32(8,true)===6){assert.equal(decodeGeoOverviewReply(response).code,14);terminalEnter();await terminalGate;}return response;}};
  const terminalDrive=driveGeoOverview(delayedTerminal,{handle:terminalHandle,sequence:101n,budget,signal:terminalAbort.signal,readChunk:async()=>{throw Error('terminal must not reread source');},readPage:async()=>{throw Error('terminal must not reread page');},writePage:async()=>{throw Error('terminal must not write');}});
  const terminalRejection=assert.rejects(terminalDrive,e=>e.name==='AbortError');
  await terminalEntered;terminalAbort.abort();terminalSettle();await terminalRejection;await close(terminalHandle,101n);
  await close(index,1n);index=undefined;

  for(const [h,seq] of dataOwners){const b=await bridge.read(request(23,h,seq));assert.equal(new DataView(b).getUint32(8,true),3);await assert.rejects(bridge.read(request(23,h,seq)));await assert.rejects(bridge.execute(request(14,h,seq,new Uint8Array(80))));}
  return outputs;
 }finally{for(const [i,owned] of ownedData.entries()){if(i===0){await assert.rejects(owned.dispose(),/transient/);assert.throws(()=>owned.data,/disposed/);}await owned.dispose();await owned.dispose();assert.throws(()=>owned.data,/disposed/);}for(const [h,s] of queries)await close(h,s);if(index!==undefined)await close(index,1n);if(frame)await frame.dispose();if(source!==undefined)await close(source);await close(builder);}
}
try{const native=await run(nativeGeoScaleBridge(budget.processorBytes)),browser=await run(wasm);assert.deepEqual(native,browser);if(process.env.XYG_GEO_OVERVIEW_REPORT){const artifact=await readFile(process.env.XYG_GEO_OVERVIEW_WASM??'packages/xy-client/dist/xyg-wasm.wasm');await writeFile(process.env.XYG_GEO_OVERVIEW_REPORT,JSON.stringify({recordedAt:new Date().toISOString(),node:process.version,platform:process.platform,architecture:process.arch,abi:{native:383,wasm:33},artifactSha256:createHash('sha256').update(artifact).digest('hex'),scriptSha256:createHash('sha256').update(await readFile(new URL(import.meta.url))).digest('hex'),cases:native.map((b,i)=>({case:i,expectedVertices:i===0?'3':'1',countsSha256:createHash('sha256').update(b.subarray(256,2304)).digest('hex'),sceneSha256:createHash('sha256').update(b.subarray(2304)).digest('hex'),bytes:b.length})),claims:['byte-identical native/WASM counts and Scene','typed nonfinal data-domain tier','full source/layer u64','nullable i64 MIN/MAX and half-open window','exact owning read/write ACKs','old Data after source/index/query disposal','eight-Data admission','two-copy quota','source-pick rejection','typed owning Data disposal and explicit retry after transient bridge rejection','callback ticket mutation cannot alter private ACK','cancelled read awaits callback before exact ACK','abort during real terminal reply rejects completion','nine malformed typed packet controls'],limitations:['not overview browser paint','not massive data latency']},null,2)+'\n');}console.log('overview native/WASM: exact 256-cell temporal counts, nullable i64 extrema, half-open instant/window, full-u64 source/layer, projected Scene/pitch/cross-CRS parity, authenticated external read/write ACKs, typed nonfinal label, old data after source/index/query disposal, two-copy quotas and source-pick rejection PASS');}finally{assert.equal(x.xyg_wasm_instance_dispose(wasmInstance),0);}
