#!/usr/bin/env node
// Raw 42–44 proof: framing only. Rust owns projection, selection, time and LOD.
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {gzipSync} from 'node:zlib';
import {encodeGeoScaleRequest as encode,encodeGeoChunkRequest,encodeGeoScaleStyle,driveGeoSession,nativeGeoScaleBridge} from '../packages/xy-node/src/geoscale.js';
import {nativeGeoSnapshotBridge} from '../packages/xy-node/src/geo-snapshot.js';
const budget={processorBytes:128<<20,maxRowsExamined:1000000n,maxReadBytes:128n<<20n,maxChunks:65536,pageRows:4096};
const MAX=(1n<<64n)-1n, MIN=-(1n<<63n), MAX_TIME=(1n<<63n)-1n;
const style=encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0});
function request(command,handle=0n,sequence=0n,payload,query){const b=encode({command:query?5:6,handle,sequence,budget,payload,query});new DataView(b).setUint32(8,command,true);return b;}
function reply(b){assert.equal(b.byteLength,256);const v=new DataView(b);assert.equal(v.getUint32(0,true),0x5a475958);return {code:v.getUint32(8,true),handle:v.getBigUint64(16,true),view:v,ticket:new Uint8Array(b,64,128).slice()};}
function stable(b){const bytes=new Uint8Array(b).slice();bytes.fill(0,16,24);return bytes;}
function footer(b){const v=new DataView(b),length=Number(v.getBigUint64(248,true));assert.equal(v.getUint32(4,true),2);const bytes=new Uint8Array(b,b.byteLength-length),f=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);assert.equal(f.getUint32(0,true),0x45535958);return {bytes,view:f};}
function descriptor(multi){const vertices=multi?6:3,out=new Uint8Array(64+vertices*16+8+32+(multi?24:0)),v=new DataView(out.buffer);out.set([88,89,71,68]);[1,multi?4:1,4326,1,0].forEach((n,i)=>v.setUint32(4+i*4,n,true));v.setBigUint64(24,4n,true);v.setBigUint64(32,BigInt(vertices),true);v.setBigUint64(40,multi?5n:0n,true);let at=64;for(let row=0;row<3;row++)for(let vertex=0;vertex<(multi?2:1);vertex++){v.setFloat64(at,(row-1)*0.0001+vertex*1e-7,true);at+=16;}out.set([1,1,1,0],at);at+=8;[MAX,9007199254740993n,MAX,1n<<63n].forEach((n,i)=>v.setBigUint64(at+i*8,n,true));at+=32;if(multi)[0,2,4,6,6].forEach((n,i)=>v.setUint32(at+i*4,n,true));return out;}
const artifact=await readFile(process.env.XYG_SELECTED_HIERARCHY_WASM??'packages/xy-client/dist/xyg-wasm.wasm');
const {instance}=await WebAssembly.instantiate(artifact,{}),x=instance.exports,wi=x.xyg_wasm_instance_new(budget.processorBytes);assert.ok(wi);let wireSeq=0;
async function wasmCall(b,method){assert.equal(x.xyg_wasm_arena_resize(wi,b.byteLength),0);new Uint8Array(x.memory.buffer,x.xyg_wasm_arena_ptr(wi)>>>0,b.byteLength).set(new Uint8Array(b));const status=x[method](wi,++wireSeq,0,b.byteLength);if(status)throw Error(`WASM status ${status}: `+new TextDecoder().decode(new Uint8Array(x.memory.buffer,x.xyg_wasm_last_error_ptr(wi)>>>0,x.xyg_wasm_last_error_len(wi))));return new Uint8Array(x.memory.buffer,x.xyg_wasm_output_ptr(wi)>>>0,x.xyg_wasm_output_len(wi)).slice().buffer;}
const wasm={execute:b=>wasmCall(b,'xyg_wasm_geo_scale_execute'),read:b=>wasmCall(b,'xyg_wasm_geo_scale_read')},wasmSnapshot={execute:b=>wasmCall(b,'xyg_wasm_geo_snapshot_execute'),read:b=>wasmCall(b,'xyg_wasm_geo_snapshot_read')};
function snapshotRequest(command,handle,sequence=0n){const b=new ArrayBuffer(256),v=new DataView(b);new Uint8Array(b).set([88,89,71,74]);v.setUint32(4,1,true);v.setUint32(8,command,true);v.setBigUint64(16,handle,true);v.setBigUint64(24,sequence,true);if(command===1)v.setBigUint64(32,BigInt(budget.processorBytes),true);return b;}
async function run(bridge,snapshot,multi){
 const owners=new Map(),storage=new Map(),outputs=[],track=(h,s=0n)=>{owners.set(h,s);return h;},close=async h=>{const r=reply(await bridge.execute(request(10,h,owners.get(h)??0n)));assert.notEqual(r.code,2);owners.delete(h);};let frozen;
 const readChunk=async()=>chunk;
 async function drive(h,seq,done){for(;;){const s=reply(await bridge.execute(request(6,h,seq)));if(s.code===done)return s;assert.ok([1,7].includes(s.code),`unexpected hierarchy ${s.code}`);const t=s.ticket,tv=new DataView(t.buffer),kind=tv.getUint32(32,true),n=Number(tv.getBigUint64(48,true)),key=`${tv.getBigUint64(8,true)}:${tv.getBigUint64(40,true)}`;assert.ok(n<=16<<20);let held,p;try{if(kind===3){held=await bridge.read(request(40,h,seq,t));assert.equal(held.byteLength,n);storage.set(key,new Uint8Array(held).slice());}else{held=kind===1?chunk:storage.get(key);assert.ok(held);const b=held instanceof ArrayBuffer?new Uint8Array(held):held;p=new Uint8Array(128+b.length);p.set(t);p.set(b,128);await bridge.execute(request(7,h,seq,p));}}finally{held=undefined;p=undefined;await bridge.execute(request(kind===3?41:8,h,seq,t));}}}
 async function newState(scope){const p=new Uint8Array(40),v=new DataView(p.buffer);v.setBigUint64(0,10n,true);p.set([0,255,0,255],8);v.setBigUint64(16,2n,true);v.setBigUint64(24,MAX,true);v.setBigUint64(32,1n<<63n,true);return track(reply(await bridge.execute(request(33,scope,0n,p))).handle);}
 async function selected(cmd,h,seq,q,st){const p=new Uint8Array(8);new DataView(p.buffer).setBigUint64(0,st,true);const r=reply(await bridge.execute(request(cmd,h,seq,p,q)));if(cmd===35){owners.delete(st);}else if(cmd===43&&r.code!==17){assert.equal(r.handle,st);owners.set(st,seq);}return r;}
 async function pick(frame,seq){const p=new Uint8Array(80);p.set(style);const v=new DataView(p.buffer);v.setFloat64(48,400,true);v.setFloat64(56,300,true);v.setFloat64(64,0,true);v.setUint32(72,1,true);v.setUint32(76,16,true);const d=track(reply(await bridge.execute(request(14,frame,seq,p))).handle),packet=await bridge.read(request(23,d));const b=stable(packet);b.fill(0,80,88);await close(d);return b;}
 const chunk=await bridge.read(encodeGeoChunkRequest({descriptor:descriptor(multi),rows:4,intervals:{starts:BigInt64Array.of(MIN,0n,10n,0n),ends:BigInt64Array.of(0n,10n,0n,0n),startValidity:Uint8Array.of(0,1,1,0),endValidity:Uint8Array.of(1,1,0,0)}},budget.processorBytes));
 try{
 const builder=track(reply(await bridge.execute(encode({command:1}))).handle);await bridge.execute(encode({command:2,handle:builder,payload:new Uint8Array(chunk)}));await bridge.execute(encode({command:3,handle:builder,generation:MAX}));const manifest=await bridge.read(encode({command:21,handle:builder}));const source=track(reply(await bridge.execute(encode({command:4,payload:new Uint8Array(manifest),budget}))).handle),info=(await driveGeoSession(bridge,{handle:source,sequence:0n,budget,readChunk})).source;await close(builder);
 const base={camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:8,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:32768,previousDirect:true,sourceDigest:info.digest,generation:MAX,layerId:MAX,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:0},maxProjectedVertices:1000000n};await bridge.execute(request(5,source,1n,undefined,base));await driveGeoSession(bridge,{handle:source,sequence:1n,budget,readChunk});const initial=track(reply(await bridge.execute(request(11,source,1n,style))).handle),ordinary=await bridge.read(request(23,initial));assert.equal(new DataView(ordinary).getUint32(4,true),1);outputs.push(stable(ordinary));
 const scopePayload=new Uint8Array(16),sv=new DataView(scopePayload.buffer);sv.setBigUint64(0,777n,true);sv.setBigUint64(8,MAX,true);const scope=track(reply(await bridge.execute(request(32,initial,1n,scopePayload))).handle);
 // Explicit link34 retains IDs/profile, but its distinct Scope cannot authorize this root.
 const targetPayload=scopePayload.slice();new DataView(targetPayload.buffer).setBigUint64(0,888n,true);const target=track(reply(await bridge.execute(request(32,initial,1n,targetPayload))).handle),issued=await newState(scope),link=new Uint8Array(16),lv=new DataView(link.buffer);lv.setBigUint64(0,issued,true);lv.setBigUint64(8,10n,true);const linked=track(reply(await bridge.execute(request(34,target,0n,link))).handle);
 const bp=new Uint8Array(24),bv=new DataView(bp.buffer);bv.setUint32(0,1024,true);bv.setBigUint64(8,1000000n,true);bv.setBigUint64(16,64n<<20n,true);
 const unscoped=track(reply(await bridge.execute(request(37,initial,1n,bp))).handle,1n);await drive(unscoped,1n,18);assert.equal((await selected(43,unscoped,2n,{...base,stateRevision:10n},issued)).code,17);await close(unscoped);
 const q10={...base,cameraRevision:10n,timeRevision:10n,layerRevision:10n,styleRevision:10n,stateRevision:10n};await selected(35,source,10n,q10,issued);await driveGeoSession(bridge,{handle:source,sequence:10n,budget,readChunk});const seed=track(reply(await bridge.execute(request(11,source,10n,style))).handle),seedBytes=await bridge.read(request(23,seed));assert.equal(new DataView(seedBytes).getUint32(4,true),2);
 const index=track(reply(await bridge.execute(request(37,seed,10n,bp))).handle,10n);await drive(index,10n,18);await assert.rejects(selected(43,index,11n,q10,linked));await close(linked);await close(target);await close(seed);await close(initial);
 const lanes=[index];for(let i=0;i<4;i++)lanes.push(track(reply(await bridge.execute(request(42,index,10n))).handle,10n));
 const times=[{kind:0},{kind:1,instant:MIN},{kind:1,instant:0n},{kind:1,instant:MAX_TIME},{kind:2,start:0n,end:10n}],frames=[];
 for(let i=0;i<5;i++){const seq=BigInt(11+i),q={...q10,time:times[i],camera:{...base.camera,crs:i%2?3857:4326,pitch:i%2?60:0,centerX:i===4?120:0},cameraRevision:seq,timeRevision:seq,layerRevision:seq,styleRevision:seq};const st=await newState(scope);await selected(35,source,seq,q,st);await driveGeoSession(bridge,{handle:source,sequence:seq,budget,readChunk});const reference=track(reply(await bridge.execute(request(11,source,seq,style))).handle),ref=await bridge.read(request(23,reference)),referencePick=await pick(reference,seq);const qs=await newState(scope),session=(await selected(43,lanes[i],seq,q,qs)).handle;await drive(session,seq,19);const d=reply(await bridge.execute(request(44,session,seq,style))).handle;assert.equal(d,session);owners.set(d,0n);const packet=await bridge.read(request(23,d));if(i===4){assert.equal(new DataView(ref).getBigUint64(56,true),multi?2n:1n);assert.equal(new DataView(packet).getBigUint64(56,true),0n);const refSemantic=stable(ref);new DataView(refSemantic.buffer).setBigUint64(56,0n,true);assert.deepEqual(stable(packet),refSemantic);}else assert.deepEqual(stable(packet),stable(ref));const expected=(i===4?0:i===0?3:1)*(multi?2:1);assert.equal(new DataView(packet).getBigUint64(48,true),BigInt(expected));const f=footer(packet);assert.equal(f.view.getBigUint64(24,true),2n);assert.equal(f.view.getBigUint64(40,true),BigInt((i===0?2:i===1||i===3?1:0)*(multi?2:1)));const hit=await pick(d,seq);assert.deepEqual(hit,referencePick);assert.equal(new DataView(hit.buffer).getBigUint64(32,true),BigInt(expected));outputs.push(stable(packet),hit);frames.push({handle:d,sequence:seq});await close(reference);}
 // Retire Source: Scope1 + lanes5 + five frames =11. Add State12 and four explicit controls to fill16.
 await close(source);
 const latest={...q10,cameraRevision:16n,timeRevision:16n,layerRevision:16n,styleRevision:16n};const st=await newState(scope),pressure=[];for(let i=0;i<4;i++)pressure.push(track(reply(await bridge.execute(request(42,index,10n))).handle,10n));await assert.rejects(bridge.execute(encode({command:1})));const session=(await selected(43,index,16n,latest,st)).handle;assert.equal(session,st);await drive(session,16n,19);const low=request(44,session,16n,style);new DataView(low).setBigUint64(32,4096n,true);await assert.rejects(bridge.execute(low));const replacement=reply(await bridge.execute(request(44,session,16n,style))).handle;assert.equal(replacement,session);owners.set(replacement,0n);await assert.rejects(bridge.execute(encode({command:1})));for(const h of pressure)await close(h);await close(replacement);
 for(const lane of lanes)await close(lane);await assert.rejects(bridge.execute(request(10,scope)));
 const frame=frames[0],rows=track(reply(await bridge.execute(request(15,frame.handle,frame.sequence))).handle);await driveGeoSession(bridge,{handle:rows,sequence:frame.sequence,budget,readChunk});const rowData=track(reply(await bridge.execute(request(16,rows,frame.sequence))).handle),rowBytes=await bridge.read(request(23,rowData));const rv=new DataView(rowBytes);assert.equal(rv.getBigUint64(32,true),4n);for(let i=0;i<4;i++)assert.equal((rv.getUint32(256+i*64+24,true)&128)!==0,i!==1);outputs.push(stable(rowBytes));await close(rows);await close(rowData);
 // Original rows remain available from the empty offscreen/time-filtered frame.
 const excluded=frames[4],allRows=track(reply(await bridge.execute(request(15,excluded.handle,excluded.sequence))).handle);await driveGeoSession(bridge,{handle:allRows,sequence:excluded.sequence,budget,readChunk});const allData=track(reply(await bridge.execute(request(16,allRows,excluded.sequence))).handle),allPacket=await bridge.read(request(23,allData)),av=new DataView(allPacket);assert.equal(av.getBigUint64(32,true),4n);assert.equal(av.getUint32(256+24,true)&2,0);assert.equal(av.getUint32(256+24,true)&128,128);assert.equal(av.getUint32(320+24,true)&2,2);assert.equal(av.getUint32(384+24,true)&2,0);assert.equal(av.getUint32(384+24,true)&128,128);outputs.push(stable(allPacket));await close(allRows);await close(allData);
 const frozenReceipt=await snapshot.execute(snapshotRequest(1,frame.handle,frame.sequence));assert.equal(frozenReceipt.byteLength,256);assert.equal(new DataView(frozenReceipt).getUint32(0,true),0x57475958);frozen=new DataView(frozenReceipt).getBigUint64(16,true);const frozenBytes=await snapshot.read(snapshotRequest(20,frozen));assert.ok(new Uint8Array(frozenBytes).some((_,i,b)=>i+4<=b.length&&b[i]===88&&b[i+1]===89&&b[i+2]===83&&b[i+3]===69));outputs.push(new Uint8Array(frozenBytes));await snapshot.execute(snapshotRequest(3,frozen));frozen=undefined;
 for(const frame of frames)await close(frame.handle);await close(scope);return outputs;
 }catch(error){console.error("primary selected hierarchy failure",error);throw error;}finally{if(frozen)await snapshot.execute(snapshotRequest(3,frozen));for(const[h,s]of [...owners].reverse())await bridge.execute(request(10,h,s));}
}
async function reduced(bridge,multi,density){
 const rows=multi?16385:32769,vertices=rows*(multi?2:1),xy=vertices*16,valid=(rows+7)&~7,offset=multi?((rows+1)*4+7)&~7:0,descriptor=new Uint8Array(64+xy+valid+rows*8+offset),v=new DataView(descriptor.buffer);descriptor.set([88,89,71,68]);[1,multi?4:1,4326,1,0].forEach((n,i)=>v.setUint32(4+i*4,n,true));v.setBigUint64(24,BigInt(rows),true);v.setBigUint64(32,BigInt(vertices),true);v.setBigUint64(40,multi?BigInt(rows+1):0n,true);descriptor.fill(1,64+xy,64+xy+rows);const at=64+xy+valid;for(let i=0;i<rows;i++)v.setBigUint64(at+i*8,i%7?7n:MAX,true);if(multi)for(let i=0;i<=rows;i++)v.setUint32(at+rows*8+i*4,i*2,true);
 const chunk=await bridge.read(encodeGeoChunkRequest({descriptor,rows},budget.processorBytes)),readChunk=async()=>chunk,owners=new Map(),storage=new Map(),outputs=[],track=(h,s=0n)=>{owners.set(h,s);return h;},close=async h=>{await bridge.execute(request(10,h,owners.get(h)??0n));owners.delete(h);};
 async function drive(h,seq,done){for(;;){const r=reply(await bridge.execute(request(6,h,seq)));if(r.code===done)return r;assert.ok([1,7].includes(r.code));const t=r.ticket,tv=new DataView(t.buffer),kind=tv.getUint32(32,true),key=`${tv.getBigUint64(8,true)}:${tv.getBigUint64(40,true)}`;let bytes,p;try{if(kind===3){bytes=await bridge.read(request(40,h,seq,t));storage.set(key,new Uint8Array(bytes).slice());}else{bytes=kind===1?new Uint8Array(chunk):storage.get(key);assert.ok(bytes);p=new Uint8Array(128+bytes.length);p.set(t);p.set(bytes,128);await bridge.execute(request(7,h,seq,p));}}finally{bytes=undefined;p=undefined;await bridge.execute(request(kind===3?41:8,h,seq,t));}}}
 async function issued(scope){const p=new Uint8Array(32),v=new DataView(p.buffer);v.setBigUint64(0,2n,true);p.set([0,255,0,255],8);v.setBigUint64(16,1n,true);v.setBigUint64(24,MAX,true);return track(reply(await bridge.execute(request(33,scope,0n,p))).handle);}
 try{
 const builder=track(reply(await bridge.execute(encode({command:1}))).handle);await bridge.execute(encode({command:2,handle:builder,payload:new Uint8Array(chunk)}));await bridge.execute(encode({command:3,handle:builder,generation:MAX}));const manifest=await bridge.read(encode({command:21,handle:builder})),source=track(reply(await bridge.execute(encode({command:4,payload:new Uint8Array(manifest),budget}))).handle),info=(await driveGeoSession(bridge,{handle:source,sequence:0n,budget,readChunk})).source;await close(builder);
 const q={camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:8,width:800,height:600,bearing:0,pitch:0},reducedKind:density?1:0,maxCells:1,previousDirect:true,sourceDigest:info.digest,generation:MAX,layerId:MAX,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:0},maxProjectedVertices:1000000n};await bridge.execute(request(5,source,1n,undefined,q));await driveGeoSession(bridge,{handle:source,sequence:1n,budget,readChunk});const ordinary=track(reply(await bridge.execute(request(11,source,1n,style))).handle),sp=new Uint8Array(16),sv=new DataView(sp.buffer);sv.setBigUint64(0,777n,true);sv.setBigUint64(8,MAX,true);const scope=track(reply(await bridge.execute(request(32,ordinary,1n,sp))).handle),state=await issued(scope),p=new Uint8Array(8);new DataView(p.buffer).setBigUint64(0,state,true);const selected={...q,cameraRevision:2n,timeRevision:2n,layerRevision:2n,styleRevision:2n,stateRevision:2n};await bridge.execute(request(35,source,2n,p,selected));owners.delete(state);await driveGeoSession(bridge,{handle:source,sequence:2n,budget,readChunk});const reference=track(reply(await bridge.execute(request(11,source,2n,style))).handle),ref=await bridge.read(request(23,reference));await close(ordinary);
 const bp=new Uint8Array(24),bv=new DataView(bp.buffer);bv.setUint32(0,1024,true);bv.setBigUint64(8,1000000n,true);bv.setBigUint64(16,64n<<20n,true);const index=track(reply(await bridge.execute(request(37,reference,2n,bp))).handle,2n);await drive(index,2n,18);await close(source);const qs=await issued(scope);new DataView(p.buffer).setBigUint64(0,qs,true);const query=reply(await bridge.execute(request(43,index,3n,p,selected))).handle;assert.equal(query,qs);owners.set(query,3n);await drive(query,3n,19);const d=reply(await bridge.execute(request(44,query,3n,style))).handle;assert.equal(d,query);owners.set(d,0n);const packet=await bridge.read(request(23,d));assert.deepEqual(new Uint8Array(packet,32),new Uint8Array(ref,32));const pv=new DataView(packet);assert.equal(pv.getUint32(8,true),1);assert.equal(pv.getBigUint64(48,true),BigInt(vertices));const f=footer(packet);assert.equal(f.view.getBigUint64(32,true),1n);const count=BigInt(Math.ceil(rows/7)*(multi?2:1));assert.equal(f.view.getBigUint64(40,true),count);assert.equal(f.view.getBigUint64(136,true),count);outputs.push(stable(packet));await close(reference);await close(index);
 let cursor,total=0;do{const p=new Uint8Array(16+(cursor?208:0)),v=new DataView(p.buffer);v.setUint32(4,cursor?1:0,true);v.setBigUint64(8,1000000n,true);if(cursor)p.set(cursor,16);const members=track(reply(await bridge.execute(request(12,d,3n,p))).handle);await driveGeoSession(bridge,{handle:members,sequence:3n,budget,readChunk});const data=track(reply(await bridge.execute(request(13,members,3n))).handle),packet=await bridge.read(request(23,data)),v2=new DataView(packet),n=Number(v2.getBigUint64(32,true)),cursorBytes=v2.getUint32(76,true),at=256+cursorBytes;assert.ok(n<=4096);for(let i=0;i<n;i++){assert.equal(v2.getBigUint64(at+i*32+8,true),BigInt(total+i));assert.equal(v2.getBigUint64(at+i*32,true),(total+i)%7?7n:MAX);}total+=n;cursor=cursorBytes?new Uint8Array(packet,256,cursorBytes).slice():undefined;const b=stable(packet);b.fill(0,80,88);outputs.push(b);await close(members);await close(data);}while(cursor);assert.equal(total,rows);await close(d);await close(scope);return outputs;
 }finally{for(const[h,s]of [...owners].reverse())await bridge.execute(request(10,h,s));}
}
try{const cases=[];for(const multi of[false,true]){const native=await run(nativeGeoScaleBridge(budget.processorBytes),nativeGeoSnapshotBridge(budget.processorBytes),multi),browser=await run(wasm,wasmSnapshot,multi);assert.deepEqual(native,browser);for(let i=0;i<native.length;i++)cases.push({geometry:multi?'MultiPoint':'Point',case:i,bytes:native[i].length,sha256:createHash('sha256').update(native[i]).digest('hex')});}
for(const multi of[false,true])for(const density of[false,true]){const native=await reduced(nativeGeoScaleBridge(budget.processorBytes),multi,density),browser=await reduced(wasm,multi,density);assert.deepEqual(native,browser);for(let i=0;i<native.length;i++)cases.push({geometry:multi?'MultiPoint':'Point',tier:density?'Density':'Cluster',case:`reduced-${i}`,bytes:native[i].length,sha256:createHash('sha256').update(native[i]).digest('hex')});}
const report={status:'passed',recordedAt:new Date().toISOString(),node:process.version,platform:process.platform,architecture:process.arch,nativeAbi:JSON.parse(await readFile('spec/abi/xyg-abi.json','utf8')).abi_version,wasmAbi:x.xyg_wasm_abi_version(),wasmBytes:artifact.length,wasmGzipBytes:gzipSync(artifact).length,wasmSha256:createHash('sha256').update(artifact).digest('hex'),nativeSha256:createHash('sha256').update(await readFile(process.env.XYG_NATIVE_LIB??'target/release/libxyg_core.dylib')).digest('hex'),scriptSha256:createHash('sha256').update(await readFile(new URL(import.meta.url))).digest('hex'),cases,claims:['ordinary None v1 bytes/native-WASM parity','selected canonical/selected hierarchy exact Scene+metadata+XYSE and exact hit bytes','full-u64 duplicate/null-row intent and signed-i64 time','explicit34 link and privateScope mismatch reject','unscoped43 Unsupported preserves issuedState','five independent lanes/State→Query→Data same-handle replacement','rows and frozen full intent after Source/lane disposal','two-pass selected cluster/density counts identical canonical output at32769/32770vertices','complete paged cell membership deduplicates MultiPoint original rows after Source/lane disposal'],limitations:['no selected massive latency or1B execution claim','no public live hierarchy host controller','no browser WebGL/OS/GPU ledger claim']};if(process.env.XYG_SELECTED_HIERARCHY_REPORT)await writeFile(process.env.XYG_SELECTED_HIERARCHY_REPORT,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));}finally{assert.equal(x.xyg_wasm_instance_dispose(wi),0);}
