#!/usr/bin/env node
// Raw test-only opt-in framing; public typed owners intentionally remain nonce-zero.
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fixture,budget,U64} from '../packages/xy-node/test/geoscale-fixture.mjs';
import {encodeGeoScaleRequest as encode,decodeGeoScaleReply as decode,driveGeoSession,prepareGeoSceneData,encodeGeoScaleStyle,nativeGeoScaleBridge} from '../packages/xy-node/src/geoscale.js';
import {driveGeoOverview} from '../packages/xy-node/src/geo-overview.js';
function raw(command,handle=0n,sequence=0n,payload,query,nonce=0n){const b=encode({command:query?5:6,handle,sequence,budget,payload,query});const v=new DataView(b);v.setUint32(8,command,true);v.setBigUint64(240,nonce,true);return b;}
function reply(b){assert.equal(b.byteLength,256);const v=new DataView(b);assert.equal(v.getUint32(0,true),0x5a475958);assert.equal(v.getUint32(4,true),1);return {code:v.getUint32(8,true),handle:v.getBigUint64(16,true),sequence:v.getBigUint64(24,true),length:v.getBigUint64(32,true)};}
function ack(b,target,action=0,sequence){const v=new DataView(b),p=new Uint8Array(16),d=new DataView(p.buffer);d.setUint32(0,v.getUint32(8,true),true);d.setUint32(4,action,true);d.setBigUint64(8,target,true);return raw(47,v.getBigUint64(16,true),sequence??v.getBigUint64(24,true),p,undefined,v.getBigUint64(240,true));}
const wasmPath=process.env.XYG_GEO_RECOVERY_WASM??'packages/xy-client/dist/xyg-wasm.wasm';
const {instance}=await WebAssembly.instantiate(await readFile(wasmPath),{}),x=instance.exports,id=x.xyg_wasm_instance_new(budget.processorBytes);assert.ok(id);let transportSequence=0;
async function call(b,read){assert.equal(x.xyg_wasm_arena_resize(id,b.byteLength),0);new Uint8Array(x.memory.buffer,x.xyg_wasm_arena_ptr(id)>>>0,b.byteLength).set(new Uint8Array(b));const status=x[read?'xyg_wasm_geo_scale_read':'xyg_wasm_geo_scale_execute'](id,++transportSequence,0,b.byteLength);if(status){const e=new Error(`WASM:${status}`);e.nativeCode=status===3?-9:status;throw e;}return new Uint8Array(x.memory.buffer,x.xyg_wasm_output_ptr(id)>>>0,x.xyg_wasm_output_len(id)).slice().buffer;}
const wasm={execute:b=>call(b,false),read:b=>call(b,true)};
async function run(bridge){
 const f=await fixture(bridge),chunk=Uint8Array.from(Buffer.from(f.chunk,'hex')),manifest=Uint8Array.from(Buffer.from(f.manifest,'hex'));
 const source=decode(await bridge.execute(encode({command:4,payload:manifest,budget}))).handle;
 const readChunk=async()=>chunk,info=(await driveGeoSession(bridge,{handle:source,sequence:0n,budget,readChunk})).source;
 const q={camera:{crs:4326,worldWrap:true,centerX:0,centerY:0,zoom:0,width:800,height:600,bearing:0,pitch:0},reducedKind:0,maxCells:32768,previousDirect:true,sourceDigest:info.digest,generation:info.generation,layerId:U64,cameraRevision:1n,timeRevision:1n,layerRevision:1n,styleRevision:1n,stateRevision:1n,time:{kind:1,instant:-(1n<<63n)},maxProjectedVertices:1000000n};
 await bridge.execute(raw(5,source,1n,undefined,q));await driveGeoSession(bridge,{handle:source,sequence:1n,budget,readChunk});const seed=await prepareGeoSceneData(bridge,{handle:source,sequence:1n,budget,style:encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0})});await bridge.execute(raw(10,source));
 const close=(h,s=0n)=>bridge.execute(raw(10,h,s)),forget=(b,h,s)=>bridge.execute(ack(b,h,1,s));
 const confirm=async(b,h,s)=>{const command=ack(b,h,0,s),first=await bridge.execute(command);assert.equal(reply(first).code,0);/* lost47 response: only exact ACK retries */assert.deepEqual(await bridge.execute(command),first);};
 // Five live retains from one parent; unconfirmed replacement rejects.
 const parent=reply(await bridge.execute(raw(26,seed.handle,1n))).handle,retains=[];let last;
 for(let n=1n;n<=5n;n++){const b=raw(26,parent,1n,undefined,undefined,n),first=await bridge.execute(b),h=reply(first).handle;assert.deepEqual(await bridge.execute(b),first);if(n===1n)await assert.rejects(bridge.execute(raw(26,parent,1n,undefined,undefined,2n)));await confirm(b,h);retains.push({h,b});last=b;}
 await close(parent);assert.equal(reply(await bridge.execute(last)).handle,retains[4].h);await close(retains[4].h);assert.equal(reply(await bridge.execute(last)).code,22);assert.equal(reply(await bridge.execute(ack(last,retains[4].h))).code,22);await forget(last,retains[4].h);for(const {h,b} of retains.slice(0,4)){await close(h);await bridge.execute(ack(b,h,2));}
 // Five independent ready indices from one seed and five accepted frames.
 const lanes=[],old=[],queries=[],outputs=[];let lastBuild;
 const oq={...q,maxCells:0,previousDirect:false,maxProjectedVertices:0n};
 for(let n=1n;n<=5n;n++){const p=new Uint8Array(8);new DataView(p.buffer).setBigUint64(0,1000000n,true);const b=raw(27,seed.handle,1n,p,undefined,n),h=reply(await bridge.execute(b)).handle;await confirm(b,h);const pages=new Map(),storage={readChunk,readPage:async t=>pages.get(`${t.namespace}:${t.page}`),writePage:async(t,b)=>pages.set(`${t.namespace}:${t.page}`,b.slice())};assert.equal((await driveGeoOverview(bridge,{handle:h,sequence:1n,budget,...storage})).code,13);lanes.push({h,storage,b});lastBuild=b;
 const query=reply(await bridge.execute(raw(28,h,2n,undefined,oq))).handle;await driveGeoOverview(bridge,{handle:query,sequence:2n,budget,...storage});const d=reply(await bridge.execute(raw(29,query,2n))).handle;old.push(d);await close(query,2n);}
 for(let i=0;i<5;i++){const seq=BigInt(i+3),b=raw(28,lanes[i].h,seq,undefined,oq,1n),h=reply(await bridge.execute(b)).handle;await confirm(b,h);assert.equal((await driveGeoOverview(bridge,{handle:h,sequence:seq,budget,...lanes[i].storage})).code,14);queries.push({h,seq,b});}
 // This starts with exactly16 handles. Nonce-zero29 would require a17th.
 for(let i=0;i<5;i++){const {h,seq,b}=queries[i],p=raw(29,h,seq,undefined,undefined,1n),bad=p.slice(0);new DataView(bad).setBigUint64(32,8192n,true);await assert.rejects(bridge.execute(bad));assert.equal(reply(await bridge.execute(raw(6,h,seq))).code,14);const out=await bridge.execute(p);assert.equal(reply(out).handle,h);assert.deepEqual(await bridge.execute(p),out);assert.equal(reply(await bridge.execute(b)).code,22);await confirm(p,h);await bridge.execute(ack(b,h,2));await forget(p,h);await close(old[i]);const packet=await bridge.read(raw(23,h,seq)),v=new DataView(packet);assert.equal(v.getUint32(8,true),3);assert.equal(v.getBigUint64(16,true),h);assert.equal(v.getBigUint64(24,true),seq);assert.equal(v.getBigUint64(80,true),U64);let total=0n;for(let n=0;n<256;n++)total+=v.getBigUint64(256+n*8,true);assert.equal(total,2n);const normalized=new Uint8Array(packet.slice(0));normalized.fill(0,16,24);outputs.push(Buffer.from(normalized));}
 await seed.dispose();await forget(lastBuild,lanes[4].h);for(let i=0;i<5;i++){await close(lanes[i].h,1n);await bridge.execute(ack(lanes[i].b,lanes[i].h,2));assert.equal(reply(await bridge.execute(ack(queries[i].b,queries[i].h))).code,22);await forget(queries[i].b,queries[i].h);}
 //45 is independently recovered after its authentic OverviewData issuer dies.
 const p=new Uint8Array(24),pv=new DataView(p.buffer);pv.setBigUint64(0,10n,true);pv.setUint32(8,136,true);pv.setBigUint64(16,1000n,true);const initial=raw(45,queries[0].h,queries[0].seq,p,undefined,1n),r=await bridge.execute(initial),member=reply(r).handle;assert.deepEqual(await bridge.execute(initial),r);await close(queries[0].h);assert.deepEqual(await bridge.execute(initial),r);await confirm(initial,member,10n);
 for(;;){const s=await bridge.execute(raw(6,member,10n)),code=reply(s).code;if(code===21)break;assert.equal(code,1);const t=new Uint8Array(s,64,128).slice(),payload=new Uint8Array(128+chunk.byteLength);payload.set(t);payload.set(chunk,128);await bridge.execute(raw(7,member,10n,payload));await bridge.execute(raw(8,member,10n,t));}
 const published=await bridge.execute(raw(46,member,10n));assert.equal(reply(published).handle,member);assert.equal(reply(await bridge.execute(initial)).code,22);assert.equal(reply(await bridge.execute(ack(initial,member,0,10n))).code,22);const packet=await bridge.read(raw(23,member,10n)),v=new DataView(packet);assert.equal(v.getUint32(0,true),0x4d4f5958);assert.equal(v.getBigUint64(16,true),member);assert.equal(v.getBigUint64(24,true),10n);assert.equal(v.getBigUint64(256,true),U64);assert.equal(v.getBigUint64(280,true),1n);const normalized=new Uint8Array(packet.slice(0));normalized.fill(0,16,24);outputs.push(Buffer.from(normalized));await close(member);await forget(initial,member,10n);for(const t of queries.slice(1,-1))await close(t.h);
 // Lost original allocation followed by externally retired target has no guessed ID.
 const f2=await fixture(bridge);let legacyParent;
 // fixture disposes its frame; reconstruct a source frame using the same bounded chunks.
 const s2=decode(await bridge.execute(encode({command:4,payload:Uint8Array.from(Buffer.from(f2.manifest,'hex')),budget}))).handle;await driveGeoSession(bridge,{handle:s2,sequence:0n,budget,readChunk});await bridge.execute(raw(5,s2,1n,undefined,q));await driveGeoSession(bridge,{handle:s2,sequence:1n,budget,readChunk});legacyParent=await prepareGeoSceneData(bridge,{handle:s2,sequence:1n,budget,style:encodeGeoScaleStyle({fill:Uint8Array.of(255,0,0,255),stroke:new Uint8Array(4),strokeWidth:0,diameter:6,opacity:1,symbol:0})});await close(s2);
 const lost=raw(26,legacyParent.handle,1n,undefined,undefined,1n),actual=reply(await bridge.execute(lost));await assert.rejects(bridge.execute(ack(lost,0n)));await close(actual.handle);await legacyParent.dispose();assert.equal(reply(await bridge.execute(lost)).code,22);assert.equal(reply(await bridge.execute(ack(lost,0n))).code,22);await forget(lost,0n);await assert.rejects(bridge.execute(lost));
 // Historical lost10 after receipt replacement: fixed16 retired births, no silent eviction.
 const historyParent=reply(await bridge.execute(raw(26,queries[4].h,queries[4].seq))).handle,historical=[];await close(queries[4].h);
 for(let n=1n;n<=16n;n++){const b=raw(26,historyParent,queries[4].seq,undefined,undefined,n),h=reply(await bridge.execute(b)).handle;await confirm(b,h);await close(h);historical.push({b,h});}
 const historyNext=raw(26,historyParent,queries[4].seq,undefined,undefined,17n);await assert.rejects(bridge.execute(historyNext));
 const first=historical[0];assert.equal(reply(await bridge.execute(ack(first.b,first.h))).code,22);await assert.rejects(bridge.execute(first.b));
 const release=ack(first.b,first.h,2),released=await bridge.execute(release);assert.equal(reply(released).handle,0n);assert.deepEqual(await bridge.execute(release),released);await assert.rejects(bridge.execute(ack(first.b,first.h)));
 const latest=reply(await bridge.execute(historyNext)).handle;await confirm(historyNext,latest);await assert.rejects(bridge.execute(ack(historyNext,latest,2)));
 for(const {b,h}of historical.slice(1))await bridge.execute(ack(b,h,2));await close(latest);await bridge.execute(ack(historyNext,latest,2));assert.equal(reply(await bridge.execute(historyNext)).code,22);const chainSeed=reply(await bridge.execute(raw(26,historyParent,queries[4].seq))).handle;await close(historyParent);await forget(historyNext,latest);
 let chain=chainSeed;const receipts=[];for(let n=0;n<16;n++){const b=raw(26,chain,queries[4].seq,undefined,undefined,1n),h=reply(await bridge.execute(b)).handle;await confirm(b,h);await close(chain);receipts.push([b,h]);chain=h;}
 const pressure=raw(26,chain,queries[4].seq,undefined,undefined,1n);await assert.rejects(bridge.execute(pressure));const retained=await bridge.read(raw(23,chain,queries[4].seq));assert.equal(new DataView(retained).getUint32(8,true),3);for(const [b,h]of receipts)await forget(b,h);const recovered=reply(await bridge.execute(pressure)).handle;await confirm(pressure,recovered);await close(chain);await forget(pressure,recovered);await close(recovered);return outputs;
}
try{const native=await run(nativeGeoScaleBridge(budget.processorBytes)),browser=await run(wasm);assert.deepEqual(native,browser);const report={profiles:6,normalization:'only independently validated process-local output owner16..24',packets:native.map(b=>({bytes:b.length,sha256:createHash('sha256').update(b).digest('hex'),base64:b.toString('base64')})),claims:['five live retains','five indices plus16handle sameQuery publication','exact allocation/Confirm replay and retiredphase','parent disposal','45→46 fullIDs/counts','no guessed target for lost-original retired0Confirm','historical lost10 after newer nonce','16 retired births preflight','lost successful ReleaseBirth ACK retry'],limitations:['raw opt-in engine proof; public owners still nonce0','no35/36 recovery','no massive latency claim']};if(process.env.XYG_GEO_RECOVERY_REPORT)await writeFile(process.env.XYG_GEO_RECOVERY_REPORT,JSON.stringify(report,null,2)+'\n');console.log('allocation recovery: six full native/WASM count/Scene/member packets and five-view/retired ACK controls PASS');}finally{assert.equal(x.xyg_wasm_instance_dispose(id),0);}
