// Generated by scripts/gen_wasm_abi.py from spec/wasm/abi.json.
// Do not hand-edit this typed-series wire contract.

pub const SERIES_MAGIC: &[u8; 4] = b"XYTS";
pub const SERIES_VERSION: u32 = 2;
pub const COMPILE_HEADER_BYTES: usize = 192;
pub const SERIES_DESCRIPTOR_BYTES: usize = 96;
pub const MAX_SERIES: usize = 4_096;
pub const MAX_RECORDS: usize = 10_000_000;
pub const MAX_TEXT_BYTES: usize = 4_096;
pub const MAX_SYMBOL_CODE: u32 = 18;
pub const SERIES_PEAK_FIXED_BYTES: usize = 4_096;
pub const SERIES_PEAK_BYTES_PER_RECORD: usize = 256;
pub const SERIES_PEAK_BYTES_PER_SERIES: usize = 1_024;
pub const SERIES_PEAK_INPUT_MULTIPLIER: usize = 2;
pub const HEADER_VERSION: usize = 4;
pub const HEADER_HEADER_BYTES: usize = 8;
pub const HEADER_FLAGS: usize = 12;
pub const HEADER_SERIES_COUNT: usize = 16;
pub const HEADER_RECORD_COUNT: usize = 20;
pub const HEADER_TITLE_BYTES: usize = 24;
pub const HEADER_X_LABEL_BYTES: usize = 28;
pub const HEADER_Y_LABEL_BYTES: usize = 32;
pub const HEADER_RESERVED0: usize = 36;
pub const HEADER_WIDTH: usize = 40;
pub const HEADER_HEIGHT: usize = 48;
pub const HEADER_MARGINS: usize = 56;
pub const HEADER_X_AXIS_ID: usize = 88;
pub const HEADER_Y_AXIS_ID: usize = 96;
pub const HEADER_X_SCALE_KIND: usize = 104;
pub const HEADER_Y_SCALE_KIND: usize = 108;
pub const HEADER_X_MASK_NONPOSITIVE: usize = 112;
pub const HEADER_Y_MASK_NONPOSITIVE: usize = 116;
pub const HEADER_X_LO: usize = 120;
pub const HEADER_X_HI: usize = 128;
pub const HEADER_X_CONSTANT: usize = 136;
pub const HEADER_Y_LO: usize = 144;
pub const HEADER_Y_HI: usize = 152;
pub const HEADER_Y_CONSTANT: usize = 160;
pub const HEADER_RESERVED_TAIL: usize = 168;
pub const DESCRIPTOR_KIND: usize = 0;
pub const DESCRIPTOR_SYMBOL: usize = 4;
pub const DESCRIPTOR_RECORD_COUNT: usize = 8;
pub const DESCRIPTOR_FLAGS: usize = 12;
pub const DESCRIPTOR_STABLE_ID_BASE: usize = 16;
pub const DESCRIPTOR_DIAMETER: usize = 24;
pub const DESCRIPTOR_STROKE_WIDTH: usize = 32;
pub const DESCRIPTOR_FILL_RGBA: usize = 40;
pub const DESCRIPTOR_STROKE_RGBA: usize = 44;
pub const DESCRIPTOR_X: usize = 48;
pub const DESCRIPTOR_Y: usize = 52;
pub const DESCRIPTOR_Y0: usize = 56;
pub const DESCRIPTOR_Y1: usize = 60;
pub const DESCRIPTOR_DIAMETERS: usize = 64;
pub const DESCRIPTOR_STABLE_IDS: usize = 68;
pub const HEADER_FLAG_AUTO_MARGINS: u32 = 1;
pub const HEADER_FLAG_AUTO_DOMAIN: u32 = 2;
pub const DESCRIPTOR_FLAG_DIAMETERS: u32 = 1;
pub const DESCRIPTOR_FLAG_Y0: u32 = 2;
pub const DESCRIPTOR_FLAG_Y1: u32 = 4;
pub const DESCRIPTOR_FLAG_FILL_RGBA: u32 = 8;
pub const DESCRIPTOR_FLAG_STROKE_RGBA: u32 = 16;
pub const DESCRIPTOR_FLAG_STABLE_ID_BASE: u32 = 32;
pub const DESCRIPTOR_FLAG_STABLE_IDS: u32 = 64;
pub const KIND_SCATTER: u32 = 0;
pub const KIND_LINE: u32 = 1;
pub const KIND_BAR: u32 = 2;
pub const KIND_AREA: u32 = 3;
pub const HEADER_FLAG_KNOWN: u32 = HEADER_FLAG_AUTO_MARGINS | HEADER_FLAG_AUTO_DOMAIN;
pub const DESCRIPTOR_FLAG_KNOWN: u32 = DESCRIPTOR_FLAG_DIAMETERS
    | DESCRIPTOR_FLAG_FILL_RGBA
    | DESCRIPTOR_FLAG_STABLE_ID_BASE
    | DESCRIPTOR_FLAG_STABLE_IDS
    | DESCRIPTOR_FLAG_STROKE_RGBA
    | DESCRIPTOR_FLAG_Y0
    | DESCRIPTOR_FLAG_Y1;
