// Generated Koffi declarations. Do not edit; run scripts/gen_abi_manifest.py --write.

export const ABI_VERSION = 67;
export const SIGNATURE_SHA256 = "e4e19e9ba86eff3283e936eb8c0feeae1beb5c816ab58bc0225d5dae889a815e";

export function bindAbiVersion(lib) {
  return lib.func("uint32_t xyg_abi_version()");
}

export let xyBarStack;
export let xyBin2d;
export let xyBin2dF32;
export let xyBin2dIndices;
export let xyBin2dMeanColor;
export let xyBin2dSampleRange;
export let xyBin2dStratifiedSampleRangeU8Counted;
export let xyBoxStats;
export let xyContourfBands;
export let xyContourfDensify;
export let xyCorrelation;
export let xyCssCheck;
export let xyDelaunayTriangles;
export let xyDensityLogU8;
export let xyDensityRgba;
export let xyDrillDecision;
export let xyEncodeF32;
export let xyFactorizeFixed;
export let xyFactorizeFixedU8;
export let xyFactorizeFixedU8Counts;
export let xyFactorizeUnicode1U8Counts;
export let xyGraphBuildCsr;
export let xyGraphBuildRender;
export let xyGraphClusterAggregate;
export let xyGraphForceCreate;
export let xyGraphForceDestroy;
export let xyGraphForceTick;
export let xyGraphLayout;
export let xyGraphLodDecision;
export let xyGraphProjectionCopyEdgeIds;
export let xyGraphProjectionCopyEndpoints;
export let xyGraphProjectionCopyNodeIds;
export let xyGraphProjectionCopyParents;
export let xyGraphProjectionCounts;
export let xyGraphProjectionCreate;
export let xyGraphProjectionDestroy;
export let xyGraphSampleEdges;
export let xyHeatmapRgba;
export let xyHexbin;
export let xyHistogram2d;
export let xyHistogramEdges;
export let xyHistogramUniform;
export let xyIndexedTriangles;
export let xyIsSorted;
export let xyLocalLogDensity;
export let xyLodGridShape;
export let xyLodPlan;
export let xyM4Indices;
export let xyM4Points;
export let xyMarchingSquares;
export let xyMarchingTriangles;
export let xyMinMax;
export let xyNormalizeF32;
export let xyPolygonSelect;
export let xyPolygonTriangles;
export let xyPyramidAppend;
export let xyPyramidAppendFromStream;
export let xyPyramidBuild;
export let xyPyramidBuildColor;
export let xyPyramidBuildFromStream;
export let xyPyramidCompose;
export let xyPyramidComposeColor;
export let xyPyramidCount;
export let xyPyramidFree;
export let xyQuadMeshTriangles;
export let xyQuantiles;
export let xyRangeIndices;
export let xyRangeIndicesRows;
export let xyRasterize;
export let xyRasterizeData;
export let xyRasterizePng;
export let xyRasterizePngData;
export let xyRasterizePngSpans;
export let xyRasterizeSpans;
export let xyRemapU8;
export let xyRfft;
export let xySampleMask;
export let xySampleMaskU32;
export let xySampleRangeIndices;
export let xySankeyLayout;
export let xySceneAxisTicks;
export let xySceneBatchEncode;
export let xySceneRasterCommands;
export let xySceneScaleMap;
export let xySceneScatterSvg;
export let xySceneSvg;
export let xySceneVersion;
export let xySectorTriangles;
export let xySpectrogram;
export let xyStackedBounds;
export let xyStratifiedSampleMask;
export let xyStratifiedSampleMaskU32;
export let xyStratifiedSampleRangeU8;
export let xyStratifiedSampleRangeU8Counted;
export let xyStreamAppend;
export let xyStreamCapacity;
export let xyStreamCopy;
export let xyStreamData;
export let xyStreamFree;
export let xyStreamLen;
export let xyStreamNew;
export let xyStreamSeal;
export let xyStreamZoneMaps;
export let xyStreamlines;
export let xySvgPolyPath;
export let xyTransitionKeysFixed;
export let xyTriangleEdges;
export let xyValidIndicesF64;
export let xyVectorSegments;
export let xyViolinDensity;
export let xyWeightedEcdf;
export let xyWelchSpectra;
export let xyWindRoseBins;
export let xyZoneMaps;
export let xyZoneMapsPair;

export function bindGeneratedAbi(lib) {
  xyBarStack = lib.func("int32_t xyg_bar_stack(const double * pos, size_t n_items, const double * values, size_t n_series, const double * width, size_t width_len, const double * base, size_t base_len, uint32_t mode, uint32_t orientation, double * out_x0, double * out_x1, double * out_y0, double * out_y1)");
  xyBin2d = lib.func("int32_t xyg_bin_2d(const double * x, const double * y, size_t len, double x0, double x1, double y0, double y1, size_t w, size_t h, float * out)");
  xyBin2dF32 = lib.func("int32_t xyg_bin_2d_f32(const float * x, const float * y, size_t len, double x0, double x1, double y0, double y1, size_t w, size_t h, float * out)");
  xyBin2dIndices = lib.func("size_t xyg_bin_2d_indices(const double * x, const double * y, size_t len, double x0, double x1, double y0, double y1, size_t w, size_t h, float * grid, uint32_t * idx)");
  xyBin2dMeanColor = lib.func("int32_t xyg_bin_2d_mean_color(const double * x, const double * y, size_t len, const uint8_t * idx, const uint8_t * rgba, const uint8_t * lut, size_t lut_len, double x0, double x1, double y0, double y1, size_t w, size_t h, uint8_t * out)");
  xyBin2dSampleRange = lib.func("size_t xyg_bin_2d_sample_range(const double * x, const double * y, size_t len, double x0, double x1, double y0, double y1, size_t w, size_t h, uint64_t seed, uint64_t threshold, float * grid, uint32_t * out, size_t capacity)");
  xyBin2dStratifiedSampleRangeU8Counted = lib.func("size_t xyg_bin_2d_stratified_sample_range_u8_counted(const double * x, const double * y, const uint8_t * groups, size_t len, const uint64_t * counts, size_t n_groups, double x0, double x1, double y0, double y1, size_t w, size_t h, uint64_t seed, double fraction, uint64_t min_count, float * grid, uint32_t * out, size_t capacity)");
  xyBoxStats = lib.func("int32_t xyg_box_stats(const double * data, size_t len, double * out_stats, double * out_outliers, size_t outliers_cap, size_t * out_n_outliers)");
  xyContourfBands = lib.func("size_t xyg_contourf_bands(const double * z, size_t rows, size_t cols, const double * xpos, const double * ypos, const double * edges, size_t n_edges, uint8_t extend_min, uint8_t extend_max, double * out_x0, double * out_y0, double * out_x1, double * out_y1, double * out_x2, double * out_y2, int64_t * out_slots, size_t capacity)");
  xyContourfDensify = lib.func("int32_t xyg_contourf_densify(const double * z, size_t rows, size_t cols, const double * xpos, const double * ypos, double * out_z, double * out_x, double * out_y, size_t out_z_cap, size_t out_x_cap, size_t out_y_cap, size_t * out_rows, size_t * out_cols)");
  xyCorrelation = lib.func("int32_t xyg_correlation(const double * x, const double * y, size_t len, size_t max_lag, int32_t normalize, double * out_lag, double * out_correlation)");
  xyCssCheck = lib.func("int32_t xyg_css_check(uint32_t kind, const uint8_t * prop, size_t prop_len, const uint8_t * value, size_t value_len, float * out_rgba)");
  xyDelaunayTriangles = lib.func("size_t xyg_delaunay_triangles(const double * x, const double * y, size_t len, int64_t * out, size_t capacity)");
  xyDensityLogU8 = lib.func("int32_t xyg_density_log_u8(const float * grid, size_t len, uint8_t * out, double * out_max)");
  xyDensityRgba = lib.func("int32_t xyg_density_rgba(const uint8_t * encoded, size_t w, size_t h, double maximum, const uint8_t * stops, size_t stop_count, double opacity, uint8_t * out)");
  xyDrillDecision = lib.func("int32_t xyg_drill_decision(uint64_t visible, double budget, int32_t in_drill, double exit_factor, int32_t * out_exact)");
  xyEncodeF32 = lib.func("int32_t xyg_encode_f32(const double * data, size_t len, double offset, double scale, float * out)");
  xyFactorizeFixed = lib.func("size_t xyg_factorize_fixed(const uint8_t * data, size_t len, size_t width, uint32_t * out_codes, uint32_t * out_unique_indices)");
  xyFactorizeFixedU8 = lib.func("size_t xyg_factorize_fixed_u8(const uint8_t * data, size_t len, size_t width, uint8_t * out_codes, uint32_t * out_unique_indices, size_t unique_capacity)");
  xyFactorizeFixedU8Counts = lib.func("size_t xyg_factorize_fixed_u8_counts(const uint8_t * data, size_t len, size_t width, uint8_t * out_codes, uint32_t * out_unique_indices, uint64_t * out_counts, size_t unique_capacity)");
  xyFactorizeUnicode1U8Counts = lib.func("size_t xyg_factorize_unicode1_u8_counts(const uint32_t * data, size_t len, int32_t swap_endian, uint8_t * out_codes, uint32_t * out_unique_indices, uint64_t * out_counts, size_t unique_capacity)");
  xyGraphBuildCsr = lib.func("int32_t xyg_graph_build_csr(uint64_t n_nodes, uint64_t n_edges, const uint64_t * sources, const uint64_t * targets, int32_t directed, uint64_t * out_offsets, uint64_t * out_neighbors, uint64_t neighbors_cap, uint64_t * out_neighbor_len)");
  xyGraphBuildRender = lib.func("int32_t xyg_graph_build_render(uint64_t n_nodes, uint64_t n_edges, const double * x, const double * y, const uint64_t * sources, const uint64_t * targets, uint64_t node_budget, uint64_t edge_budget, int32_t viewport_enabled, double vp_x0, double vp_y0, double vp_x1, double vp_y1, double * out_node_x, double * out_node_y, uint64_t * out_member_of, uint64_t * out_edge_sources, uint64_t * out_edge_targets, uint64_t * out_n_nodes, uint64_t * out_n_edges, uint32_t * out_tier, uint64_t * out_edges_kept)");
  xyGraphClusterAggregate = lib.func("int32_t xyg_graph_cluster_aggregate(uint64_t n_nodes, uint64_t n_edges, const double * x, const double * y, uint64_t node_budget, uint64_t edge_budget, double * out_x, double * out_y, uint64_t * out_count, uint64_t * out_member_of, uint32_t * out_tier, uint64_t * out_edges_kept)");
  xyGraphForceCreate = lib.func("int32_t xyg_graph_force_create(uint64_t n_nodes, uint64_t n_edges, const uint64_t * sources, const uint64_t * targets, const double * in_x, const double * in_y, uint64_t seed, uint32_t algorithm, uint64_t * out_handle)");
  xyGraphForceDestroy = lib.func("int32_t xyg_graph_force_destroy(uint64_t handle)");
  xyGraphForceTick = lib.func("int32_t xyg_graph_force_tick(uint64_t handle, uint64_t n_nodes, uint32_t steps, double * out_x, double * out_y, double * out_alpha)");
  xyGraphLayout = lib.func("int32_t xyg_graph_layout(uint32_t layout, uint64_t n_nodes, uint64_t n_edges, const uint64_t * sources, const uint64_t * targets, const double * in_x, const double * in_y, const uint64_t * roots, uint64_t n_roots, uint64_t seed, double * out_x, double * out_y)");
  xyGraphLodDecision = lib.func("int32_t xyg_graph_lod_decision(uint64_t n_nodes, uint64_t n_edges, uint64_t node_budget, uint64_t edge_budget, uint32_t * out_tier, uint64_t * out_edges_kept)");
  xyGraphProjectionCopyEdgeIds = lib.func("int32_t xyg_graph_projection_copy_edge_ids(uint64_t handle, uint8_t * output, uint64_t capacity)");
  xyGraphProjectionCopyEndpoints = lib.func("int32_t xyg_graph_projection_copy_endpoints(uint64_t handle, uint64_t * out_sources, uint64_t * out_targets, uint64_t capacity)");
  xyGraphProjectionCopyNodeIds = lib.func("int32_t xyg_graph_projection_copy_node_ids(uint64_t handle, uint8_t * output, uint64_t capacity)");
  xyGraphProjectionCopyParents = lib.func("int32_t xyg_graph_projection_copy_parents(uint64_t handle, uint64_t * out_parents, uint8_t * out_validity, uint64_t capacity)");
  xyGraphProjectionCounts = lib.func("int32_t xyg_graph_projection_counts(uint64_t handle, uint64_t * out_nodes, uint64_t * out_edges, uint32_t * out_directed)");
  xyGraphProjectionCreate = lib.func("int32_t xyg_graph_projection_create(const void * descriptor, uint64_t * out_handle)");
  xyGraphProjectionDestroy = lib.func("int32_t xyg_graph_projection_destroy(uint64_t handle)");
  xyGraphSampleEdges = lib.func("uint64_t xyg_graph_sample_edges(uint64_t n_edges, uint64_t budget, uint64_t * out_indices)");
  xyHeatmapRgba = lib.func("int32_t xyg_heatmap_rgba(const double * raw, size_t w, size_t h, const uint8_t * stops, size_t stop_count, uint8_t alpha, uint8_t * out)");
  xyHexbin = lib.func("size_t xyg_hexbin(const double * x, const double * y, const double * c, size_t len, size_t grid_w, size_t grid_h, double x0, double x1, double y0, double y1, size_t mincnt, int32_t reduce, double * out_cx, double * out_cy, double * out_metric, double * out_counts, size_t capacity, double * out_dx, double * out_dy)");
  xyHistogram2d = lib.func("int32_t xyg_histogram2d(const double * x, const double * y, const double * weights, size_t len, const double * x_edges, size_t x_edge_len, const double * y_edges, size_t y_edge_len, double * out)");
  xyHistogramEdges = lib.func("size_t xyg_histogram_edges(const double * data, size_t len, double lo, double hi, int32_t use_range, int32_t method, double * out_edges, size_t capacity)");
  xyHistogramUniform = lib.func("size_t xyg_histogram_uniform(const double * data, size_t len, double lo, double hi, size_t n_bins, int32_t density, double * out_counts)");
  xyIndexedTriangles = lib.func("size_t xyg_indexed_triangles(const double * x, const double * y, size_t vertex_count, const int64_t * triangles, size_t face_count, const double * values, size_t value_len, uint32_t value_mode, double * out_x0, double * out_y0, double * out_x1, double * out_y1, double * out_x2, double * out_y2, double * out_values)");
  xyIsSorted = lib.func("int32_t xyg_is_sorted(const double * data, size_t len)");
  xyLocalLogDensity = lib.func("int32_t xyg_local_log_density(const double * x, const double * y, size_t len, double lo_x, double hi_x, double lo_y, double hi_y, size_t w, size_t h, float * out)");
  xyLodGridShape = lib.func("int32_t xyg_lod_grid_shape(int32_t px_w, int32_t px_h, uint64_t visible, double target_per_cell, int32_t * out_w, int32_t * out_h)");
  xyLodPlan = lib.func("int32_t xyg_lod_plan(uint64_t visible, double budget, int32_t in_drill, double exit_factor, int32_t px_w, int32_t px_h, double target_per_cell, int32_t * out_exact, uint32_t * out_mode, int32_t * out_grid_w, int32_t * out_grid_h)");
  xyM4Indices = lib.func("size_t xyg_m4_indices(const double * x, const double * y, size_t len, double x0, double x1, size_t n_buckets, uint32_t * out)");
  xyM4Points = lib.func("size_t xyg_m4_points(const double * x, const double * y, size_t len, double x0, double x1, size_t n_buckets, double * out_x, double * out_y)");
  xyMarchingSquares = lib.func("size_t xyg_marching_squares(const double * z, size_t rows, size_t cols, const double * x_coords, const double * y_coords, const double * levels, size_t n_levels, uint8_t corner_mask, double * out_x0, double * out_x1, double * out_y0, double * out_y1, double * out_levels, size_t capacity)");
  xyMarchingTriangles = lib.func("size_t xyg_marching_triangles(const double * x, const double * y, const double * z, size_t vertex_count, const int64_t * triangles, size_t face_count, const double * levels, size_t level_count, double * out_x0, double * out_x1, double * out_y0, double * out_y1, double * out_levels, size_t capacity)");
  xyMinMax = lib.func("int32_t xyg_min_max(const double * data, size_t len, double * out_min, double * out_max)");
  xyNormalizeF32 = lib.func("int32_t xyg_normalize_f32(const double * data, size_t len, double lo, double hi, int32_t nan_mode, float * out)");
  xyPolygonSelect = lib.func("size_t xyg_polygon_select(const double * x, const double * y, size_t len, const uint32_t * rows, size_t n_rows, const double * poly_x, const double * poly_y, size_t n_poly, uint32_t * out)");
  xyPolygonTriangles = lib.func("size_t xyg_polygon_triangles(const double * x, const double * y, size_t len, int64_t * out, size_t capacity)");
  xyPyramidAppend = lib.func("int32_t xyg_pyramid_append(uint64_t handle, const double * x, const double * y, size_t len)");
  xyPyramidAppendFromStream = lib.func("int32_t xyg_pyramid_append_from_stream(uint64_t handle, uint64_t x_handle, uint64_t y_handle, size_t tail_len)");
  xyPyramidBuild = lib.func("uint64_t xyg_pyramid_build(const double * x, const double * y, size_t len, double x0, double x1, double y0, double y1, uint32_t base_dim)");
  xyPyramidBuildColor = lib.func("uint64_t xyg_pyramid_build_color(const double * x, const double * y, size_t len, const uint8_t * idx, const uint8_t * rgba, const uint8_t * lut, size_t lut_len, double x0, double x1, double y0, double y1, uint32_t base_dim)");
  xyPyramidBuildFromStream = lib.func("uint64_t xyg_pyramid_build_from_stream(uint64_t x_handle, uint64_t y_handle, double x0, double x1, double y0, double y1, uint32_t base_dim)");
  xyPyramidCompose = lib.func("int32_t xyg_pyramid_compose(uint64_t handle, double lo_x, double hi_x, double lo_y, double hi_y, size_t w, size_t h, size_t max_upsample, float * out)");
  xyPyramidComposeColor = lib.func("int32_t xyg_pyramid_compose_color(uint64_t handle, double lo_x, double hi_x, double lo_y, double hi_y, size_t w, size_t h, size_t max_upsample, float * out, uint8_t * out_rgba)");
  xyPyramidCount = lib.func("int32_t xyg_pyramid_count(uint64_t handle, double lo_x, double hi_x, double lo_y, double hi_y, double * out_count)");
  xyPyramidFree = lib.func("int32_t xyg_pyramid_free(uint64_t handle)");
  xyQuadMeshTriangles = lib.func("size_t xyg_quad_mesh_triangles(const double * x, size_t x_len, const double * y, size_t y_len, const double * values, size_t cell_rows, size_t cell_cols, uint32_t layout, double * out_x0, double * out_y0, double * out_x1, double * out_y1, double * out_x2, double * out_y2, double * out_values)");
  xyQuantiles = lib.func("size_t xyg_quantiles(const double * data, size_t len, const double * probs, size_t n_probs, double * out)");
  xyRangeIndices = lib.func("size_t xyg_range_indices(const double * x, const double * y, size_t len, double lo_x, double hi_x, double lo_y, double hi_y, uint32_t * out)");
  xyRangeIndicesRows = lib.func("size_t xyg_range_indices_rows(const double * x, const double * y, size_t len, const uint32_t * rows, size_t n_rows, double lo_x, double hi_x, double lo_y, double hi_y, uint32_t * out)");
  xyRasterize = lib.func("int32_t xyg_rasterize(const uint8_t * cmd, size_t cmd_len, uint8_t * out, size_t w, size_t h)");
  xyRasterizeData = lib.func("int32_t xyg_rasterize_data(const uint8_t * cmd, size_t cmd_len, const uint8_t * data, size_t data_len, uint8_t * out, size_t w, size_t h)");
  xyRasterizePng = lib.func("size_t xyg_rasterize_png(const uint8_t * cmd, size_t cmd_len, uint8_t * out, size_t out_capacity, size_t w, size_t h)");
  xyRasterizePngData = lib.func("size_t xyg_rasterize_png_data(const uint8_t * cmd, size_t cmd_len, const uint8_t * data, size_t data_len, uint8_t * out, size_t out_capacity, size_t w, size_t h)");
  xyRasterizePngSpans = lib.func("size_t xyg_rasterize_png_spans(const uint8_t * cmd, size_t cmd_len, const uint8_t *const * span_ptrs, const size_t * span_lens, size_t span_count, uint8_t * out, size_t out_capacity, size_t w, size_t h)");
  xyRasterizeSpans = lib.func("int32_t xyg_rasterize_spans(const uint8_t * cmd, size_t cmd_len, const uint8_t *const * span_ptrs, const size_t * span_lens, size_t span_count, uint8_t * out, size_t w, size_t h)");
  xyRemapU8 = lib.func("int32_t xyg_remap_u8(uint8_t * values, size_t len, const uint8_t * mapping, size_t mapping_len)");
  xyRfft = lib.func("int32_t xyg_rfft(const double * data, size_t len, size_t nfft, double sample_rate, double * out_frequency, double * out_real, double * out_imag)");
  xySampleMask = lib.func("int32_t xyg_sample_mask(const uint64_t * ids, size_t len, uint64_t seed, uint64_t threshold, uint8_t * out)");
  xySampleMaskU32 = lib.func("int32_t xyg_sample_mask_u32(const uint32_t * ids, size_t len, uint64_t seed, uint64_t threshold, uint8_t * out)");
  xySampleRangeIndices = lib.func("size_t xyg_sample_range_indices(size_t size, uint64_t seed, uint64_t threshold, uint32_t * out, size_t capacity)");
  xySankeyLayout = lib.func("int32_t xyg_sankey_layout(uint64_t n_nodes, uint64_t n_links, const uint64_t * sources, const uint64_t * targets, const double * values, double node_width, double node_padding, uint32_t align, uint32_t iterations, double * out_x0, double * out_y0, double * out_x1, double * out_y1, uint32_t * out_layer, double * out_value, double * out_source_y0, double * out_source_y1, double * out_target_y0, double * out_target_y1, uint32_t * out_layers, uint64_t * out_err_nodes, uint64_t * out_err_n)");
  xySceneAxisTicks = lib.func("size_t xyg_scene_axis_ticks(uint32_t kind, double lo, double hi, size_t target, double aux, double * out_ticks, double * out_labeled, size_t * out_labeled_len, double * out_step, size_t out_cap)");
  xySceneBatchEncode = lib.func("size_t xyg_scene_batch_encode(double viewport_width, double viewport_height, double margin_left, double margin_right, double margin_top, double margin_bottom, uint64_t x_axis_id, uint32_t x_kind, double x_lo, double x_hi, double x_constant, int32_t x_mask_nonpositive, uint64_t y_axis_id, uint32_t y_kind, double y_lo, double y_hi, double y_constant, int32_t y_mask_nonpositive, const uint8_t * kinds, const uint64_t * stable_ids, const uint32_t * style_refs, const uint8_t * fill_rgba, const uint8_t * stroke_rgba, const double * stroke_width, size_t style_count, const double * diameter, const uint8_t * symbols, const double * x0, const double * y0, const double * x1, const double * y1, size_t len, uint8_t * out, size_t out_cap)");
  xySceneRasterCommands = lib.func("size_t xyg_scene_raster_commands(const uint8_t * encoded, size_t encoded_len, double scale, uint8_t * out, size_t out_cap)");
  xySceneScaleMap = lib.func("int32_t xyg_scene_scale_map(const double * values, size_t len, uint32_t kind, uint32_t operation, double lo, double hi, double px0, double px1, double constant, int32_t mask_nonpositive, double * out)");
  xySceneScatterSvg = lib.func("size_t xyg_scene_scatter_svg(const double * x, const double * y, const double * diameter, const uint8_t * fill_rgba, const uint8_t * stroke_rgba, const double * stroke_width, const uint8_t * symbols, const uint8_t * visible, const uint8_t * fill_css, size_t fill_css_len, const uint8_t * stroke_css, size_t stroke_css_len, size_t len, uint8_t * out, size_t out_cap)");
  xySceneSvg = lib.func("size_t xyg_scene_svg(const uint8_t * encoded, size_t encoded_len, uint8_t * out, size_t out_cap)");
  xySceneVersion = lib.func("uint32_t xyg_scene_version()");
  xySectorTriangles = lib.func("size_t xyg_sector_triangles(const double * values, size_t len, const double * explode, double center_x, double center_y, double radius, double inner_radius, double start_degrees, int32_t counterclockwise, int32_t normalize, double * out_x0, double * out_y0, double * out_x1, double * out_y1, double * out_x2, double * out_y2, double * out_sector, size_t capacity)");
  xySpectrogram = lib.func("int32_t xyg_spectrogram(const double * data, size_t len, size_t nfft, size_t noverlap, double sample_rate, double * out_frequency, double * out_time, double * out_power)");
  xyStackedBounds = lib.func("int32_t xyg_stacked_bounds(const double * values, size_t rows, size_t cols, uint32_t baseline, double * out_lower, double * out_upper)");
  xyStratifiedSampleMask = lib.func("int32_t xyg_stratified_sample_mask(const uint64_t * ids, const uint32_t * groups, size_t len, size_t n_groups, uint64_t seed, double fraction, uint64_t min_count, uint8_t * out)");
  xyStratifiedSampleMaskU32 = lib.func("int32_t xyg_stratified_sample_mask_u32(const uint32_t * ids, const uint32_t * groups, size_t len, size_t n_groups, uint64_t seed, double fraction, uint64_t min_count, uint8_t * out)");
  xyStratifiedSampleRangeU8 = lib.func("size_t xyg_stratified_sample_range_u8(const uint8_t * groups, size_t len, size_t n_groups, uint64_t seed, double fraction, uint64_t min_count, uint32_t * out, size_t capacity)");
  xyStratifiedSampleRangeU8Counted = lib.func("size_t xyg_stratified_sample_range_u8_counted(const uint8_t * groups, size_t len, const uint64_t * counts, size_t n_groups, uint64_t seed, double fraction, uint64_t min_count, uint32_t * out, size_t capacity)");
  xyStreamAppend = lib.func("int32_t xyg_stream_append(uint64_t handle, const double * data, size_t len)");
  xyStreamCapacity = lib.func("size_t xyg_stream_capacity(uint64_t handle)");
  xyStreamCopy = lib.func("int32_t xyg_stream_copy(uint64_t handle, double * out, size_t len)");
  xyStreamData = lib.func("int32_t xyg_stream_data(uint64_t handle, const double ** out_ptr, size_t * out_len)");
  xyStreamFree = lib.func("int32_t xyg_stream_free(uint64_t handle)");
  xyStreamLen = lib.func("size_t xyg_stream_len(uint64_t handle)");
  xyStreamNew = lib.func("uint64_t xyg_stream_new(const double * data, size_t len)");
  xyStreamSeal = lib.func("int32_t xyg_stream_seal(uint64_t handle)");
  xyStreamZoneMaps = lib.func("size_t xyg_stream_zone_maps(uint64_t handle, double * out_min, double * out_max, uint64_t * out_count, uint64_t * out_null_count, double * out_sum, double * out_sum_sq, double * out_positive_min, double * out_positive_max)");
  xyStreamlines = lib.func("size_t xyg_streamlines(const double * x_coords, size_t cols, const double * y_coords, size_t rows, const double * u, const double * v, double density, size_t max_steps, double * out_x0, double * out_x1, double * out_y0, double * out_y1, size_t capacity)");
  xySvgPolyPath = lib.func("size_t xyg_svg_poly_path(const double * x, const double * y, size_t len, uint8_t * out, size_t out_cap)");
  xyTransitionKeysFixed = lib.func("int32_t xyg_transition_keys_fixed(const uint8_t * data, size_t len, size_t width, uint32_t kind, int32_t swap_endian, uint32_t * out_lo, uint32_t * out_hi, size_t * out_error_first, size_t * out_error_index)");
  xyTriangleEdges = lib.func("size_t xyg_triangle_edges(const double * x, const double * y, size_t vertex_count, const int64_t * triangles, size_t face_count, double * out_x0, double * out_x1, double * out_y0, double * out_y1)");
  xyValidIndicesF64 = lib.func("size_t xyg_valid_indices_f64(const double *const * columns, size_t n_columns, size_t len, uint64_t positive_mask, uint32_t * out, size_t capacity)");
  xyVectorSegments = lib.func("size_t xyg_vector_segments(const double * x, const double * y, const double * u, const double * v, size_t len, double scale, uint32_t pivot, double head_ratio, double * out_x0, double * out_x1, double * out_y0, double * out_y1)");
  xyViolinDensity = lib.func("int32_t xyg_violin_density(const double * data, size_t len, size_t n_bins, double * out_edges, double * out_density)");
  xyWeightedEcdf = lib.func("size_t xyg_weighted_ecdf(const double * values, const double * weights, size_t len, double * out_values, double * out_cumulative)");
  xyWelchSpectra = lib.func("int32_t xyg_welch_spectra(const double * x, const double * y, size_t len, size_t nfft, size_t noverlap, double sample_rate, double * out_frequency, double * out_pxx, double * out_pyy, double * out_pxy_real, double * out_pxy_imag)");
  xyWindRoseBins = lib.func("size_t xyg_wind_rose_bins(const double * directions, const double * speeds, size_t len, size_t sectors, const double * speed_edges, size_t n_speed_edges, double * out_edges, size_t capacity_edges, double * out_centres, double * out_counts, size_t capacity_counts, size_t * out_n_obs)");
  xyZoneMaps = lib.func("size_t xyg_zone_maps(const double * data, size_t len, size_t chunk_size, double * out_min, double * out_max, uint64_t * out_count, uint64_t * out_null_count, double * out_sum, double * out_sum_sq, double * out_positive_min, double * out_positive_max)");
  xyZoneMapsPair = lib.func("size_t xyg_zone_maps_pair(const double * x, const double * y, size_t len, size_t chunk_size, void * out_x, void * out_y)");
}
